if GetLocale() == "zhTW" then


function psealocale()


	pseachatlistldb1			= "團隊成就助手"
	pseachatlistldb2			= "點擊 = 顯示 | 隱藏 GUI設置"
	charakillintime = "條件達成！殺死堆疊有3層閃電充能的首領（30秒剩余時間）！"
	charakillintime2 = "條件達成！當他有此增益效果時擊殺首領（20秒剩余時間）！"
	chhrbrannyell = "好了，快走吧!只需要把最後的登錄程序輸入到門的機關中....然後..."
	chratitle = "    浩劫與重生英雄"
	crraraidpartachloc1 = "靜電震擊！"
	crraraidpartachloc2 = "毒泥炸彈！"
	crraraidpartachloc3 = "秘法殲滅者！"
	crraraidpartachloc4 = "火焰噴射器！"
	crratitle = "    浩劫與重生團隊"
	icratitle = "    冰冠城塞"
	icravalitriayell1 = "我打開了一道傳送門通往夢境。你們的救贖就在其中，英雄們"
	icravalitriayell2 = "我重生了!伊瑟拉賦予我讓那些邪惡生物安眠的力量!"
	nrallbuttonmaint = "區域列表"
	nrallbuttontak = "戰術"
	nxraonyemote = "深深地吸了一口氣"
	nxraonyxiab = "奧妮克希亞"
	nxratitle = "    納克薩瑪斯和其他巫妖王之怒團隊"
	phratitle = "    潘達利亞之謎英雄"
	prratitle = "    潘達利亞之謎團隊"
	psbuttonoff = "停止"
	psbuttonon = "開始"
	pseaaddonmy = "插件"
	pseaaddonoff = "關閉"
	pseaaddonok = "確定"
	pseaaddonon = "啟用插件"
	pseaaddonon2 = "開啟"
	pseachangeall = "反向選擇"
	pseachatlist1 = "團隊"
	pseachatlist2 = "團隊警报"
	pseachatlist3 = "官員"
	pseachatlist4 = "隊伍"
	pseachatlist5 = "公會"
	pseachatlist6 = "說"
	pseachatlist7 = "大喊"
	pseachatlist8 = "僅自己"
	pseadisableall = "全部禁用"
	pseaenableall = "全部啟用"
	psealeftmenu1 = "插件"
	psealeftmenu11 = "失敗後追蹤"
	psealeftmenu3 = "納克薩瑪斯"
	psealeftmenu31 = "納克薩瑪斯 + 其他巫妖王之怒團隊"
	psealeftmenu4 = "巫妖王之怒地城"
	psealeftmenu5 = "奧杜亞"
	psealeftmenu6 = "冰冠城塞"
	psealeftmenucata = "浩劫與重生英雄"
	psealeftmenucata2 = "浩劫與重生團隊"
	psealeftmenupanda = "潘達利亞之謎英雄"
	psealeftmenupanda2 = "潘達利亞之謎團隊"
	psealeftmenupanda3 = "潘達利亞之謎情景模式"
	pseamanyachtitle = "    失敗後繼續追蹤成就"
	pseamimifailloc1 = "炸彈機器人！"
	pseamimifailloc2 = "火箭攻擊！"
	pseamimifailloc3 = "環罩地雷！"
	pseamimifailloc5 = "部分已失敗！"
	pseamoduleload = "已加載的模塊："
	pseamodulenotload = "加載錯誤的模塊："
	pseaoldmodules = "舊模塊"
	pseaoldmodules2 = "    舊模塊"
	pseapartfailedloc = "部分已失敗！"
	pseapsaddonanet = "錯誤！未安裝 PhoenixStyle 插件"
	pseapsaddonanet2 = "你可以從www.phoenixstyle.com下載它"
	pseareports = "- 在此頻道中公布警報"
	pseashownames = "顯示成就失敗的原因（名字等）"
	pseashowveren = "如果在你的公會/隊伍中檢測到新版本的插件那麽顯示其更新信息"
	pseasoundoptions1 = "成就失敗時播放的音效"
	pseasoundoptions2 = "成就條件達成時播放的音效"
	pseasoundoptions3 = "只對需要的這些成就播放音效"
	pseasoundoptions6 = "主控模式，在播放音效時遊戲中的聲音被禁用"
	pseatreb2 = "條件已達成！現在可以擊殺首領！"
	pseatreb4 = "失敗！"
	pseatrebulda2 = "擊殺最後一個小怪並在之後殺死首領！"
	pseauierror = "    錯誤！"
	pseauierroraddonoff = "錯誤！插件被禁用 - 這個模塊無法使用！"
	pseauinomodule1 = "    錯誤！模塊未安裝！"
	pseauinomodule2 = "錯誤！所選模塊未安裝！"
	pseaulduarkolf1 = "怪物已被擊殺！"
	pseaulduarkolf2 = "成就將因首領被擊殺而無法達成！"
	pseaulduartitle = "    奧杜亞"
	PSFeaserver = "RU-Gordunni（漢化：TW-奥特兰克-生命祝福）"
	psmoduletxtoff = "模塊被禁用"
	psmoduletxton = "模塊已啟用"
	psoldvertxt = "（舊版本）"
	pzratitle = "    潘達利亞之謎情景模式"
	racolor1 = "紅色"
	racolor2 = "黑色"
	racolor3 = "黃色"
	racolor5 = "綠色"
	racolor6 = "紫色"
	racolorcomb = "剩余一種組合"
	racredits1 = "致謝"
	racredits2 = "    感謝您的幫助！"
	radatabrokervart = "點擊 = 顯示|隱藏"
	radeathwingemote1 = "往左翻滾！"
	radeathwingemote2 = "往右翻滾！"
	raiccof = "的"
	raiccused = "已使用"
	ramainbattleground = "戰場"
	ramainbattlegroundopt = "在戰場的入口顯示成就列表（如果它為團隊時啟用）"
	ramaintrackingtitle = "追蹤中"
	ramanyachtitinfo = "當你的一個成就失敗它的追蹤將會被阻止直到戰鬥結束。這個模塊將重置被阻止的追蹤。會在'失敗消息'的"
	ramanyachtitinfo2 = "後重置。設置一場戰鬥中應該完成多少次重置並點擊'開始'模塊。這個模塊在登出後自動禁用。"
	ramanyachtitinfoq = "將會重置阻止追蹤成就"
	ramanyachtitinfoq2 = "次於戰鬥中。更改："
	ramanyplayers = "許多玩家"
	raminibuttset = "顯示小地圖按鈕"
	ramodulnotblock = "追蹤將不會被阻止"
	ranewversfound = "|cff00ff00註意|r新版本被發現，推薦你到http://phoenixstyle.com更新它"
	ranotsure = "不準確"
	raragnaachtxt1 = "擊敗首領來獲得它！"
	raragnaachtxt2 = "成就條件達成！你有%s秒來擊敗首領！檢查你首領模塊的計時器。"
	rasec = "秒"
	ravalitnottrack = "插件不會在英雄模式中追蹤"
	rayard = "碼"
	whraaddkilled1 = "怪物已被擊殺！"
	whraaddkilled2 = "如果你現在殺死首領將無法完成成就！"
	whrabrann = "布萊恩·銅須"
	whrabrannemo = "你想玩硬的是麼"
	whrabrannemo2 = "安全性系統自動修復裝置已被關閉。開始記憶體內容消除與..."
	whragundemo = "我要讓你血肉橫飛"
	whratitle = "    巫妖王之怒英雄"
	raspectext  = "過大的戰鬥區域. 在團隊中需要更多的插件!"
	raerroraddoninst = "出錯! 插件沒有被安裝,你必須下載並安裝它:"
	raerrormodulereq = "需要額外的模塊"

racredits1				= "致謝"
racredits2				= "    感謝您的幫助！"
racredits3				= "感謝所有幫助插件改善這個插件的人！\n\n\n|cff00ff00Phoenix|r @ RU-Azuregos - 公會是一切的開始，沒有他們插件不會被開發。\n|cff00ff00Black Lotus|r @ RU-Gordunni - 一直保持著更新\n\n|cff00ff00Шурш (Shurshik)|r @ RU-Gordunni - 插件作者\n\n感謝本地化：\n德文：|cff00ff00Domestica|r @ [EU] Baelgun\n簡體中文：|cff00ff00ananhaid|r，|cff00ff00fanjunyi|r\n繁體中文：|cff00ff00fanjunyi|r\n\n訪問 http://wow.curseforge.com/addons/raidachievement/localization/\n\n\n特別感謝：\n|cff00ff00Бенефит (Benefit)|r @ RU-Drakonomor，|cff00ff00Дэи (Dei)|r @ RU-Azuregos，|cff00ff00Кайи (Kaii)|r @ RU-Azuregos，|cff00ff00Сильвин (Silwin)|r @ RU-Azuregos，|cff00ff00Львёнка (L'venka)|r @ RU-Gordunni\n\n也同樣感謝所有不斷幫助改善插件，卻不在這個名單中的人。|CFFFFFF00你有有趣的建議或者想幫助本地化？|r 在|cff00ff00www.phoenixstyle.com|r寫消息給我，我們將一起研究討論！\n\n\n\n贊助者：\n暫時沒有\n\n給你看我的插件網站|cffff0000www.phoenixstyle.com|r我希望有你感興趣的廣告。"




end


end