local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("ChocolateBar", "ruRU")
if not L then return end

-- L["A broker plugin to toggle a bar."] = ""
L["Adjust Blizzard Frames"] = "Подогнать фреймы от Blizzard" -- Needs review
-- L["Adjust the size of the tiles."] = ""
L["Advanced Textures"] = "Дополнительные текстуры" -- Needs review
-- L["Alignment"] = ""
-- L["Always adjust the center group based on the current width of the plugins. Disable this to align the center group based only on the number of plugins."] = ""
-- L["Autohide"] = ""
-- L["Automatically disable new plugins of type:"] = ""
L["Background Texture"] = "Текстура фона" -- Needs review
L["Bar Right Click"] = "Правый клик" -- Needs review
L["Bars"] = "Бары" -- Needs review
L["Bar Settings"] = "Настройки" -- Needs review
L["Bar Size"] = "Размер бара" -- Needs review
-- L["Bar Strata"] = ""
-- L["Bar Width"] = ""
L["Blizzard Options"] = "Опции Blizzard" -- Needs review
-- L["Border Color/Alpha"] = ""
L["Center"] = "Центр" -- Needs review
L["ChocolateBar Options"] = "Опции ChocolateBar" -- Needs review
L["Could not load ChocolateBar_Options, make sure it's installed."] = "Невозможно загрузить ChocolateBar_Options, проверьте, установлен ли он." -- Needs review
L["Create Bar"] = "Создать бар" -- Needs review
L["Create New Bar"] = "Создать новый бар" -- Needs review
-- L["Data Source"] = ""
-- L["Debug"] = ""
L["Defaults"] = "По умолчанию" -- Needs review
L["Default text color of a plugin. This will not overwrite plugins that use own colors."] = "Цвет текста плагина по умолчанию. Это не перезапишет плагины, которые используют свои цвета." -- Needs review
-- L["Delay"] = ""
-- L["Desaturated Icons"] = ""
L["Disable All"] = "Выключить все" -- Needs review
-- L["Disable all Launchers"] = ""
-- L["Disable all the bad guy's:)"] = ""
-- L["Disable Clicking"] = ""
L["Disabled"] = "Выключено" -- Needs review
L["Disable Options"] = "Выключить опции" -- Needs review
-- L["Disable options dialog on right click"] = ""
L["Disable Plugin"] = "Отключить плагин" -- Needs review
L["Disable Tooltips"] = "Выключить подсказки" -- Needs review
-- L["Eat all the chocolate at once, uff..."] = ""
-- L["Eat a whole chocolate bar, oh my.."] = ""
L["Enable All"] = "Включить все" -- Needs review
L["Enabled"] = "Включено" -- Needs review
-- L["Enable free placement for this bar"] = ""
-- L["Fixed"] = ""
-- L["Fixed/Max Text Width"] = ""
L["Font"] = "Шрифт" -- Needs review
L["Fonts and Textures"] = "Шрифты и текстуры" -- Needs review
L["Font Size"] = "Размер шрифта" -- Needs review
-- L["Force Text Color"] = ""
-- L["Free"] = ""
-- L["Free Placement"] = ""
-- L["Gap"] = ""
L["General"] = "Основное" -- Needs review
-- L["Get back my plugins!"] = ""
L["Hide Bars"] = "Спрятать бары" -- Needs review
-- L["Hide Bars during a Pet Battle."] = ""
-- L["Hide Bars in Pet Battle"] = ""
-- L["Hide In Combat"] = ""
-- L["Hide this bar during combat."] = ""
-- L["Hold alt key to drag a plugin."] = ""
-- L["Horizontal Offset"] = ""
-- L["How should the plugin width adapt to the text?"] = ""
L["Icon Size"] = "Размер иконки" -- Needs review
-- L["Icon size in relation to the bar height."] = ""
-- L["If enabled new plugins of type data source will automatically be disabled."] = ""
-- L["If enabled new plugins of type launcher will automatically be disabled."] = ""
L["In Combat"] = "В бою" -- Needs review
-- L["Launcher"] = ""
L["Left"] = "Лево" -- Needs review
L["Locked"] = "Заблокирован" -- Needs review
L["Lock Plugins"] = "Блокировать плагины" -- Needs review
-- L["Look and Feel"] = ""
-- L["Managed Placement"] = ""
-- L["Manage this Bar"] = ""
-- L["Max"] = ""
L["Move Blizzard frames above/below bars"] = "Двигать фреймы от Blizzard выше/ниже баров" -- Needs review
L["Move Down"] = "Двигать ниже" -- Needs review
L["Move Up"] = "Двигать выше" -- Needs review
-- L["none"] = ""
-- L["None"] = ""
L["Opacity"] = "Прозрачность" -- Needs review
L["Options"] = "Опции" -- Needs review
L["Other"] = "Другое" -- Needs review
-- L["Overwrite Icon Size"] = ""
-- L["Overwrite Text Offset"] = ""
L["Plugins"] = "Плагины" -- Needs review
L["Plugin Statistics"] = "Статистика плагинов" -- Needs review
-- L["Quick Config"] = ""
L["Remove Bar"] = "Убрать бар" -- Needs review
-- L["Remove custom colors from plugins."] = ""
L["Right"] = "Право" -- Needs review
L["Select Bar"] = "Выбрать бар" -- Needs review
-- L["Select the action when right clicking on a bar."] = ""
L["Set a width for the bar."] = "Установить ширину бара" -- Needs review
-- L["Set fixed or max width for the text."] = ""
L["Set seconds until bar will hide."] = "Установить кол-во секунд, до тех пор пока бар не спрячется." -- Needs review
-- L["Set the distance between the icon and the text."] = ""
-- L["Set the gap between the plugins."] = ""
L["Set the opacity of the bars during combat."] = "Установить прозрачность баров во время боя." -- Needs review
L["Show Icon"] = "Показать иконку" -- Needs review
-- L["Show icons in gray scale mode (This will not affect icons embedded in the text of a plugin)."] = ""
L["Show Text"] = "Показать текст" -- Needs review
-- L["Some of the fonts may depend on other addons."] = ""
-- L["Some of the textures may depend on other addons."] = ""
L["Text color"] = "Цвет текста" -- Needs review
-- L["Text Offset"] = ""
L["Texture Color/Alpha"] = "Цвет/прозрачность текстуры" -- Needs review
L["Textures"] = "Текстуры" -- Needs review
-- L["Tile"] = ""
-- L["Tile Size"] = ""
-- L["Tile the Texture. Disable to stretch the Texture."] = ""
L["Toggle Text"] = "Включить текст" -- Needs review
L["Total"] = "Всего" -- Needs review
L["Type"] = "Тип" -- Needs review
L["Unlock to to move the bar anywhere you want."] = "Разблокировать бар, чтобы его передвигать." -- Needs review
-- L["Update Center Position"] = ""
-- L["Vertical Offset"] = ""
-- L["Width Behavior"] = ""
