


function psealocalem()


pseachatlistldb1			= "RaidAchievement"
pseachatlistldb2			= "Click = Show | Hide"
pseachatlist1				= "raid"
pseachatlist2				= "raid warning"
pseachatlist3				= "officer"
pseachatlist4				= "party"
pseachatlist5				= "guild"
pseachatlist6				= "say"
pseachatlist7				= "yell"
pseachatlist8				= "self only"
pseaaddonmy				= "AddOn"
pseaaddonon2				= "ON"
pseaaddonoff				= "OFF"
pseamoduleload				= "Module loaded:"
pseamodulenotload			= "Error while loading module:"
pseaaddonon				= "Enable addon"
pseaaddonok				= "OK"
pseatreb2				= "requirements completed! Kill the boss now!"
pseatreb4				= "failed!"
ranewversfound				= "|cff00ff00Attention!|r New version was found, it's recommended to update it from http://phoenixstyle.com"
nrallbuttonmaint			= "List for zone"
nrallbuttontak				= "Tactics"
pseapartfailedloc			= "part is failed!"
ramaintrackingtitle			= "Tracking"
racolorcomb           = "LEFT ONE combination"
racolor5               = "green"
racolor1               = "red"
racolor2               = "black"
racolor3               = "yellow"
racolor6               = "purple"
radeathwingemote1			= " rolls left!"
radeathwingemote2			= " rolls right!"
raspectext            = "Too big fight zone. Requests more addons in the raid!"


psealeftmenu1				= "AddOn"
psealeftmenu3				= "Naxxramas"
psealeftmenu31				= "Naxxramas + other mini WotLK raids"
psealeftmenu4				= "Wotlk dungeons"
psealeftmenu5				= "Ulduar"
psealeftmenu6				= "Icecrown"
pseareports				= "- chat channel to announce warnings"
PSFeaserver				= "ru-Gordunni"
pseauinomodule1				= "    Error! Module is not installed!"
pseauinomodule2				= "Error! Module chosen is not installed!"
pseauierror				= "    Error!"
pseauierroraddonoff			= "Error! Addon is disabled - this module is unavailable!"
pseapsaddonanet				= "Error! Addon PhoenixStyle is not installed"
pseapsaddonanet2			= "You can download it from www.phoenixstyle.com"
pseaenableall				= "Enable all"
pseadisableall				= "Disable all"
pseachangeall				= "Switch"
pseashownames				= "Show the reason (name, etc) of the achievement's failure"
pseashowveren				= "Show msg if a new version of the addon is detected in your guild/party"
psealeftmenu11				= "Track after fail"
pseamanyachtitle			= "    Keep tracking achivement after its failure"
ramanyachtitinfo			= "When you fail an achievement its tracking is blocked until fight ends. This module resets the blocking. Reset occurs in "
ramanyachtitinfo2			= "after 'fail message'. Set how many resets for a fight should be done and click 'start' module. This module is autodisabled after logout."
psbuttonon				= "Start"
psbuttonoff				= "STOP"
psmoduletxton				= "module is enabled"
psmoduletxtoff				= "module is disabled"
rasec					= "sec."
ramanyachtitinfoq			= "Blocking achievement tracking will be reset"
ramanyachtitinfoq2			= "times for the fight. Change:"
ramodulnotblock				= "tracking will not be blocked"
psoldvertxt				= "(old version)"
raminibuttset				= "Show minimap button"
psealeftmenucata			= "Cata Heroics"
psealeftmenucata2			= "Cata Raids"
pseasoundoptions1			= "Play sound on achievement fail"
pseasoundoptions2			= "Play sound on requirements completed"
pseasoundoptions3			= "Play sound only if i need this achievement"
pseasoundoptions6			= "Master mode, play sound when in-game sound is disabled"

nxraonyxiab				= "Onyxia"
nxraonyemote				= "takes in a deep breath"
nxratitle				= "    Naxxramas + other mini WotLK raids"
icravalitriayell1			= "I have opened a portal into the Dream. Your salvation lies within, heroes..."
icravalitriayell2			= "I AM RENEWED! Ysera grant me the favor to lay these foul creatures to rest!"
icratitle				= "    Icecrown"
raiccof					= "of"
raiccused				= "used"
ravalitnottrack				= "doesn't track in heroic by addon"
crratitle				= "    Cataclysm Raids"
crraraidpartachloc1			= "Static Shock!"
crraraidpartachloc2			= "Poison Bomb!"
crraraidpartachloc3			= "Arcane Annihilator!"
crraraidpartachloc4			= "Flamethrower!"
chratitle				= "    Cataclysm Heroic"
charakillintime				= "Requirements completed! Kill boss with 3 stacks of Lightning Charge (30 sec left)!"
charakillintime2			= "Requirements completed! Kill boss when he has buff (20 sec left)!"
chhrbrannyell				= "Right, let's go! Just need to input the final entry sequence into the door mechanism... and..."
pseaulduarkolf1				= "Add was killed!"
pseaulduarkolf2				= "will not be complete if you kill boss now!"
pseamimifailloc1			= "Bombot!"
pseamimifailloc2			= "Rocket strike!"
pseamimifailloc3			= "Mine!"
pseamimifailloc5			= "part is failed!"
pseatrebulda2				= "Kill last add and THEN kill boss!"
pseaulduartitle				= "    Ulduar"
whrabrann				= "Brann Bronzebeard"
whrabrannemo				= "you want to play hardball"
whrabrannemo2				= "safes deactivated. Beginning memory purge and"
whragundemo				= "gonna spill your guts"
whraaddkilled1				= "Add was killed!"
whraaddkilled2				= "will not be complete if you kill boss now!"
whratitle				= "    Wotlk Heroics"
ranotsure				= "NOT ACCURATELY!"
rayard					= "yd"
ramanyplayers				= "many players"
raragnaachtxt1				= "kill boss to get it!"
raragnaachtxt2				= "Requirements completed! You have %s sec to kill boss! Check timer in your BossMod."
radatabrokervart  = "Click = Show | Hide"
ramainbattleground  = "battleground"
ramainbattlegroundopt = "Show achieve list in battleground too (if it is enabled for raids)"

	raerroraddoninst  = "Error! Addon is not installed, you have to download and install it:"
raerrormodulereq  = "Additional module is required:"

pseaoldmodules  = "Old modules"
pseaoldmodules2 = "    Old modules"
psealeftmenupanda = "Panda Heroics"
psealeftmenupanda2  = "Panda Raids"
psealeftmenupanda3  = "Panda Scenarios"
phratitle				= "    Pandaria Heroics"
prratitle       = "    Pandaria Raids"
pzratitle       = "    Pandaria Scenarios"




racredits1				= "Credits"
racredits2				= "    Thanks for help!"
racredits3				= "Thanks to everyone who help to improve this addon!\n\n\n|cff00ff00Phoenix|r @ RU-Azuregos - guild where all began, without it addon wouldn't be created\n|cff00ff00Black Lotus|r @ RU-Gordunni - where all keeps on\n\n|cff00ff00Шурш (Shurshik)|r @ RU-Gordunni - addon author\n\nThanks for localization:\nGerman: |cff00ff00Domestica|r @ [EU] Baelgun\nSpanish: |cff00ff00Krovikan|r @ [EU] Minahonda\nSimplified Chinese: |cff00ff00ananhaid|r\nKorean: |cff00ff00antinobunno|r\n\nVisit http://wow.curseforge.com/addons/raidachievement/localization/\n\n\nSpecial Thanks to:\n|cff00ff00Бенефит (Benefit)|r @ RU-Drakonomor, |cff00ff00Дэи (Dei)|r @ RU-Azuregos, |cff00ff00Кайи (Kaii)|r @ RU-Azuregos, |cff00ff00Сильвин (Silwin)|r @ RU-Azuregos, |cff00ff00Львёнка (L'venka)|r @ RU-Gordunni\n\nAnd also everybody, who helped & keep hepling to improve addon, but didn`t get in this list. |CFFFFFF00Do you have interesting suggestions or want to help with localization?|r Write me on |cff00ff00www.phoenixstyle.com|r and we will discuss it together!\n\n\n\nGive a look to the addon's site: |cffff0000www.phoenixstyle.com|r I hope advertising will suit your interests ;)"


end





