if GetLocale() == "frFR" then

function psealocale()


	PSFeaserver = "ru-Gordunni"
	charakillintime = "Conditions requises complètes ! Tuez le boss avec 3 stacks de \"Charge de Foudre\" (30 sec restantes)!" -- Needs review
	charakillintime2 = "Conditions remplies! Tuez le boss quand il a le buff (20 sec restantes)"
	chhrbrannyell = "Bien, allons-y! Nous devons juste saisir la séquence finale dans le mécanisme de la porte... et..."
	chratitle = "    Héroïque Cataclysm"
	crraraidpartachloc1 = "Horion statique!"
	crraraidpartachloc2 = "Bombe de poison!"
	crraraidpartachloc3 = "Annihilateur arcanique!"
	crraraidpartachloc4 = "Lance-flammes!"
	crratitle = "    Raids de Cataclysm"
	icravalitriayell1 = "Vous y trouverez votre salut"
	icravalitriayell2 = "JE REVIS"
	nrallbuttonmaint = "Liste pour cette zone"
	nrallbuttontak = "Tactiques"
	-- nxraonyemote = ""
	nxraonyxiab = "Onyxia"
	psbuttonoff = "STOP"
	psbuttonon = "Début"
	pseaaddonmy = "AddOn"
	pseaaddonoff = "ARRÊT"
	pseaaddonok = "OK"
	pseaaddonon = "activer l'addon"
	pseaaddonon2 = "MARCHE"
	pseachangeall = "Changer"
	pseachatlist1 = "raid"
	pseachatlist2 = "avertissement de raid"
	pseachatlist3 = "officier"
	pseachatlist4 = "groupe"
	pseachatlist5 = "guilde"
	pseachatlist6 = "dire"
	pseachatlist7 = "crier"
	pseachatlist8 = "à soi-même"
	pseadisableall = "Désactiver tout"
	pseaenableall = "Activer tout"
	psealeftmenu1 = "AddOn"
	psealeftmenu11 = "Suivre après échec"
	psealeftmenu3 = "Naxxramas"
	psealeftmenu31 = "Naxxramas + autre mini raids WotLK"
	psealeftmenu4 = "Donjons WotLK"
	psealeftmenu5 = "Ulduar"
	psealeftmenu6 = "La Couronne de glace"
	psealeftmenucata = "Héroïque Cata"
	psealeftmenucata2 = "Raids Cata"
	pseamanyachtitle = "    Garder le suivi du haut fait après son échec"
	pseamoduleload = "Module chargé :"
	pseamodulenotload = "Erreur lors du chargement du module :"
	pseapartfailedloc = "une partie de ce haut fait a échoué!"
	pseapsaddonanet = "Erreur ! L'Addon PhoenixStyle n'est pas installé"
	pseapsaddonanet2 = "Vous pouvez le télécharger sur www.ps-addon.com"
	pseareports = "- canal de chat pour annoncer les avertissements"
	pseashownames = "montrer la raison (nom, etc.) de l'échec du haut fait"
	pseashowveren = "Montrer un message si une nouvelle version de l'addon est détectée dans votre guilde/groupe"
	pseasoundoptions1 = "Joue un son lors de l'échec du haut fait"
	pseasoundoptions2 = "Joue un son quand les conditions sont remplies"
	pseasoundoptions3 = "Joue un son seulement si j'ai besoin de ce haut fait"
	pseasoundoptions6 = "Mode principal, joue un son quand le son du jeu est désactivé" -- Needs review
	pseatreb2 = "Pré-requis complété(s) ! Tuer le boss maintenant !"
	pseatreb4 = "échec !"
	pseatrebulda2 = "Tuez le dernier add et ENSUITE tuez le boss !"
	pseauierror = "    Erreur !"
	pseauierroraddonoff = "Erreur ! L'addon est désactivé - Ce module n'est pas disponible !"
	pseauinomodule1 = "    Erreur ! Le module n'est pas installé !"
	pseauinomodule2 = "Erreur ! Le module choisi n'est pas installé !\r\nDownload it from http://phoenixstyle.com or curse.com"
	psmoduletxtoff = "le module est désactivé"
	psmoduletxton = "le module est activé"
	psoldvertxt = "(ancienne version)"
	raiccof = "de"
	raiccused = "utilisé"
	ramaintrackingtitle = "Recherche"
	ramanyachtitinfo = "Lorsque vous échouez un haut fait son suivi est bloqué jusqu'à la fin du combat. Ce module réinitialise le blocage. Le réinitialisation se produit dans "
	ramanyachtitinfo2 = "après un « message d'échec ». Définir le temps de réinitialisation nécessaire pour un combat et cliquez sur le module « Début ». Ce module est auto-désactivé après déconnexion." -- Needs review
	ramanyachtitinfoq = "Le blocage du suivi de haut fait sera réinitialisé" -- Needs review
	ramanyachtitinfoq2 = "temps pour le combat. Changement :"
	raminibuttset = "Montre le bouton de la mini-carte"
	ramodulnotblock = "le suivi ne sera pas bloqué"
	ranewversfound = "|cff00ff00Attention!|r Une nouvelle de l'Addon |cff00ff00'RaidAchievement'|r a été trouvé dans votre groupe/guilde, il est recommandé de le mettre à jour via www.ps-addon.com"
	-- ranotsure = ""
	rasec = "sec."
	ravalitnottrack = "ne sera pas suivi en héroïque par l'addon"
	ut_3 = "Options principales"
	whraaddkilled1 = "L'add a été tué !"
	whraaddkilled2 = "ne sera pas completé si vous tuez boss maintenant !"
	whrabrann = "Brann Barbe-de-bronze"
	-- whrabrannemo = ""
	-- whrabrannemo2 = ""
	whragundemo = "allant répandre vos tripes" -- Needs review



end

end