if GetLocale() == "ruRU" then


function psealocale()


pseachatlist1				= "рейд"
pseachatlist2				= "объявление рейду"
pseachatlist3				= "офицер"
pseachatlist4				= "группа"
pseachatlist5				= "гильдия"
pseachatlist6				= "сказать"
pseachatlist7				= "крикнуть"
pseachatlist8				= "только себе"
pseaaddonmy				= "Аддон"
pseaaddonon2				= "включен"
pseaaddonoff				= "отключен"
pseamoduleload				= "Загружен модуль"
pseamodulenotload			= "Не удалось загрузить модуль"
pseaaddonon				= "Включить аддон"
pseaaddonok				= "OK"
pseatreb2				= "требования выполнены! Теперь убейте босса!"
pseatreb4				= "провалено!"
ranewversfound				= "|cff00ff00Внимание!|r Доступна более новая версия, рекомендуется скачать обновление с http://phoenixstyle.com"
nrallbuttonmaint			= "Список по локации"
pseapartfailedloc			= "часть провалена!"
ramaintrackingtitle			= "Отслеживание"
racolorcomb           = "ОСТАЛАСЬ 1 комбинация"
racolor5               = "зеленый"
racolor1               = "красный"
racolor2               = "черный"
racolor3               = "желтый"
racolor6               = "фиолетовый"
radeathwingemote1			= " наклоняется влево!"
radeathwingemote2			= " наклоняется вправо!"
raspectext            = "Слишком большая зона боя. Требуется установить аддон всем!"


psealeftmenu1				= "Аддон"
psealeftmenu3				= "Наксрамас"
psealeftmenu31				= "Наксрамас + остальные мини рейды WotLK"
psealeftmenu4				= "Wotlk Подземелья"
psealeftmenu5				= "Ульдуар"
psealeftmenu6				= "Цитадель"
pseareports				= "- канал для отправки сообщений"
PSFeaserver				= "ru-Гордунни"
pseauinomodule1				= "    Ошибка! Модуль не установлен!"
pseauinomodule2				= "Произошла ошибка! Выбранный Вами модуль не установлен!"
pseauierror				= "    Ошибка!"
pseauierroraddonoff			= "Ошибка! Аддон отключен - данный модуль не доступен!"
pseapsaddonanet				= "Ошибка! Аддон PhoenixStyle не установлен"
pseapsaddonanet2			= "Вы можете скачать его с сайта www.phoenixstyle.com"
pseaenableall				= "Включить все"
pseadisableall				= "Отключить все"
pseachangeall				= "Переключить"
pseashownames				= "Отображать причину провала достижений (имена, и тп)"
pseashowveren				= "Отображать сообщ. при обнаружении более новой версии аддона в гильдии/группе"
psealeftmenu11				= "Многократный анонс"
pseamanyachtitle			= "    Многократная проверка достижений"
ramanyachtitinfo			= "При провале достижения его отслеживание прекращается до конца боя. Данный модуль позволяет следить за дальнейшими провалами уже проваленного достижения. Обнуление таймера слежения происходит через "
ramanyachtitinfo2			= "после сообщения о провале. На этой странице вы можете включить модуль и здесь же установить количество обнулений за один бой. Данный модуль отключится при выходе из игры."
psbuttonon				= "Включить"
psbuttonoff				= "Отключить"
psmoduletxton				= "модуль включен"
psmoduletxtoff				= "модуль отключен"
rasec					= "сек."
ramanyachtitinfoq			= "Таймер слежения после провала достижения будет обнуляться "
ramanyachtitinfoq2			= "раз(а) за бой. Изменить:"
ramodulnotblock				= "проверка не блокируется"
psoldvertxt				= "(устаревшая)"
raminibuttset				= "Отображать кнопку на мини-карте"
nrallbuttontak				= "Тактики"
psealeftmenucata			= "Героики Катаклизма"
psealeftmenucata2			= "Рейды Катаклизма"
pseasoundoptions1			= "Звук при провале достижения"
pseasoundoptions2			= "Звук при выполнении критерий достижения"
pseasoundoptions3			= "Проигрывать только, если достижение не выполненное мною"
pseasoundoptions6			= "Master режим, проигрывать звуки даже с отключенным звуком в клиенте"

nxratitle				= "    Наксрамас + остальные мини рейды WotLK"
nxraonyxiab				= "Ониксия"
nxraonyemote				= "делает глубокий вдох"
icravalitriayell1			= "Я открыла портал в Изумрудный Сон. Там вы найдете спасение, герои..."
icravalitriayell2			= "Я ИЗЛЕЧИЛАСЬ! Изера, даруй мне силу покончить с этими нечестивыми тварями."
icratitle				= "    Цитадель Ледяной Короны"
raiccof					= "из"
raiccused				= "использовано"
ravalitnottrack				= "- не отслеживается аддоном в героическом режиме из-за отсутствия эмоций босса в чате"
crratitle				= "    Рейды Катаклизма"
crraraidpartachloc1			= "Статический шок!"
crraraidpartachloc2			= "Ядовитая бомба!"
crraraidpartachloc3			= "Волшебный уничтожитель!"
crraraidpartachloc4			= "Огнемет!"
chratitle				= "    Героические подземелья Катаклизма"
charakillintime				= "Требования выполнены! Осталось: 30 сек (пока на вас 3 стака баффа)!"
charakillintime2			= "Требования выполнены! Осталось: 20 сек (пока на боссе бафф)!"
chhrbrannyell				= "Ага, ну поехали! Осталось ввести последний код для открывания двери...и..."
pseaulduarkolf1				= "Адд убит!"
pseaulduarkolf2				= "не будет выполнено, если убьете босса!"
pseamimifailloc1			= "Бомбот!"
pseamimifailloc2			= "Ракетный залп!"
pseamimifailloc3			= "Мина!"
pseamimifailloc5			= "часть провалена!"
pseatrebulda2				= "Остался последний адд! ПОТОМ убейте босса!"
pseaulduartitle				= "    Ульдуар"
whrabrann				= "Бранн Бронзобород"
whrabrannemo				= "значит, играем по"
whrabrannemo2				= "меры предосторожности деактивированы"
whragundemo				= "Я вытащу ваши кишки, твари"
whraaddkilled1				= "Адд убит!"
whraaddkilled2				= "не будет выполнено, если убьете босса!"
whratitle				= "    Wotlk Подземелья"
ranotsure				= "НЕ ТОЧНО"
rayard					= "м"
ramanyplayers				= "много игроков"
raragnaachtxt1				= "убейте босса вовремя!"
raragnaachtxt2				= "Требования выполнены! Осталось: %s сек. Таймер в вашем БоссМоде."
radatabrokervart  = "Открыть | Закрыть"
ramainbattleground  = "поле боя"
ramainbattlegroundopt = "Отображать список достижений при входе на Поле Боя (если вкл отображение для рейдов)"

raerroraddoninst  = "Ошибка! Аддон не установлен. Вам необходимо скачать и установить:"
raerrormodulereq  = "Требуется дополнительный аддон:"

pseaoldmodules  = "Старые модули"
pseaoldmodules2 = "    Старые модули"
psealeftmenupanda = "Героики Пандарии"
psealeftmenupanda2  = "Рейды Пандарии"
psealeftmenupanda3  = "Сценарии Пандарии"
phratitle				= "    Героики Пандарии"
prratitle       = "    Рейды Пандарии"
pzratitle       = "    Сценарии Пандарии"



racredits1				= "Благодарности"
racredits2				= "    Спасибо за помощь!"
racredits3				= "Выражаем благодарность всем, кто помогает делать аддон лучше!\n\nОсобенно хотелось бы отметить:\n|cff00ff00Феникс|r @ Азурегос - гильдия, где всё начиналось, без неё аддон бы не появился\n|cff00ff00Чёрный лотос|r @ Гордунни - где все продолжается\n\n|cff00ff00Шурш|r @ Гордунни - автор аддона\n\nСпасибо за локализацию:\nGerman: |cff00ff00Domestica|r @ [EU] Baelgun\nSimplified Chinese: |cff00ff00ananhaid|r\n\nПосетите сайт, чтобы помочь: http://wow.curseforge.com/addons/raidachievement/localization/\n\n\nОсобенная благодарность за постоянную помощь в тестировании, решение проблем и обсуждении идей:\n|cff00ff00Бенефит|r @ Дракономор, |cff00ff00Дэи|r @ Свежеватель душ, |cff00ff00Кайи|r @ Азурегос, |cff00ff00Сильвин|r @ Азурегос, |cff00ff00Львёнка|r @ Гордунни\n\nА так же всем всем всем, кто помогал и помогает улучшать аддон, но не попал в этот список. |CFFFFFF00У вас есть интересные идеи, хотите помочь с локализацией?|r Пишите мне на |cff00ff00www.phoenixstyle.com|r и вместе обсудим ваши предложения!\n\n\n\nПосетите наш сайт: |cffff0000www.phoenixstyle.com|r надеюсь реклама спонсоров подойдет под ваши интересы и вы найдете там много интересного ;)"


end





end