if GetLocale() == "zhCN" then


function psealocale()


	pseachatlistldb1			= "团队成就助手"
	pseachatlistldb2			= "点击 = 显示 | 隐藏 GUI设置"
	charakillintime = "条件达成！杀死堆叠有3层闪电充能的首领（30秒剩余时间）！"
	charakillintime2 = "条件达成！当他有此增益效果时击杀首领（20秒剩余时间）！"
	chhrbrannyell = "好啊，我们走！只需要在门禁系统中输入最终登录序列……然后……"
	chratitle = "    大地的裂变英雄"
	crraraidpartachloc1 = "静电震击！"
	crraraidpartachloc2 = "毒液炸弹！"
	crraraidpartachloc3 = "奥术歼灭者！"
	crraraidpartachloc4 = "火焰喷射器！"
	crratitle = "    大地的裂变团队"
	icratitle = "    冰冠堡垒"
	icravalitriayell1 = "我打开了进入梦境的传送门。英雄们，救赎就在其中……"
	icravalitriayell2 = "我获得了新生！伊瑟拉的恩泽赐予我消灭邪恶的力量！"
	nrallbuttonmaint = "区域列表"
	nrallbuttontak = "战术"
	nxraonyemote = "深深地吸了一口气"
	nxraonyxiab = "奥妮克希亚"
	nxratitle = "    纳克萨玛斯和其他巫妖王之怒团队"
	phratitle = "    熊猫人之谜英雄"
	prratitle = "    熊猫人之谜团队"
	psbuttonoff = "停止"
	psbuttonon = "开始"
	pseaaddonmy = "插件"
	pseaaddonoff = "关闭"
	pseaaddonok = "确定"
	pseaaddonon = "启用插件"
	pseaaddonon2 = "开启"
	pseachangeall = "反向选择"
	pseachatlist1 = "团队"
	pseachatlist2 = "团队通知"
	pseachatlist3 = "官员"
	pseachatlist4 = "队伍"
	pseachatlist5 = "公会"
	pseachatlist6 = "说"
	pseachatlist7 = "大喊"
	pseachatlist8 = "仅自己"
	pseadisableall = "全部禁用"
	pseaenableall = "全部启用"
	psealeftmenu1 = "插件"
	psealeftmenu11 = "失败后追踪"
	psealeftmenu3 = "纳克萨玛斯"
	psealeftmenu31 = "纳克萨玛斯 + 其他巫妖王团队"
	psealeftmenu4 = "巫妖王之怒地下城"
	psealeftmenu5 = "奥杜尔"
	psealeftmenu6 = "冰冠堡垒"
	psealeftmenucata = "大地的裂变英雄"
	psealeftmenucata2 = "大地的裂变团队"
	psealeftmenupanda = "熊猫人之谜英雄"
	psealeftmenupanda2 = "熊猫人之谜团队"
	psealeftmenupanda3 = "熊猫人之谜场景战役"
	pseamanyachtitle = "    失败后继续追踪成就"
	pseamimifailloc1 = "炸弹机器人！"
	pseamimifailloc2 = "火箭打击！"
	pseamimifailloc3 = "感应地雷！"
	pseamimifailloc5 = "部分已失败！"
	pseamoduleload = "已加载的模块："
	pseamodulenotload = "加载错误的模块："
	pseaoldmodules = "旧模块"
	pseaoldmodules2 = "    旧模块"
	pseapartfailedloc = "部分已失败！"
	pseapsaddonanet = "错误！未安装 PhoenixStyle 插件"
	pseapsaddonanet2 = "你可以从www.phoenixstyle.com下载它"
	pseareports = "- 在此频道中公布警报"
	pseashownames = "显示成就失败的原因（名字等）"
	pseashowveren = "如果在你的公会/队伍中检测到新版本的插件那么显示其更新信息"
	pseasoundoptions1 = "成就失败时播放的音效"
	pseasoundoptions2 = "成就条件达成时播放的音效"
	pseasoundoptions3 = "只对需要的这些成就播放音效"
	pseasoundoptions6 = "主控模式，在播放音效时游戏中的声音被禁用"
	pseatreb2 = "条件已达成！现在可以击杀首领！"
	pseatreb4 = "失败！"
	pseatrebulda2 = "击杀最后一个小怪并在之后杀死首领！"
	pseauierror = "    错误！"
	pseauierroraddonoff = "错误！插件被禁用 - 这个模块无法使用！"
	pseauinomodule1 = "    错误！模块未安装！"
	pseauinomodule2 = "错误！所选模块未安装！"
	pseaulduarkolf1 = "怪物已被击杀！"
	pseaulduarkolf2 = "成就将因首领被击杀而无法达成！"
	pseaulduartitle = "    奥杜尔"
	PSFeaserver = "RU-Gordunni（汉化：CN--斯坦索姆-Adavak）"
	psmoduletxtoff = "模块被禁用"
	psmoduletxton = "模块已启用"
	psoldvertxt = "（旧版本）"
	pzratitle = "    熊猫人之谜场景战役"
	racolor1 = "红色"
	racolor2 = "黑色"
	racolor3 = "黄色"
	racolor5 = "绿色"
	racolor6 = "紫色"
	racolorcomb = "剩余一种组合"
	racredits1 = "致谢"
	racredits2 = "    感谢您的帮助！"
	radatabrokervart = "点击 = 显示|隐藏"
	radeathwingemote1 = "向左翻滚！"
	radeathwingemote2 = "向右翻滚！"
	raiccof = "的"
	raiccused = "已使用"
	ramainbattleground = "战场"
	ramainbattlegroundopt = "在战场的入口显示成就列表（如果它为团队时启用）"
	ramaintrackingtitle = "追踪中"
	ramanyachtitinfo = "当你的一个成就失败它的追踪将会被阻止直到战斗结束。这个模块将重置被阻止的追踪。会在'失败消息'的"
	ramanyachtitinfo2 = "后重置。设置一场战斗中应该完成多少次重置并点击'开始'模块。这个模块在登出后自动禁用。"
	ramanyachtitinfoq = "将会重置阻止追踪成就"
	ramanyachtitinfoq2 = "次于战斗中。更改："
	ramanyplayers = "许多玩家"
	raminibuttset = "显示小地图按钮"
	ramodulnotblock = "追踪将不会被阻止"
	ranewversfound = "|cff00ff00注意|r新版本被发现，推荐你到http://phoenixstyle.com更新它"
	ranotsure = "不准确"
	raragnaachtxt1 = "击败首领来获得它！"
	raragnaachtxt2 = "成就条件达成！你有%s秒来击败首领！检查你首领模块的计时器。"
	rasec = "秒"
	ravalitnottrack = "插件不会在英雄模式中追踪"
	rayard = "码"
	whraaddkilled1 = "怪物已被击杀！"
	whraaddkilled2 = "如果你现在杀死首领将无法完成成就！"
	whrabrann = "布莱恩·铜须"
	whrabrannemo = "你想跟我来硬的？"
	whrabrannemo2 = "安全系统自动修复装置已被关闭。立刻消除化全部存储器内容并……"
	whragundemo = "我要把你碎尸万断"
	whratitle = "    巫妖王之怒英雄"
	raspectext  = "过大的战斗区域. 在团队中需要更多的插件!"
	raerroraddoninst = "出错! 插件没有被安装,你必须下载并安装它:"
	raerrormodulereq = "需要额外的模块"

racredits1				= "致谢"
racredits2				= "    感谢您的帮助！"
racredits3				= "感谢所有帮助插件改善这个插件的人！\n\n\n|cff00ff00Phoenix|r @ RU-Azuregos - 公会是一切的开始，没有他们插件不会被开发。\n|cff00ff00Black Lotus|r @ RU-Gordunni - 一直保持着更新\n\n|cff00ff00Шурш (Shurshik)|r @ RU-Gordunni - 插件作者\n\n感谢本地化：\n德文：|cff00ff00Domestica|r @ [EU] Baelgun\n简体中文：|cff00ff00ananhaid|r，|cff00ff00fanjunyi|r\n\n访问 http://wow.curseforge.com/addons/raidachievement/localization/\n\n\n特别感谢：\n|cff00ff00Бенефит (Benefit)|r @ RU-Drakonomor，|cff00ff00Дэи (Dei)|r @ RU-Azuregos，|cff00ff00Кайи (Kaii)|r @ RU-Azuregos，|cff00ff00Сильвин (Silwin)|r @ RU-Azuregos，|cff00ff00Львёнка (L'venka)|r @ RU-Gordunni\n\n也同样感谢所有不断帮助改善插件，却不在这个名单中的人。|CFFFFFF00你有有趣的建议或者想帮助本地化？|r 在|cff00ff00www.phoenixstyle.com|r写消息给我，我们将一起研究讨论！\n\n\n\n赞助者：\n暂时没有\n\n给你看我的插件网站|cffff0000www.phoenixstyle.com|r我希望有你感兴趣的广告。"




end


end