if GetLocale() == "koKR" then


function psealocale()

pseachatlist1				= "공격대"
pseachatlist2				= "공격대 경보"
pseachatlist3				= "길드관리자"
pseachatlist4				= "파티"
pseachatlist5				= "길드"
pseachatlist6				= "대화"
pseachatlist7				= "외침"
pseachatlist8				= "자신에게만"
pseaaddonmy				= "애드온"
pseaaddonon2				= "켜기"
pseaaddonoff				= "끄기"
pseamoduleload				= "모듈 불러오기:"
pseamodulenotload			= "모듈 불러오기 실패:"
pseaaddonon				= "애드온 켜기"
pseaaddonok				= "확인"
pseatreb2				= "요구조건 완료! 보스를 잡으세요!"
pseatreb4				= "실패!"
ranewversfound				= "|cff00ff00주의!|r 새로운 버전을 찾았습니다, http://phoenixstyle.com에서 업데이트 할수있습니다"
nrallbuttonmaint			= "지역 목록"
pseapartfailedloc			= "부분 실패!"
ramaintrackingtitle			= "추적중"
racolorcomb           = "LEFT ONE combination"
racolor5               = "녹색"
racolor1               = "빨강"
racolor2               = "검정"
racolor3               = "노랑"
racolor6               = "보라"
radeathwingemote1			= "왼쪽으로 굴려!"
radeathwingemote2			= "오른쪽으로 굴려!"


psealeftmenu1				= "애드온"
psealeftmenu3				= "낙스라마스"
psealeftmenu31				= "낙스라마스 + 그밖에 리치왕의 분노 공격대"
psealeftmenu4				= "리치왕의 분노 던전"
psealeftmenu5				= "울두아르"
psealeftmenu6				= "얼음왕관"
pseareports				= "경보를 알릴 채널"
pseauinomodule1				= "에러! 모듈이 설치되어있지 않습니다"
pseauinomodule2				= "에러! 선택된 모듈이 설치되어있지 않습니다\r\nDownload it from http://phoenixstyle.com or curse.com"
pseauierror				= "에러!"
pseauierroraddonoff			= "에러! 애드온이 꺼져있습니다. -  모듈이 사용불가합니다"
pseapsaddonanet				= "에러! PhoenixStyle 애드온이 설치되어있지 않습니다."
pseapsaddonanet2			= "당신은 www.phoenixstyle.com에서 다운로드받을수 있습니다"
pseaenableall				= "모두 켜기"
pseadisableall				= "모두 끄기"
pseachangeall				= "전환"
pseashownames				= "업적에 실패한 이유를 보여줍니다(캐릭명, 기타)"

pseashowveren				= "길드/파티에서 감지된 새로운 애드온 버전에 대한 메세지를 보여줍니다."
psealeftmenu11				= "실패 후 추적"
pseamanyachtitle			= "실패후에도 업적 추적을 유지합니다."

ramanyachtitinfo			= "당신이 업적에 실패할 때 싸움이 끝날 때까지 그 추적은 막힙니다. 이 모듈은 블로킹을 재설정합니다. 리셋은 안에서 발생합니다"
ramanyachtitinfo2			= "'실패 메시지' 후에. 싸움을 위한 많은 리셋이 수행되어야 하고 '출발' 모듈을 클릭해야 하는 방법을 설정합니다. 이 모듈은 로그 아웃 후의 자동 비활성화됩니다."

psbuttonon				= "시작"
psbuttonoff				= "정지"
psmoduletxton				= "모듈을 사용합니다."
psmoduletxtoff				= "모듈을 사용하지 않습니다"
rasec					= "초."
ramanyachtitinfoq			= "업적 추적을 막는 것은 재설정될 것입니다"
ramanyachtitinfoq2			= "전투의 시간. 변화:"
ramodulnotblock				= "추적은 막히지 않을 것입니다"
psoldvertxt				= "(오래된 버전)"
raminibuttset				= "미니맵 버튼을 표시"
nrallbuttontak				= "기능"
psealeftmenucata			= "대격변 영웅 던전"
psealeftmenucata2			= "대격변 공격대"
pseasoundoptions1			= "업적 실패 시 소리를 재생합니다"
pseasoundoptions2			= "업적 완료 시 소리를 재생합니다"
pseasoundoptions3			= "업적이 필요할때만 소리를 재생합니다"
pseasoundoptions6			= "관리자모드, 게임내 소리가 꺼져있을대 소리를 재생합니다."


nxraonyxiab				= "오닉시아"
nxraonyemote				= "숨을 깊게 들이쉽니다"
nxraonyemote22          = "깊은 숨을 쉽니다"
nxratitle				= "낙스라마스 + 그밖에 리치왕 공격대"
icravalitriayell1			= "I have opened a portal into the Dream. Your salvation lies within, heroes..."
icravalitriayell2			= "I AM RENEWED! Ysera grant me the favor to lay these foul creatures to rest!"
icratitle				= "얼음왕관"
raiccof					= "of"
raiccused				= "used"
ravalitnottrack				= "영웅던전은 추적하지 않습니다."
crratitle				= "대격변 공격대"
crraraidpartachloc1			= "Static Shock!"
crraraidpartachloc2			= "Poison Bomb!"
crraraidpartachloc3			= "Arcane Annihilator!"
crraraidpartachloc4			= "Flamethrower!"
chratitle				= "대격변 영웅"
charakillintime				= "요구사항 완료! Kill boss with 3 stacks of Lightning Charge (30 초 남음)!"
charakillintime2			= "요구사항 완료! Kill boss when he has buff (20 초 남음)!"
chhrbrannyell				= "Right, let's go! Just need to input the final entry sequence into the door mechanism... and..."
pseaulduarkolf1				= "Add was killed!"
pseaulduarkolf2				= "지금 보스를 잡으면 완료되지 않을겁니다"
pseamimifailloc1			= "Bombot!"
pseamimifailloc2			= "Rocket strike!"
pseamimifailloc3			= "지뢰!"
pseamimifailloc5			= "부분 실패!"
pseatrebulda2				= "Kill last add and THEN kill boss!"
pseaulduartitle				= "울두아르"
whrabrann				= "Brann Bronzebeard"
whrabrannemo				= "you want to play hardball"
whrabrannemo2				= "safes deactivated. Beginning memory purge and"
whragundemo				= "gonna spill your guts"
whraaddkilled1				= "Add was killed!"
whraaddkilled2				= "will not be complete if you kill boss now!"
whratitle				= "리치왕의 분노 영웅"
ranotsure				= "NOT ACCURATELY!"
rayard					= "미터"
ramanyplayers				= "여러 플레이어"
raragnaachtxt1				= "kill boss to get it!"
raragnaachtxt2				= "요구조건 완료! 보스를 %s초 안에 잡아야 합니다. 보스경보를 확인하세요"
radatabrokervart  = "클릭 = 보기 | 감추기"
ramainbattleground  = "전장"
ramainbattlegroundopt = "전장에서 너무 많은 업적도 표시합니다.(레이드에서는 작동하지 않습니다)"


pseaoldmodules  = "오래된 모듈"
pseaoldmodules2 = "오래된 모듈"
psealeftmenupanda = "판다리아 영웅"
psealeftmenupanda2  = "판다리아 공격대"
psealeftmenupanda3  = "판다리아 시나리오"
phratitle				= "판다리아 영웅"
prratitle       = "판다리아 공격대"
pzratitle       = "판다리아 시나리오"




racredits1				= "크레딧"
racredits2				= "도와주신분들에게 감사합니다!"
racredits3				= "Thanks to everyone who help to improve this addon!\n\n\n|cff00ff00Phoenix|r @ RU-Azuregos - guild where all began, without it addon wouldn't be created\n|cff00ff00Black Lotus|r @ RU-Gordunni - where all keeps on\n\n|cff00ff00Шурш (Shurshik)|r @ RU-Gordunni - addon author\n\nThanks for localization:\nGerman: |cff00ff00Domestica|r @ [EU] Baelgun\nSimplified Chinese: |cff00ff00ananhaid|r\n\nVisit http://wow.curseforge.com/addons/raidachievement/localization/\n\n\nSpecial Thanks to:\n|cff00ff00Бенефит (Benefit)|r @ RU-Drakonomor, |cff00ff00Дэи (Dei)|r @ RU-Azuregos, |cff00ff00Кайи (Kaii)|r @ RU-Azuregos, |cff00ff00Сильвин (Silwin)|r @ RU-Azuregos, |cff00ff00Львёнка (L'venka)|r @ RU-Gordunni\n\nAnd also everybody, who helped & keep hepling to improve addon, but didn`t get in this list. |CFFFFFF00Do you have interesting suggestions or want to help with localization?|r Write me on |cff00ff00www.phoenixstyle.com|r and we will discuss it together!\n\n\n\nDonators:\nnoone for the moment\nGive a look to the addon's site: |cffff0000www.phoenixstyle.com|r I hope advertising will suit your interests ;)"


end

end