--[[ Credit for these translations goes to:
	sunyruru
--]]
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "koKR", false)
if not L then return end


L["ACTIVE"] = "%d 활성" -- Needs review
L["AIR"] = "바람" -- Needs review
L["ALLOWCOMM"] = "아이콘 들여오기 허용" -- Needs review
L["ANN_CHANTOUSE"] = "사용할 채널" -- Needs review
L["ANN_SHOWICON"] = "아이콘 텍스쳐 보이기" -- Needs review
L["ANN_TAB"] = "문자 출력" -- Needs review
L["ANN_WHISPERTARGET"] = "귓속말 대상" -- Needs review
L["ASCENDING"] = "오름" -- Needs review
L["ASPECT"] = "상" -- Needs review
L["AURA"] = "오라" -- Needs review
L["Bleeding"] = "출혈" -- Needs review
L["BonusStamina"] = "체력 증가" -- Needs review
L["BOTTOM"] = "하단" -- Needs review
L["BOTTOMLEFT"] = "좌측 하단" -- Needs review
L["BOTTOMRIGHT"] = "우측 하단" -- Needs review
L["BUFFTOCHECK"] = "체크할 강화 효과" -- Needs review
L["BUFFTOCOMP1"] = "비교할 첫번째 강화 효과 " -- Needs review
L["BUFFTOCOMP2"] = "비교할 두번째 강화 효과 " -- Needs review
L["BurstManaRegen"] = "마나 회복 충만" -- Needs review
L["CACHINGSPEED"] = "프레임당 주문:" -- Needs review
L["CASTERFORM"] = "인간형" -- Needs review
L["CENTER"] = "정중앙" -- Needs review
L["CHAT_FRAME"] = "대화 프레임" -- Needs review
L["CHAT_MSG_CHANNEL"] = "대화 채널" -- Needs review
L["CHAT_MSG_CHANNEL_DESC"] = "거래 또는 현재 연결 중인 사용자 채널과 같은 대화 채널로 출력하게 됩니다." -- Needs review
L["CHECKORDER"] = "순서 갱신" -- Needs review
L["CHOOSENAME_DIALOG"] = [=[이 아이콘에 관찰하고자 하는 이름 또는 ID를 입력하십시오. 세미콜론(;)로 항목을 구분짓는 것을 통해 여러 개의 항목을 추가할 수 있습니다.

주문/아이템/대화창 링크를 |cff7fffffShift-click|r 하시거나 주문/아이템을 드래그 하셔서 이 편집박스에 넣을 수 있습니다.]=]
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "미리 정의된 주문 세트/해재 유형" -- Needs review
L["CHOOSENAME_DIALOG_PETABILITIES"] = "|cFFFF5959소환수 능력|r은 주문ID를 사용해야 합니다." -- Needs review
L["CLEU_CAT_AURA"] = "버프/디버프" -- Needs review
L["CMD_OPTIONS"] = "옵션"
L["CNDTCAT_BUFFSDEBUFFS"] = "강화 효과/약화 효과" -- Needs review
L["CNDTCAT_FREQUENTLYUSED"] = "지속적으로 사용" -- Needs review
L["CNDTCAT_RESOURCES"] = "출처" -- Needs review
L["CNDTCAT_SPELLSABILITIES"] = "주문/아이템" -- Needs review
L["CNDTCAT_STATS"] = "전투 상태" -- Needs review
L["CODETOEXE"] = "실행할 코드" -- Needs review
L["COMPARISON"] = "비교" -- Needs review
L["CONDITIONPANEL_ADD"] = "조건 추가" -- Needs review
L["CONDITIONPANEL_ALIVE"] = "Unit is Alive" -- Needs review
L["CONDITIONPANEL_ALIVE_DESC"] = "조건은 만일 지정된 유닛이 살아 있으면 통과됩니다." -- Needs review
L["CONDITIONPANEL_AND"] = "과(와)"
L["CONDITIONPANEL_ANDOR"] = "과(와)/또는"
L["CONDITIONPANEL_AUTOCAST"] = "주문 자동시전" -- Needs review
L["CONDITIONPANEL_CASTTOMATCH"] = "일치하는 주문" -- Needs review
L["CONDITIONPANEL_CASTTOMATCH_DESC"] = "주문 시전이 정확하게 일치한 경우에만 조건이 통과되도록 하려면 여기에 주문의 이름을 입력하십시오." -- Needs review
L["CONDITIONPANEL_CLASS"] = "유닛 직업" -- Needs review
L["CONDITIONPANEL_CLASSIFICATION"] = "유닛 분류" -- Needs review
L["CONDITIONPANEL_COMBAT"] = "Unit in Combat(전투 중 유닛)" -- Needs review
L["CONDITIONPANEL_COMBO"] = "연계 점수" -- Needs review
L["CONDITIONPANEL_DEFAULT"] = "유형 선택..." -- Needs review
L["CONDITIONPANEL_ECLIPSE_DESC"] = "식은 -100(월식)에서 100(일식)의 범위를 갖고 있습니다. 80의 월력의 값으로 작동하는 아이콘을 원한다면 -80을 입력하십시오." -- Needs review
L["CONDITIONPANEL_EQUALS"] = "같음"
L["CONDITIONPANEL_EXISTS"] = "Unit Exists" -- Needs review
L["CONDITIONPANEL_GREATER"] = "보다 큼"
L["CONDITIONPANEL_GREATEREQUAL"] = "보다 크거나/같음"
L["CONDITIONPANEL_GROUPTYPE"] = "그룹 유형" -- Needs review
L["CONDITIONPANEL_ICON"] = "아이콘 보여지기" -- Needs review
L["CONDITIONPANEL_ICON_DESC"] = "조건은 아이콘이 현재 0 이상의 투명도로 보여지도록 지정한다면 통과되거나, false(거짓)로 설정한다면 0의 투명도로 숨겨지게 됩니다. " -- Needs review
L["CONDITIONPANEL_INSTANCETYPE"] = "인던 유형" -- Needs review
L["CONDITIONPANEL_INTERRUPTIBLE"] = "차단 가능" -- Needs review
L["CONDITIONPANEL_ITEMRANGE"] = "유닛의 사정 거리내 아이템" -- Needs review
L["CONDITIONPANEL_LESS"] = "보다 작음"
L["CONDITIONPANEL_LESSEQUAL"] = "보다 작거나/같음"
L["CONDITIONPANEL_LEVEL"] = "유닛 레벨" -- Needs review
L["CONDITIONPANEL_MANAUSABLE"] = "사용 가능 주문(마나/기력/기타)" -- Needs review
L["CONDITIONPANEL_NAME"] = "유닛 이름" -- Needs review
L["CONDITIONPANEL_NAMETOMATCH"] = "일치하는 이름" -- Needs review
L["CONDITIONPANEL_NOTEQUAL"] = "같지 않음"
L["CONDITIONPANEL_OPERATOR"] = "연산자" -- Needs review
L["CONDITIONPANEL_OR"] = "또는"
L["CONDITIONPANEL_PETMODE"] = "소환수 공격 모드" -- Needs review
L["CONDITIONPANEL_PETTREE"] = "소환수 특성 트리" -- Needs review
L["CONDITIONPANEL_POWER"] = "주 자원"
L["CONDITIONPANEL_POWER_DESC"] = "유닛이 표범 변신 중인 드루이드라면 기력에, 유닛이 전사 또는 그외라면 분노에 체크하면 됩니다." -- Needs review
L["CONDITIONPANEL_RAIDICON"] = "유닛 공격대 아이콘" -- Needs review
L["CONDITIONPANEL_REMOVE"] = "이 조건 제거" -- Needs review
L["CONDITIONPANEL_RESTING"] = "휴식" -- Needs review
L["CONDITIONPANEL_ROLE"] = "유닛 역활" -- Needs review
L["CONDITIONPANEL_SPELLRANGE"] = "유닛의 사정 거리내 주문" -- Needs review
L["CONDITIONPANEL_SWIMMING"] = "수영" -- Needs review
L["CONDITIONPANEL_TRACKING"] = "추적 활성" -- Needs review
L["CONDITIONPANEL_TYPE"] = "유형"
L["CONDITIONPANEL_UNIT"] = "유닛" -- Needs review
L["CONDITIONPANEL_UNITISUNIT"] = "Unit is Unit(유닛이 유닛)" -- Needs review
L["CONDITIONPANEL_UNITISUNIT_DESC"] = "이 조건은 유닛이 첫번째 편집 박스에 들어 있고 두번째 편집 박스에도 동일하게 들어 있다면 통과됩니다. " -- Needs review
L["CONDITIONPANEL_UNITISUNIT_EBDESC"] = "이 편집 박스에 첫번째 유닛과 비교할 유닛을 입력합니다." -- Needs review
L["CONDITIONPANEL_VALUEN"] = "값" -- Needs review
L["CONDITIONS"] = "조건" -- Needs review
L["CONDITION_TIMERS_HEADER"] = "타이머" -- Needs review
L["CONFIGMODE"] = "TellMeWhen이 설정 모드 상태입니다. 설정 모드를 빠져 나가기 까지 아이콘은 기능하지 않습니다. 설정 모드 켜기와 끄기를 전환하려면 '/tmw'를 입력하십시오. " -- Needs review
L["CONFIGMODE_EXIT"] = "설정 모드 나가기" -- Needs review
L["CONFIGMODE_NEVERSHOW"] = "다시 보여 주지 않음" -- Needs review
L["COPYGROUP"] = "해당 그룹 복사" -- Needs review
L["COPYPOSSCALE"] = "위치/크기 비율 복사" -- Needs review
L["CREATURETYPE_1"] = "야수"
L["CREATURETYPE_10"] = "기타"
L["CREATURETYPE_11"] = "토템"
L["CREATURETYPE_12"] = "애완동물"
L["CREATURETYPE_13"] = "가스 구름"
L["CREATURETYPE_14"] = "야생 애완동물"
L["CREATURETYPE_2"] = "용족"
L["CREATURETYPE_3"] = "악마"
L["CREATURETYPE_4"] = "정령"
L["CREATURETYPE_5"] = "거인"
L["CREATURETYPE_6"] = "언데드"
L["CREATURETYPE_7"] = "인간형"
L["CREATURETYPE_8"] = "동물"
L["CREATURETYPE_9"] = "기계"
L["CrowdControl"] = "군중 제어" -- Needs review
L["Curse"] = "저주" -- Needs review
L["DAMAGER"] = "피해" -- Needs review
L["DEBUFFTOCHECK"] = "체크할 약화 효과" -- Needs review
L["DEBUFFTOCOMP1"] = "비교할 첫번째 약화 효과 " -- Needs review
L["DEBUFFTOCOMP2"] = "비교할 두번째 약화 효과 " -- Needs review
L["DEFAULT"] = "기본" -- Needs review
L["DefensiveBuffs"] = "방어적 강화효과" -- Needs review
L["DESCENDING"] = "내림" -- Needs review
L["DISABLED"] = "비활성화" -- Needs review
L["Disarmed"] = "무장해제" -- Needs review
L["Disease"] = "질병" -- Needs review
L["Disoriented"] = "혼란"
L["DR-Banish"] = "추방" -- Needs review
L["DR-ControlledRoot"] = "군중 제어 묶기" -- Needs review
L["DR-ControlledStun"] = "군중 제어 기절" -- Needs review
L["DR-Cyclone"] = "회오리 바람" -- Needs review
L["DR-Disarm"] = "무장 해제" -- Needs review
L["DR-DragonsBreath"] = "용의 숨결" -- Needs review
L["DR-Entrapment"] = "올가미" -- Needs review
L["DR-Fear"] = "공포" -- Needs review
L["DR-MindControl"] = "정신 지배" -- Needs review
L["DR-RandomRoot"] = "무작위 묶기" -- Needs review
L["DR-RandomStun"] = "무작위 기절" -- Needs review
L["DR-Scatter"] = "산탄 사격" -- Needs review
L["DR-Silence"] = "침묵" -- Needs review
L["DR-Taunt"] = "도발" -- Needs review
L["DURATION"] = "지속시간" -- Needs review
L["EARTH"] = "대지" -- Needs review
L["ECLIPSE_DIRECTION"] = "식 진행방향" -- Needs review
L["elite"] = "정예" -- Needs review
L["ERROR_MISSINGFILE"] = "TellMeWhen %s(%s|1을;를; 찾을 수 없습니다)|1을;를; 사용하려면 WoW의 완벽한 재시작이 필요합니다. 지금 WoW를 재시작하시겠습니까? " -- Needs review
L["EXPORT_f"] = "%s 내보내기 "
L["EXPORT_HEADING"] = "내보내기"
L["EXPORT_TOCOMM"] = "플레이어에게"
L["EXPORT_TOSTRING"] = "문자열에"
L["FALSE"] = "False(거짓)" -- Needs review
L["Feared"] = "공포" -- Needs review
L["fGROUP"] = "그룹: %s" -- Needs review
L["fICON"] = "아이콘: %s" -- Needs review
L["FIRE"] = "불" -- Needs review
L["FONTCOLOR"] = "글꼴 색상" -- Needs review
L["FONTSIZE"] = "글꼴 크기" -- Needs review
L["fPROFILE"] = "프로필: %s" -- Needs review
L["GCD"] = "전체 대기시간"
L["GCD_ACTIVE"] = "GCD 활성 상태" -- Needs review
L["GENERIC_NUMREQ_CHECK_DESC"] = "%s|1을;를; 활성화하고 설정하려면 체크하십시오." -- Needs review
L["GROUPADDONSETTINGS"] = "그룹 설정" -- Needs review
L["GROUPCONDITIONS"] = "그룹 조건" -- Needs review
L["GROUPICON"] = "그룹: %s, 아이콘: %s" -- Needs review
L["HEALER"] = "치유" -- Needs review
L["Heals"] = "플레이어 치유" -- Needs review
L["HELP_EXPORT_DOCOPY_WIN"] = "|cff7fffffCTRL+C|r 입력시 복사"
L["ICON"] = "아이콘"
L["ICONALPHAPANEL_FAKEHIDDEN"] = "항상 숨기기" -- Needs review
L["ICONGROUP"] = "아이콘: %s(그룹: %s)"
L["ICONMENU_ABSENT"] = "없음"
L["ICONMENU_ALPHA"] = "불투명도" -- Needs review
L["ICONMENU_BOTH"] = "Either(둘 중의 하나)" -- Needs review
L["ICONMENU_BUFF"] = "강화 효과"
L["ICONMENU_BUFFDEBUFF"] = "강화 효과/약화 효과"
L["ICONMENU_BUFFTYPE"] = "강화 효과 또는 약화 효과"
L["ICONMENU_CAST"] = "주문 시전" -- Needs review
L["ICONMENU_CASTS"] = "주문 시전" -- Needs review
L["ICONMENU_CASTSHOWWHEN"] = "시전된 경우에 보이기" -- Needs review
L["ICONMENU_CHOOSENAME_ORBLANK"] = "모두 추적하려면 OR를 빈란으로 놔 두십시오. " -- Needs review
L["ICONMENU_CNDTIC"] = "조건 아이콘" -- Needs review
L["ICONMENU_COOLDOWNCHECK"] = "재사용 대기 체크" -- Needs review
L["ICONMENU_COOLDOWNCHECK_DESC"] = "아이콘이 재사용 대기 중이라 사용할 수 없는 것으로 간주하려면 이것에 체크하십시오." -- Needs review
L["ICONMENU_COPYHERE"] = "여기에 복사" -- Needs review
L["ICONMENU_CUSTOMTEX"] = "사용자 텍스쳐" -- Needs review
L["ICONMENU_DEBUFF"] = "약화 효과"
L["ICONMENU_DISPEL"] = "해제 유형" -- Needs review
L["ICONMENU_DONTREFRESH"] = "갱신 안 함" -- Needs review
L["ICONMENU_DURATION_MAX_DESC"] = "아이콘이 보여지는 최대 지속시간" -- Needs review
L["ICONMENU_DURATION_MIN_DESC"] = "아이콘이 보여지는데 필요한 최소 지속시간" -- Needs review
L["ICONMENU_ENABLE"] = "활성화"
L["ICONMENU_FOCUS"] = "주시 대상" -- Needs review
L["ICONMENU_FOCUSTARGET"] = "주시 대상"
L["ICONMENU_FRIEND"] = "우호적"
L["ICONMENU_HIDEUNEQUIPPED"] = "무기칸이 비워 있는 경우에 숨기기"
L["ICONMENU_HOSTILE"] = "적대적"
L["ICONMENU_ICD"] = "내부 재사용 대기" -- Needs review
L["ICONMENU_ICDBDE"] = "버프/디버프/피해/에너지/소환" -- Needs review
L["ICONMENU_IGNORENOMANA"] = "마력 부족 무시" -- Needs review
L["ICONMENU_IGNORERUNES"] = "룬 무시" -- Needs review
L["ICONMENU_INVERTBARS"] = "바 채우기"
L["ICONMENU_ITEMCOOLDOWN"] = "아이템 재사용 대기"
L["ICONMENU_MANACHECK"] = "마력 체크" -- Needs review
L["ICONMENU_MANACHECK_DESC"] = "마나/분노/룬 마력등이 부족한 경우에 아이콘의 색상 변경 기능을 활성화하려면 이것에 체크하십시오." -- Needs review
L["ICONMENU_META_DESC"] = [=[이 아이콘 유형은 몇개의 아이콘을 하나로 합치는데 사용될 수 있습니다.

]=] -- Needs review
L["ICONMENU_MOUSEOVER"] = "마우스 올림" -- Needs review
L["ICONMENU_MOUSEOVERTARGET"] = "마우스 올림의 대상" -- Needs review
L["ICONMENU_MOVEHERE"] = "여기로 이동" -- Needs review
L["ICONMENU_OFFS"] = "좌표" -- Needs review
L["ICONMENU_ONLYBAGS"] = "가방에 있다면 한해" -- Needs review
L["ICONMENU_ONLYIFCOUNTING"] = "활성화 상태의 타이머에 한해 보이기" -- Needs review
L["ICONMENU_ONLYINTERRUPTIBLE"] = "차단이 가능한 것에 한해" -- Needs review
L["ICONMENU_ONLYINTERRUPTIBLE_DESC"] = "차단할 수 있는 주문 시전만을 보여주려면 이 박스에 체크하십시오." -- Needs review
L["ICONMENU_ONLYMINE"] = "내 것만 보이기"
L["ICONMENU_ONLYMINE_DESC"] = "이 아이콘을 자신의 강화 효과/약화 효과에 한해 체크하려면 이 옵션에 체크하십시오." -- Needs review
L["ICONMENU_PETTARGET"] = "소환수의 대상"
L["ICONMENU_PRESENT"] = "현재"
L["ICONMENU_RANGECHECK"] = "사정 거리 체크" -- Needs review
L["ICONMENU_RANGECHECK_DESC"] = "사정 거리 밖인 경우에 아이콘의 색상 변경 기능을 활성화하려면 이것에 체크하십시오." -- Needs review
L["ICONMENU_REACT"] = "유닛 대응"
L["ICONMENU_REACTIVE"] = "대응 능력"
L["ICONMENU_RUNES"] = "룬 재사용 대기" -- Needs review
L["ICONMENU_SHOWSTACKS"] = "중첩 횟수 보이기" -- Needs review
L["ICONMENU_SHOWTIMER"] = "타이머 보이기"
L["ICONMENU_SHOWTIMER_DESC"] = "적용이 가능한 경우에 아이콘에 기본 재사용 대기 교체 애니메이션을 표시하려면 이 옵션에 체크하십시오." -- Needs review
L["ICONMENU_SHOWTIMERTEXT"] = "타이머 문자 보이기" -- Needs review
L["ICONMENU_SHOWTIMERTEXT_DESC"] = [=[아이콘에 남은 재사용 대기/지속시간의 문자를 표시하려면 이 옵션을 체크하십시오

이것은 OmniCC(또는 유사품)가 설치되어있는 경우에만 적용됩니다]=]
L["ICONMENU_SHOWTTTEXT"] = "변수 문자 보이기" -- Needs review
L["ICONMENU_SHOWWHEN"] = "상태 및 투명도 보기" -- Needs review
L["ICONMENU_SORTASC"] = "낮은 지속시간" -- Needs review
L["ICONMENU_SORTDESC"] = "높은 지속시간" -- Needs review
L["ICONMENU_SORTDESC_DESC"] = "가장 높은 지속시간으로 주문의 우선 순위를 매기고 보이려면 이 박스에 체크하십시오." -- Needs review
L["ICONMENU_SPELLCAST_COMPLETE"] = "주문 시전 완료/즉시 시전" -- Needs review
L["ICONMENU_SPELLCAST_COMPLETE_DESC"] = [=[이 옵션은 주문 시전이 끝난 경우에, 또는 즉시 시전 주문을 시전한 경우에 내부 재사용 대기가 시작된다면 선택하십시오.

%q 편집 박스에 내부 재사용 대기를 적용할 주문의 이름/ID를 입력하는 것이 필요합니다.   ]=] -- Needs review
L["ICONMENU_SPELLCAST_START"] = "주문 시전 시작" -- Needs review
L["ICONMENU_SPELLCAST_START_DESC"] = [=[이 옵션은 주문을 시전하기 시작할 경우에 내부 재사용 대기가 시작한다면 선택하십시오.

%q 편집 박스에 내부 재사용 대기를 적용할 주문의 이름/ID를 입력하는 것이 필요합니다. ]=] -- Needs review
L["ICONMENU_SPELLCOOLDOWN"] = "주문 재사용 대기"
L["ICONMENU_STACKS_MAX_DESC"] = "아이콘에 보여 줄 수 있는 최대 중첩 횟수" -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "아이콘에 보여 주는데 필요한 최소 중첩 횟수" -- Needs review
L["ICONMENU_STEALABLE"] = "훔칠 수 있는 것에 한해" -- Needs review
L["ICONMENU_STEALABLE_DESC"] = "주문을 훔칠 수 있는 강화 효과에 한해 보이려면 이것에 체크하십시오. '마법' 유형에 대해 체크할 경우에 가장 낫게 사용될 수 있습니다. " -- Needs review
L["ICONMENU_TARGETTARGET"] = "대상의 대상"
L["ICONMENU_TOTEM"] = "토템"
L["ICONMENU_TYPE"] = "아이콘 유형"
L["ICONMENU_UNITCOOLDOWN"] = "유닛 재사용 대기" -- Needs review
L["ICONMENU_UNITS"] = "유닛" -- Needs review
L["ICONMENU_UNITSTOWATCH"] = "감시할 유닛" -- Needs review
L["ICONMENU_UNUSABLE"] = "사용할 수 없음"
L["ICONMENU_USABLE"] = "사용 가능"
L["ICONMENU_VEHICLE"] = "탈것" -- Needs review
L["ICONMENU_WPNENCHANT"] = "무기 마법부여"
L["ICONMENU_WPNENCHANTTYPE"] = "관찰할 무기 칸"
L["ICONTOCHECK"] = "체크할 아이콘" -- Needs review
L["ImmuneToMagicCC"] = "마법 CC에 면역" -- Needs review
L["ImmuneToStun"] = "기절에 면역" -- Needs review
L["IMPORTERROR_FAILEDPARSE"] = "문자열을 처리하는 도중 오류가 발생했습니다. 출처에서 전체 문자열이 복사되었는지 확인하십시오." -- Needs review
L["IMPORT_EXPORT"] = "들여오기/내보내기" -- Needs review
L["IMPORT_EXPORT_BUTTON_DESC"] = "아이콘, 그룹, 프로필을 들여오고 내보내려면 이 재사용 대기를 클릭하십시오. " -- Needs review
L["IMPORT_EXPORT_DESC"] = [=[아이콘, 그룹, 프로필을 들여오고 내보내려면 우측의 버튼을 클릭하세요

문자열에서 가져오거나 다른 플레이어로 내보낼때 이 편집박스의 사용을 필요로합니다. 자세한 내용은 드롭다운 메뉴에서 툴팁을 참조하세요]=]
L["IMPORT_EXPORT_DESC_INLINE"] = "프로필/그룹/문자열이나 아이콘/다른 플레이어/다른 프로필 또는 설정된 백업에서 불러오거나 내보냅니다"
L["IMPORT_FROMBACKUP"] = "백업본에서"
L["IMPORT_FROMBACKUP_WARNING"] = "백업본 설정: %s"
L["IMPORT_FROMCOMM"] = "플레이어에서"
L["IMPORT_FROMLOCAL"] = "프로필에서"
L["IMPORT_FROMSTRING"] = "문자열에서"
L["IMPORT_HEADING"] = "들여오기"
L["IMPORT_PROFILE"] = "프로필 복사"
L["IMPORT_PROFILE_NEW"] = "새 프로필 |cff59ff59생성|r"
L["IMPORT_PROFILE_OVERWRITE"] = "%s |cFFFF5959덮어쓰기|r"
L["Incapacitated"] = "움직이지 못함"
L["IncreasedAP"] = "공격력 증가"
L["IncreasedCrit"] = "치명타 / 극대화 확률 증가"
L["IncreasedPhysHaste"] = "물리적 가속도 증가" -- Needs review
L["IncreasedSpellHaste"] = "주문 가속력 증가" -- Needs review
L["IncreasedSPsix"] = "주문력 증가 (6%)"
L["IncreasedSPten"] = "주문력 증가 (10%)"
L["IncreasedStats"] = "능력치 증가"
L["INRANGE"] = "사정 거리내" -- Needs review
L["ITEMCOOLDOWN"] = "아이템 재사용 대기" -- Needs review
L["ITEMTOCHECK"] = "체크할 아이템" -- Needs review
L["ITEMTOCOMP1"] = "비교할 첫번째 아이템 " -- Needs review
L["ITEMTOCOMP2"] = "비교할 두번째 아이템 " -- Needs review
L["LDB_TOOLTIP1"] = "|cff7fffff좌-클릭:|r 그룹 잠금 전환" -- Needs review
L["LDB_TOOLTIP2"] = "|cff7fffff우-클릭:|r 주 TMW 옵션 보이기" -- Needs review
L["LEFT"] = "좌측" -- Needs review
L["LOADERROR"] = "TellMeWhen_Options을 들여올 수 없습니다: " -- Needs review
L["LOADINGOPT"] = "TellMeWhen_Options을 불러들입니다." -- Needs review
L["LUACONDITION"] = "Lua (전문가)" -- Needs review
L["MACROCONDITION"] = "매크로 조건" -- Needs review
L["Magic"] = "마법" -- Needs review
L["!!Main Addon Description"] = "재사용 대기, 강화 효과와 그밖의 꽤 많은 것에 관해 시청각적이고도 문자적인 알림을 제공합니다. " -- Needs review
L["MAINASSIST"] = "지원 전담" -- Needs review
L["MAINTANK"] = "방어 전담" -- Needs review
L["MAKENEWGROUP"] = "새 그룹 생성" -- Needs review
L["MOON"] = "달" -- Needs review
L["MOUSEOVER_TOKEN_NOT_FOUND"] = "<마우스 올림 없음>" -- Needs review
L["MP5"] = "%d MP5" -- Needs review
L["NEWVERSION"] = "TellMeWhen의 새 버전이 이용 가능합니다: %s " -- Needs review
L["normal"] = "일반" -- Needs review
L["NOTINRANGE"] = "사정 거리내에 없음" -- Needs review
L["ONLYCHECKMINE"] = "내것에 한해 체크" -- Needs review
L["OUTLINE_MONOCHORME"] = "흑백" -- Needs review
L["OUTLINE_NO"] = "외곽선 없음" -- Needs review
L["OUTLINE_THICK"] = "굵은 외곽선" -- Needs review
L["OUTLINE_THIN"] = "얇은 외곽선 " -- Needs review
L["OVERWRITEGROUP"] = "그룹 |cFFFF5959덮어쓰기|r: %s"
L["PARENTHESIS_TYPE_("] = "열기" -- Needs review
L["PARENTHESIS_TYPE_)"] = "닫기" -- Needs review
L["PhysicalDmgTaken"] = "물리적 피해 얻음" -- Needs review
L["PLAYER_DESC"] = "(당신)" -- Needs review
L["Poison"] = "독" -- Needs review
L["PvPSpells"] = "PvP 군중 제어 등" -- Needs review
L["rare"] = "희귀" -- Needs review
L["rareelite"] = "희귀 정에" -- Needs review
L["REDO_ICON"] = "다시 실행" -- Needs review
L["REDO_ICON_DESC"] = "이 아이콘의 설정으로 민들어진 마지막 변경 사항의 실행을 다시 실행합니다." -- Needs review
L["ReducedArmor"] = "방어도 감소" -- Needs review
L["ReducedCastingSpeed"] = "시전 속도 감소" -- Needs review
L["ReducedHealing"] = "치유량 감소" -- Needs review
L["ReducedPhysicalDone"] = "물리적 피해 감소" -- Needs review
L["RESET_ICON"] = "초기화" -- Needs review
L["RESIZE"] = "크기 조절"
L["RESIZE_TOOLTIP"] = "크기를 변경하려면 클릭한 후에 잡아 끄십시오." -- Needs review
L["RIGHT"] = "우측" -- Needs review
L["Rooted"] = "묶임" -- Needs review
L["RUNES"] = "체크할 룬" -- Needs review
L["RUNSPEED"] = "유닛 달리기 속도" -- Needs review
L["SENDSUCCESSFUL"] = "성공적으로 보냈습니다." -- Needs review
L["SHAPESHIFT"] = "변신" -- Needs review
L["Silenced"] = "침묵" -- Needs review
L["SORTBY"] = "우선순위 매기기" -- Needs review
L["SOUND_CUSTOM"] = "사용자 소리 파일" -- Needs review
L["SOUNDERROR2"] = "사용자 wav 파일은 WoW 4.0+에서 지원하지 않습니다." -- Needs review
L["SOUNDERROR3"] = "OGG와  MP3 파일만 지원됩니다!" -- Needs review
L["SOUND_EVENT_ONALPHADEC"] = "투명도 감소시" -- Needs review
L["SOUND_EVENT_ONALPHADEC_DESC"] = [=[이 이벤트는 아이콘의 불투명도가 감소된 경우에 적용됩니다.

주의: 이 이벤트는 0% 반투명도(숨기기시)로 감소되는 경우에 적용되지 않습니다.]=] -- Needs review
L["SOUND_EVENT_ONALPHAINC"] = "투명도 증가시" -- Needs review
L["SOUND_EVENT_ONALPHAINC_DESC"] = [=[이 이벤트는 아이콘의 불투명도가 증가된 경우에 적용됩니다.

주의: 이 이벤트는 0% 반투명도(보이기시)로 증가되는 경우에 적용되지 않습니다.]=] -- Needs review
L["SOUND_EVENT_ONHIDE_DESC"] = "이 이벤트는 아이콘이 숨겨져 있는 경우에 적용됩니다(비록 '항상 숨기기'가 체크되어 있다 할지라도)" -- Needs review
L["SOUND_EVENT_ONSHOW"] = "On Show(보이기시)" -- Needs review
L["SOUND_EVENT_ONSHOW_DESC"] = "이 이벤트는 아이콘이 보여지는 경우에 적용됩니다(비록 '항상 숨기기'가 체크되어 있다 할지라도)" -- Needs review
L["SOUND_EVENT_ONSTART"] = "On Start(시작시)" -- Needs review
L["SOUND_EVENT_ONSTART_DESC"] = "이 이벤트는 재사용 대기가 사용할 수 없게 되고, 강화/약화 효과가  적용되어 있는 등의 경우에 적용됩니다." -- Needs review
L["SOUND_SOUNDTOPLAY"] = "재생할 소리" -- Needs review
L["SOUND_TAB"] = "소리" -- Needs review
L["SPEED"] = "유닛 속도" -- Needs review
L["SPEED_DESC"] = "이것은 유닛의 현재 이동 속도를 제공합니다. 유닛이 이동할 수 없다면 그것은 0일 것 입니다. 유닛의 최고 달리기 속도를 추적하고자 한다면 이것 대신에 '유닛 달리기 속도' 조건을 사용하십시오.  " -- Needs review
L["SPELLCOOLDOWN"] = "주문 재사용 대기" -- Needs review
L["SpellDamageTaken"] = "주문 피해 얻음 증가" -- Needs review
L["SPELLTOCHECK"] = "체크할 주문" -- Needs review
L["SPELLTOCOMP1"] = "비교할 첫번째 주문" -- Needs review
L["SPELLTOCOMP2"] = "비교할 두번째 주문" -- Needs review
L["STANCE"] = "태세" -- Needs review
L["STRATA_BACKGROUND"] = "배경"
L["STRATA_DIALOG"] = "대화상자"
L["STRATA_FULLSCREEN"] = "전체화면"
L["STRATA_FULLSCREEN_DIALOG"] = "전체화면 대화상자" -- Needs review
L["STRATA_HIGH"] = "높음"
L["STRATA_LOW"] = "낮음"
L["STRATA_MEDIUM"] = "중간"
L["STRATA_TOOLTIP"] = "툴팁"
L["Stunned"] = "기절" -- Needs review
L["SUG_DISPELTYPES"] = "해제 유형" -- Needs review
L["SUG_MATCH_WPNENCH_ENCH"] = "(.*)" -- Needs review
L["SUG_MISC"] = "기타" -- Needs review
L["SUG_PATTERNMATCH_FISHINGLURE"] = "미끼 %(낚시 숙련도 %+%d+%)"
L["SUG_PATTERNMATCH_SHARPENINGSTONE"] = "무기 연마 %(공격력 %+%d+%)"
L["SUG_PATTERNMATCH_WEIGHTSTONE"] = "무게 증강 %(공격력 %+%d+%)"
L["SUG_PLAYERSPELLS"] = "당신의 주문" -- Needs review
L["SUN"] = "해" -- Needs review
L["Tier11Interrupts"] = "티어 11 차단 가능" -- Needs review
L["Tier12Interrupts"] = "티어 12 차단가능" -- Needs review
L["TOP"] = "상단" -- Needs review
L["TOPLEFT"] = "좌측 상단" -- Needs review
L["TOPRIGHT"] = "우측 상단" -- Needs review
L["TOTEMS"] = "체크할 토템" -- Needs review
L["TRUE"] = "True(참)" -- Needs review
L["UIPANEL_ADDGROUP"] = "+ 다른 그룹 추가 +" -- Needs review
L["UIPANEL_ADDGROUP_DESC"] = "새 그룹은 가능한 다음 그룹ID를 할당받게 됩니다." -- Needs review
L["UIPANEL_ALLRESET"] = "모두 초기화"
L["UIPANEL_BARIGNOREGCD"] = "바 GCD 무시" -- Needs review
L["UIPANEL_BARIGNOREGCD_DESC"] = "체크시, 재사용 대기 바는 재사용 대기가 전역 재사용 대기에 적용된다면 값을 변경하지 않게 됩니다. " -- Needs review
L["UIPANEL_BARTEXTURE"] = "바 텍스쳐"
L["UIPANEL_CLOCKIGNOREGCD"] = "타이머 GCD 무시" -- Needs review
L["UIPANEL_CLOCKIGNOREGCD_DESC"] = "체크시, 타이머와 시계 방향 재사용 대기는 전역 재사용 대기에서 적용되지 않습니다." -- Needs review
L["UIPANEL_COLORS"] = "색상" -- Needs review
L["UIPANEL_COLUMNS"] = "행 개수"
L["UIPANEL_DELGROUP"] = "이 그룹 삭제" -- Needs review
L["UIPANEL_DRAWEDGE"] = "타이머 모서리 강조" -- Needs review
L["UIPANEL_DRAWEDGE_DESC"] = "가시성을 높이기 위해 재사용 대기 타이머(시계 방향 애니메이션)의 모서리를 강조합니다." -- Needs review
L["UIPANEL_EFFTHRESHOLD"] = "강화 효과 효력 한계치" -- Needs review
L["UIPANEL_ENABLEGROUP"] = "그룹 활성"
L["UIPANEL_FONT_DESC"] = "아이콘에 중첩 횟수 문자에 의해 사용될 글꼴을 선택하십시오." -- Needs review
L["UIPANEL_FONTFACE"] = "글꼴체" -- Needs review
L["UIPANEL_FONT_OUTLINE"] = "글꼴 외곽선" -- Needs review
L["UIPANEL_FONT_OUTLINE_DESC"] = "아이콘에 중첩 횟수 문자를 위한 외곽선 양식을 설정합니다." -- Needs review
L["UIPANEL_FONT_SIZE"] = "글꼴 크기" -- Needs review
L["UIPANEL_FONT_SIZE_DESC"] = "아이콘에 중첩 횟수 문자를 위해 사용될 글꼴의 크기를 변경합니다. ButtonFacade를 사용하고 스킨 세트가 글꼴 크기가 지정되어 있다면, 이 값은 무시됩니다.  " -- Needs review
L["UIPANEL_FONT_XOFFS"] = "X 좌표" -- Needs review
L["UIPANEL_FONT_YOFFS"] = "Y 좌표" -- Needs review
L["UIPANEL_GROUPNAME"] = "그룹 이름 변경" -- Needs review
L["UIPANEL_GROUPRESET"] = "위치 초기화"
L["UIPANEL_GROUPS"] = "그룹" -- Needs review
L["UIPANEL_ICONS"] = "아이콘" -- Needs review
L["UIPANEL_ICONSPACING_DESC"] = "그룹내의 각 아이콘이 다른 아이콘에 대해 떨어져 있어야 할 간격" -- Needs review
L["UIPANEL_LEVEL"] = "프레임 레벨" -- Needs review
L["UIPANEL_LOCK"] = "그룹 잠그기" -- Needs review
L["UIPANEL_LOCKUNLOCK"] = "애드온 잠금/잠금 해제"
L["UIPANEL_MAINOPT"] = "주 옵션"
L["UIPANEL_ONLYINCOMBAT"] = "전투시에만 보이기"
L["UIPANEL_POINT"] = "포인트" -- Needs review
L["UIPANEL_POSITION"] = "위치" -- Needs review
L["UIPANEL_PRIMARYSPEC"] = "주 특성 전문화"
L["UIPANEL_PTSINTAL"] = "특성에서의 포인트" -- Needs review
L["UIPANEL_ROWS"] = "열 개수"
L["UIPANEL_SCALE"] = "크기비율" -- Needs review
L["UIPANEL_SECONDARYSPEC"] = "보조 특성 전문화"
L["UIPANEL_SPEC"] = "이중 특성 전문화" -- Needs review
L["UIPANEL_STRATA"] = "프레임 계층" -- Needs review
L["UIPANEL_SUBTEXT2"] = "잠겨 있는 경우에 아이콘이 작동합니다. 잠금이 해제된 경우에, 아이콘 그룹을 이동하거나 크기를 조절할 수 있으며 더 많은 설정을 위해서 각 아이콘을 개별적으로 우-클릭할 수 있습니다. 또한 잠금/잠금 해제하기 위해 /tellmewhen 또는 /tmw를 입력할 수 있습니다." -- Needs review
L["UIPANEL_TOOLTIP_ALLRESET"] = "모든 다른 설정과 마찬가지로, 모든 아이콘과 그룹의 자료와 위치를 초기화합니다."
L["UIPANEL_TOOLTIP_COLUMNS"] = "이 그룹에서의 행 개수를 설정합니다."
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "이 그룹을 보여주고 활성화합니다."
L["UIPANEL_TOOLTIP_GROUPRESET"] = "이 그룹의 위치와 크기 비율을 초기화합니다."
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "이 그룹이 체크되는 것으로 전투시에만 보여지게 됩니다." -- Needs review
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "주 특성 전문화가 활성화되어 있는 동안에 이 그룹이 보여지게 하려면 체크하십시오."
L["UIPANEL_TOOLTIP_ROWS"] = "이 그룹의 열 개수를 설정합니다." -- Needs review
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "보조 특성 전문화가 활성화되어 있는 동안에 이 그룹이 보여지게 하려면 체크하십시오." -- Needs review
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "보이기/숨기기, 투명도, 조건 등을 위해 아이콘의 확인 빈도(초 단위)를 설정합니다. 낮은 값은 성능이 낮은 컴퓨터에 대해 프레임율에 상당한 영향을 미칠 수 있습니다." -- Needs review
L["UIPANEL_TREE"] = "특성 트리" -- Needs review
L["UIPANEL_UPDATEINTERVAL"] = "업데이트 간격" -- Needs review
L["UIPANEL_WARNINVALIDS"] = "개별적인 아이콘에 대해 경고" -- Needs review
L["UNDO_ICON"] = "실행 취소" -- Needs review
L["UNDO_ICON_DESC"] = "이 아이콘의 설정으로 민들어진 마지막 변경 사항의 실행을 취소합니다." -- Needs review
L["WATER"] = "물" -- Needs review
L["worldboss"] = "우두머리" -- Needs review



