--[[ Credit for these translations goes to:
	Mordroba
	Djidiouf
	Fenrirpims
	Ikshaar
	Avold
	Viny
	contrebasse
--]]
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "frFR", false)
if not L then return end


L["ALPHA"] = "Alpha" -- Needs review
L["ANIM_ACTVTNGLOW"] = "Icône: Activation des bordures" -- Needs review
L["ANIM_COLOR"] = "Couleur / Opacité" -- Needs review
L["ANIM_COLOR_DESC"] = "Configurer la couleur et l'opacité du flash." -- Needs review
L["Bleeding"] = "Saigne"
L["BonusStamina"] = "Endurance augmentée"
L["BurstManaRegen"] = "Burst de Regen Mana"
L["CASTERFORM"] = "Forme de lanceur de sorts"
L["CHOOSENAME_DIALOG"] = "Entrer le nom ou l'id du Sort/Capacité/Objet/Buff/Débuff attribué à cette icône. Vous pouvez ajouter de multiples buffs/débuffs en les séparant avec ';'." -- Needs review
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "Ensembles de sorts prédéfinis."
L["CHOOSENAME_DIALOG_PETABILITIES"] = "|cFFFF5959COMPETENCES PET|r devraient utiliser SpellIDs." -- Needs review
L["CMD_OPTIONS"] = "Options" -- Needs review
L["CONDITIONPANEL_ALIVE"] = "Unité est en vie" -- Needs review
L["CONDITIONPANEL_ALIVE_DESC"] = "Le test passera si l'unité est en vie" -- Needs review
L["CONDITIONPANEL_AND"] = "Et"
L["CONDITIONPANEL_ANDOR"] = "Et / Ou"
L["CONDITIONPANEL_COMBAT"] = "Unité est en combat"
L["CONDITIONPANEL_COMBO"] = "Points de combo"
L["CONDITIONPANEL_ECLIPSE_DESC"] = [=[Eclipse fonctionne sur une fourchette de valeurs allant de -100 (éclipse lunaire) à 100 (éclipse solaire).
Entrez -80 si vous voulez faire fonctionner l'icône avec une valeur de 80 en éclipse lunaire.]=]
L["CONDITIONPANEL_EQUALS"] = "Égal à"
L["CONDITIONPANEL_EXISTS"] = "L'unité existe"
L["CONDITIONPANEL_GREATER"] = "Plus Grand Que"
L["CONDITIONPANEL_GREATEREQUAL"] = "Plus Grand Que ou Égal à"
L["CONDITIONPANEL_ICON"] = "Icône affichée"
L["CONDITIONPANEL_ICON_DESC"] = [=[La condition sera remplie si l'icône spécifiée est actuellement affichée avec une transparence supérieure à 0.
Si vous ne voulez pas afficher les icônes cochées, cochez l'option %q dans les réglages de la transparence de l'icône.
Le groupe de l'icône cochée doit aussi être affiché pour cocher l'icône.]=] -- Needs review
L["CONDITIONPANEL_LESS"] = "Moins Que"
L["CONDITIONPANEL_LESSEQUAL"] = "Moins Que ou Égal à"
L["CONDITIONPANEL_NOTEQUAL"] = "Pas Égal à"
L["CONDITIONPANEL_OPERATOR"] = "Opérateur"
L["CONDITIONPANEL_OR"] = "Ou"
L["CONDITIONPANEL_POWER"] = "Puissance"
L["CONDITIONPANEL_POWER_DESC"] = [=[Vérifiera l'énergie du personnage s'il s'agit d'un druide en forme de félin,
sa rage si le personnage est un guerrier, etc.]=]
L["CONDITIONPANEL_PVPFLAG"] = "Unité est taggué PVP"
L["CONDITIONPANEL_TYPE"] = "Type"
L["CONDITIONPANEL_UNIT"] = "Personnage"
L["CONDITIONPANEL_VALUEN"] = "Valeur"
L["COPYPOSSCALE"] = "Copier position/échelle" -- Needs review
L["CREATURETYPE_1"] = "Bête"
L["CREATURETYPE_10"] = "Non spécifié"
L["CREATURETYPE_11"] = "Totem"
L["CREATURETYPE_12"] = "Mascotte pacifique"
L["CREATURETYPE_13"] = "Nuage de gaz"
L["CREATURETYPE_14"] = "Mascotte sauvage"
L["CREATURETYPE_2"] = "Draconien"
L["CREATURETYPE_3"] = "Démon"
L["CREATURETYPE_4"] = "Elémentaire"
L["CREATURETYPE_5"] = "Géant"
L["CREATURETYPE_6"] = "Mort-vivant"
L["CREATURETYPE_7"] = "Humanoïde"
L["CREATURETYPE_8"] = "Bestiole"
L["CREATURETYPE_9"] = "Machine"
L["DISABLED"] = "Désactivé"
L["Disarmed"] = "Désarmé"
L["Disoriented"] = "Désorienté"
L["ECLIPSE_DIRECTION"] = "Sens de l'éclipse"
L["EVENTS_SETTINGS_PASSTHROUGH"] = "Continuer à réduire les événements" -- Needs review
L["FALSE"] = "Faux"
L["Feared"] = "Peur"
L["GCD"] = "Temps de recharge global" -- Needs review
L["GROUPICON"] = "Groupe : %s, Icône : %d"
L["ICONALPHAPANEL_FAKEHIDDEN"] = "Toujours Masquer" -- Needs review
L["ICONALPHAPANEL_FAKEHIDDEN_DESC"] = "Tout le temps cacher l’icône tout en la laissant active afin de permettre aux conditions des autres icônes d'effectuer des vérifications sur l’icône toujours masquer." -- Needs review
L["ICONMENU_ABSENT"] = "Absent"
L["ICONMENU_ALPHA"] = "Transparence"
L["ICONMENU_BOTH"] = "Soit"
L["ICONMENU_BUFF"] = "Buff"
L["ICONMENU_BUFFDEBUFF"] = "Buff/Débuff"
L["ICONMENU_BUFFTYPE"] = "Buff ou débuff ?" -- Needs review
L["ICONMENU_CASTSHOWWHEN"] = "Montrer quand un sort est"
L["ICONMENU_COOLDOWNCHECK"] = "Vérification de cooldown ?"
L["ICONMENU_DEBUFF"] = "Débuff"
L["ICONMENU_DURATION_MAX_DESC"] = "Durée maximale permise pour afficher l'icône"
L["ICONMENU_DURATION_MIN_DESC"] = "Durée minimale nécessaire pour afficher l'icône"
L["ICONMENU_ENABLE"] = "Activé" -- Needs review
L["ICONMENU_FOCUS"] = "Focus"
L["ICONMENU_FOCUSTARGET"] = "Cible du focus"
L["ICONMENU_FRIEND"] = "Unités amicales"
L["ICONMENU_HIDEUNEQUIPPED"] = "Cacher quand le trou est vide" -- Needs review
L["ICONMENU_HOSTILE"] = "Unités hostiles"
L["ICONMENU_INVERTBARS"] = "Inverser les barres"
L["ICONMENU_MANACHECK"] = "Vérification de la quantité de puissance ?" -- Needs review
L["ICONMENU_MOUSEOVER"] = "Survol de la souris"
L["ICONMENU_MOUSEOVERTARGET"] = "Cible du survol de la souris"
L["ICONMENU_ONLYMINE"] = "Ne montrer que si lancé par soi" -- Needs review
L["ICONMENU_PETTARGET"] = "Cible du familier"
L["ICONMENU_PRESENT"] = "Présent"
L["ICONMENU_RANGECHECK"] = "Vérification de la portée ?"
L["ICONMENU_REACT"] = "Réaction d'unités"
L["ICONMENU_REACTIVE"] = "Sort réactif ou capacité"
L["ICONMENU_SHOWTIMER"] = "Montrer le timer"
L["ICONMENU_SHOWTIMERTEXT"] = "Afficher le numéro du timer"
L["ICONMENU_SHOWTIMERTEXT_DESC"] = "Ne peut être appliquer que si \"Montrer le timer\" est coché" -- Needs review
L["ICONMENU_SHOWWHEN"] = "Montrer l'icône quand"
L["ICONMENU_STACKS_MAX_DESC"] = "Nombre maximum de stacks de l'aura requis pour montrer l'icône" -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "Nombre minimum de stacks de l'aura requis pour montrer l’icône" -- Needs review
L["ICONMENU_TARGETTARGET"] = "Cible de la cible"
L["ICONMENU_TOTEM"] = "Totem/Goule non améliorée"
L["ICONMENU_TYPE"] = "Type d'icône"
L["ICONMENU_UNUSABLE"] = "Inutilisable"
L["ICONMENU_USABLE"] = "Utilisable"
L["ICONMENU_VEHICLE"] = "Véhicule"
L["ICONMENU_WPNENCHANT"] = "Enchantement d'arme temporaire"
L["ICONMENU_WPNENCHANTTYPE"] = "Slot d'arme à surveiller"
L["ICONTOCHECK"] = "Icône à vérifier"
L["ImmuneToMagicCC"] = "Immunisé aux contrôles magiques"
L["ImmuneToStun"] = "Immunisé aux étourdissements"
L["Incapacitated"] = "Incapacité"
L["IncreasedAP"] = "Puissance d'Attaque augmentée"
L["IncreasedCrit"] = "Chance de Coup Critique augmentée"
L["IncreasedPhysHaste"] = "Hâte en mêlée augmentée"
L["IncreasedSpellHaste"] = "Hâte des sorts augmentée"
L["IncreasedSPsix"] = "Puissance des sorts augmentée (6%)"
L["IncreasedSPten"] = "Puissance des sorts augmentée (10%)"
L["IncreasedStats"] = "Stats augmentées"
L["LDB_TOOLTIP1"] = "|cff7fffffCliquer-gauche|r pour basculer le verrouillage des groupes" -- Needs review
L["LDB_TOOLTIP2"] = "Cliquer-droit pour montrer/cacher certains groupes "
L["Magic"] = "Magie"
L["MOON"] = "Lunaire"
L["NONE"] = "Aucune des valeurs ci-dessous"
L["PhysicalDmgTaken"] = "Dégâts Physiques subits augmentés"
L["Poison"] = "Poison"
L["ReducedArmor"] = "Armure réduite"
L["ReducedCastingSpeed"] = "Vitesse d'incantation réduite"
L["ReducedHealing"] = "Soins prodigués réduits"
L["ReducedPhysicalDone"] = "Dommages physiques infligés réduits"
L["RESIZE"] = "Redimensionner"
L["RESIZE_TOOLTIP"] = "Cliquer et glisser pour changer la taille" -- Needs review
L["Rooted"] = "Immobilisé"
L["Silenced"] = "Silence"
L["SpellDamageTaken"] = "Augmentation des dégâts des sorts subis"
L["Stunned"] = "Étourdi"
L["SUG_MATCH_WPNENCH_ENCH"] = "Arme ([A-Z].*)|(.*)" -- Needs review
L["SUG_PATTERNMATCH_FISHINGLURE"] = "Appât de pêche %(%+%d+ compétence de pêche%)"
L["SUG_PATTERNMATCH_SHARPENINGSTONE"] = "Aiguisé %(%+%d+ points de dégâts%)"
L["SUG_PATTERNMATCH_WEIGHTSTONE"] = "Équilibré %(%+%d+ points de dégâts%)"
L["SUN"] = "Solaire"
L["TRUE"] = "Vrai"
L["UIPANEL_ADDGROUP"] = "Ajouter un autre groupe"
L["UIPANEL_ALLRESET"] = "Réinitialiser toutes les icônes"
L["UIPANEL_BARIGNOREGCD"] = "Les barres ignorent le GCD"
L["UIPANEL_BARIGNOREGCD_DESC"] = "Si cochée, les barres des cooldowns ne changeront pas de valeur si le cooldown déclenché est un cooldown global"
L["UIPANEL_BARTEXTURE"] = "Texture de barre"
L["UIPANEL_CLOCKIGNOREGCD"] = "Les timers ignorent le GCD"
L["UIPANEL_CLOCKIGNOREGCD_DESC"] = "Si cochée, les timers et l'horloge à cooldown ne se déclencheront pas à partir d'un cooldown global"
L["UIPANEL_COLORS"] = "Couleurs"
L["UIPANEL_COLUMNS"] = "Colonnes"
L["UIPANEL_DELGROUP"] = "Supprimer ce Groupe"
L["UIPANEL_DRAWEDGE"] = "Surbrillance de la bordure du timer"
L["UIPANEL_DRAWEDGE_DESC"] = "Mets en surbrillance la bordure du timer de cooldown (animation en forme de montre) pour augmenter sa visibilité"
L["UIPANEL_ENABLEGROUP"] = "Activer Groupe"
L["UIPANEL_FONT_DESC"] = "Choisissez la police d'écriture à utiliser pour le texte des stacks des icônes."
L["UIPANEL_FONT_SIZE"] = "Taille de la police"
L["UIPANEL_GROUPRESET"] = "Réinitialiser Position"
L["UIPANEL_GROUPS"] = "Groupes"
L["UIPANEL_ICONSPACING_DESC"] = "Espace entre les icones du même groupe" -- Needs review
L["UIPANEL_LOCK"] = "Verrouiller l'AddOn" -- Needs review
L["UIPANEL_LOCKUNLOCK"] = "Verrouiller/Déverrouiller l'AddOn"
L["UIPANEL_MAINOPT"] = "Options générales"
L["UIPANEL_ONLYINCOMBAT"] = "Ne montrer qu'en combat"
L["UIPANEL_PRIMARYSPEC"] = "Spé principale"
L["UIPANEL_ROWS"] = "Lignes"
L["UIPANEL_SECONDARYSPEC"] = "Spé secondaire"
L["UIPANEL_SUBTEXT2"] = "Les icônes fonctionnent lorsqu'elles sont verrouillées. Si déverrouillées, vous pouvez déplacer/redimensionner les groupes d'icônes et cliquer droit les icônes individuelles pour plus de réglages. Vous pouvez aussi taper '/tellmewhen' ou '/tmw' pour verrouiller/déverrouiller."
L["UIPANEL_TOOLTIP_ALLRESET"] = "Réinitialiser les DONNÉES et la POSITION de toutes les icônes"
L["UIPANEL_TOOLTIP_COLUMNS"] = "Nombre de colonnes d'icônes pour ce groupe"
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "Montrer et activer ce groupe d'icônes"
L["UIPANEL_TOOLTIP_GROUPRESET"] = "Réinitialise la position de ce groupe"
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "Cocher pour ne montrer ce groupe d'icônes qu'en combat"
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "Cocher pour montrer ce groupe d'icônes alors que votre spé principale est active"
L["UIPANEL_TOOLTIP_ROWS"] = "Nombre de lignes d'icônes pour ce groupe"
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "Cocher pour montrer ce groupe d'icônes alors que votre spé secondaire est active"
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "Règle l'intervalle de temps (en secondes) pendant lequel les icônes sont vérifiées pour être montrées/cachées, leur niveau alpha, les conditions, etc. Cela n'affecte pas les barres. Zéro : le plus rapide possible. De faibles valeurs peuvent avoir un impact important sur le nombre d'IPS pour des ordinateurs anciens."
L["UIPANEL_UPDATEINTERVAL"] = "Intervalle de mise à jour"
