--[[
	Bagnon Config Localization: Chinese Simplified
		Credits: Diablohu, yleaf@cwdg, 狂飙@cwdg, 天下牧@萨格拉斯
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'zhCN')
if not L then return end

L.Columns = '列数'
L.Scale = '缩放'
L.Spacing = '间距'
L.Opacity = '透明度'
L.FrameColor = '窗口颜色'
L.FrameBorderColor = '窗口边框颜色'
L.Frame = '窗口'
L.LockFramePositions = '锁定位置'
L.ShowEmptyItemSlotBackground = '显示空格背景材质'
L.HighlightItemsByQuality = '按物品品质对物品染色'
L.HighlightNewItems = '对新物品染色' 
L.HighlightUnusableItems = '对无法使用的物品染色'
L.HighlightSetItems = '对已经保存为套装的物品染色' 
L.HighlightQuestItems = '对任务物品染色'
L.ReverseSlotOrdering = '反向排列'
L.ColorItemSlotsByBagType = '按背包类型对空格染色'
L.FrameLayer = '窗口层级'
L.EnableBagFrame = '启用背包按钮'
L.EnableMoneyFrame = '启用货币窗口'
L.EnableDBOFrame = '启用信息窗口'
L.EnableSortButton = '启用整理按钮'
L.EnableSearchToggle = '启用搜索按钮'
L.EnableOptionsToggle = '启用设置按钮'
L.EnableFrame_inventory = '启用背包框体'
L.EnableFrame_bank = '启用银行框体'
L.SettingRequiresRestart = '这个设置将在你下次登录时生效'

L.EnableAutoDisplay_bank = '打开银行时'
L.EnableAutoDisplay_ah = '打开拍卖行时'
L.EnableAutoDisplay_vendor = '与商贩对话时'
L.EnableAutoDisplay_trade = '交易时'
L.EnableAutoDisplay_craft = '制作物品时'
L.EnableAutoDisplay_mail = '打开邮箱时'
L.EnableAutoDisplay_guildbank = '打开公会银行时'
L.EnableAutoDisplay_player = '打开角色信息时'
L.EnableAutoDisplay_combat = '进入战斗时关闭'
L.EnableAutoDisplay_vehicle = '进入载具时关闭'
L.EnableAutoDisplay_gems = '打开物品镶嵌时'

L.DisplaySettings = '事件设置'
L.DisplaySettingsTitle = '何时自动打开背包'
L.FrameSettings = '显示设置'
L.FrameSettingsTitle = '窗口显示设置'
L.GeneralSettings = '通用设置'
L.GeneralSettingsTitle = '通用设置'
L.EnableBlizzardBagPassThrough = '禁用的背包使用暴雪默认框体'
L.EnableBagBreak = '启用背包分散布局'
L.ColorSettings = '颜色设置'
L.ColorSettingsTitle = '物品染色设置'
L.ItemHighlightOpacity = '物品高亮亮度'
L.EnableFlashFind = '启用闪烁搜索'
L.EnableTipCount = '启用物品统计提示'
L.EnableFading = '启用框架渐隐'
L.AllowDisableBags = '当点击时禁用背包'

L.ItemSlotColor_normal = '一般背包槽颜色'
L.ItemSlotColor_leather = '制皮包槽颜色'
L.ItemSlotColor_inscri = '铭文包槽颜色'
L.ItemSlotColor_herb = '草药包槽颜色'
L.ItemSlotColor_enchant = '附魔包槽颜色'
L.ItemSlotColor_engineer = '工程箱槽颜色'
L.ItemSlotColor_gem = '宝石包槽颜色'
L.ItemSlotColor_mine = '矿石包槽颜色'
L.ItemSlotColor_tackle = '工具箱槽颜色'
L.ItemSlotColor_cooking = '烹饪包槽颜色'
L.ItemSlotColor_reagent = '材料银行颜色'
