--[[
	Bagnon Config Localization: English
		This file must be present to have partial translations
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'enUS', true)

L.Columns = 'Columns'
L.Scale = 'Scale'
L.Spacing = 'Spacing'
L.Opacity = 'Opacity'
L.FrameColor = 'Frame Color'
L.FrameBorderColor = 'Frame Border Color'
L.Frame = 'Frame'
L.LockFramePositions = 'Lock frame positions'
L.ShowEmptyItemSlotBackground = 'Display a background for empty item slots'
L.HighlightItemsByQuality = 'Highlight items by quality' 
L.HighlightNewItems = 'Highlight new items' 
L.HighlightUnusableItems = 'Highlight unusable items'
L.HighlightSetItems = 'Highlight equipment set items'
L.HighlightQuestItems = 'Highlight quest items'
L.ReverseSlotOrdering = 'Reverse bag slot ordering'
L.ColorItemSlotsByBagType = 'Color empty slots by bag type'
L.FrameLayer = 'Layer'
L.EnableBagFrame = 'Enable bag frame'
L.EnableMoneyFrame = 'Enable money frame'
L.EnableDBOFrame = 'Enable databroker frame'
L.EnableSortButton = 'Enable sort button'
L.EnableSearchToggle = 'Enable search toggle'
L.EnableOptionsToggle = 'Enable options toggle'
L.EnableFrame_inventory = 'Enable inventory frame'
L.EnableFrame_bank = 'Enable bank frame'
L.SettingRequiresRestart = 'This setting will take effect the next time you log in'

L.EnableAutoDisplay_bank = 'Display inventory when visiting the bank'
L.EnableAutoDisplay_ah = 'Display inventory when visiting the auction house'
L.EnableAutoDisplay_vendor = 'Close inventory when leaving a vendor'
L.EnableAutoDisplay_trade = 'Display inventory when trading items'
L.EnableAutoDisplay_craft = 'Display inventory when crafting'
L.EnableAutoDisplay_mail = 'Display inventory when checking a mailbox'
L.EnableAutoDisplay_guildbank = 'Display inventory when visiting the guild bank'
L.EnableAutoDisplay_player = 'Display inventory when opening the player frame'
L.EnableAutoDisplay_combat = 'Close inventory when entering combat'
L.EnableAutoDisplay_vehicle = 'Close inventory when entering a vehicle'
L.EnableAutoDisplay_gems = 'Display inventory when socketing items'

L.DisplaySettings = 'Automatic Display'
L.DisplaySettingsTitle = 'Automatic frame display settings'
L.FrameSettings = 'Frame Settings'
L.FrameSettingsTitle = 'Configuration settings specific to a Bagnon frame'
L.GeneralSettings = 'General Settings'
L.GeneralSettingsTitle = 'General configuration settings for Bagnon'
L.EnableBlizzardBagPassThrough = 'Display Blizzard frames for disabled bags'
L.EnableBagBreak = 'Enable bag break layout'
L.ColorSettings = 'Color Settings'
L.ColorSettingsTitle = 'Item slot coloring settings'
L.ItemHighlightOpacity = 'Item highlight brightness'
L.EnableFlashFind = 'Enable flash find'
L.EnableTipCount = 'Enable tooltip item count'
L.EnableFading = 'Enable frame fading'
L.AllowDisableBags = 'Disable bags when clicked'

L.ItemSlotColor_normal = 'Normal color'
L.ItemSlotColor_leather = 'Leatherworking bag color'
L.ItemSlotColor_inscri = 'Inscription bag color'
L.ItemSlotColor_herb = 'Herbalism bag color'
L.ItemSlotColor_enchant = 'Enchanting bag color'
L.ItemSlotColor_engineer = 'Engineering bag color'
L.ItemSlotColor_gem = 'Gem bag color'
L.ItemSlotColor_mine = 'Mining bag color'
L.ItemSlotColor_tackle = 'Tackle box color'
L.ItemSlotColor_cooking = 'Refrigerator color'
L.ItemSlotColor_reagent = 'Reagent bank color'