--[[
	Bagnon Config Localization: Italian
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'itIT', true)

L.Columns = 'Colonne'
L.Scale = 'Scalatura'
L.Spacing = 'Spaziatura'
L.Opacity = 'Opacità'
L.FrameColor = 'Colore Riquadro'
L.FrameBorderColor = 'Colore Bordo Riquadro'
L.Frame = 'Riquadro'
L.LockFramePositions = 'Blocca posizione Riquadro'
L.ShowEmptyItemSlotBackground = 'Mostra uno sfondo per gli scomparti vuoti'
L.HighlightItemsByQuality = 'Evidenzia oggetti per qualità' 
L.HighlightUnusableItems = 'Evidenzia Oggetti Non Usabili'
L.HighlightQuestItems = 'Evidenzia Oggetti di Missione'
L.ReverseSlotOrdering = 'Inverti Ordinamento Scomparti Sacche'
L.ColorItemSlotsByBagType = 'Colora gli scomparti vuoti per il tipo di sacca'
L.FrameLayer = 'Livello'
L.EnableBagFrame = 'Abilita Riquadro Sacche'
L.EnableMoneyFrame = 'Abilita Riquadro Denaro'
L.EnableDBOFrame = 'Abilita Riquadro Databroker'
L.EnableSearchToggle = 'Abilita la Ricerca'
L.EnableOptionsToggle = 'Abilita le Opzioni'
L.EnableFrame_inventory = 'Abilita Riquadro Inventario'
L.EnableFrame_bank = 'Abilita Riquadro Banca'
L.SettingRequiresRestart = 'Queste impostazioni avranno effetto la prossima volta che effettuerai il login'

L.EnableAutoDisplay_bank = 'Mostra Inventario quando si visita la banca'
L.EnableAutoDisplay_ah = "Mostra Inventario quando si visita la Casa d'Aste"
L.EnableAutoDisplay_vendor = "Chiudi l'Inventario quando ci si allontana da un mercante"
L.EnableAutoDisplay_trade = 'Mostra Inventario quando si scambiano oggetti'
L.EnableAutoDisplay_craft = 'Mostra Inventario quando si apre una Professione di Creazione'
L.EnableAutoDisplay_mail = 'Mostra Inventario quando si controlla la Cassetta della Posta'
L.EnableAutoDisplay_guildbank = 'Mostra Inventario quando si visita la Banca di Gilda'
L.EnableAutoDisplay_player = 'Mostra Inventario quando si apre il riquadro del personaggio'
L.EnableAutoDisplay_combat = 'Chiudi Inventario quando si entra in combattimento'
L.EnableAutoDisplay_vehicle = 'Chiudi Inventario quando si entra in un veicolo'
L.EnableAutoDisplay_gems = 'Mostra Inventario quando si riempiono gli incavi'

L.DisplaySettings = 'Visualizzazione Automatica'
L.DisplaySettingsTitle = 'Impostazioni Visualizzazioni Riquadro Automatico'
L.FrameSettings = 'Impostazioni Riquadro'
L.FrameSettingsTitle = 'Configurazione impostazioni specifiche per un riquadro di Bagnon'
L.GeneralSettings = 'Impostazioni Generali'
L.GeneralSettingsTitle = 'Impostazioni configurazione generale per Bagnon'
L.EnableBlizzardBagPassThrough = 'Mostra riquadro Blizzard per Sacche disabilitate'
L.EnableBagBreak = 'Abilita Spaziatura tra Sacche'
L.ColorSettings = 'Impostazioni Colore'
L.ColorSettingsTitle = 'Impostazioni Colorazione Scomparto Oggetto'
L.ItemHighlightOpacity = 'Brillantezza Oggetto Evidenziato'
L.EnableFlashFind = 'Abilita Lampeggio alla Ricerca'
L.EnableTipCount = 'Abilita conteggio nel tooltip'
L.EnableFading = 'Abilita Scomparsa Progressiva del Riquadro'
L.AllowDisableBags = 'Disabilita Sacche quando clicchi'

L.ItemSlotColor_normal = 'Colore Scomparto Normale'
L.ItemSlotColor_leather = 'Colore Scomparto Sacca da Conciatore'
L.ItemSlotColor_inscri = 'Colore Scomparto Sacca da Runografo'
L.ItemSlotColor_herb = 'Colore Scomparto Sacca da Erbalista'
L.ItemSlotColor_enchant = 'Colore Scomparto Sacca da Incantatore'
L.ItemSlotColor_engineer = 'Colore Scomparto Sacca da Ingegnere'
L.ItemSlotColor_gem = 'Colore Scomparto Sacca da Orafo'
L.ItemSlotColor_mine = 'Colore Scomparto Sacca da Minatore'
L.ItemSlotColor_tackle = 'Colore Scomparto Cassetta del Gran Pescatore'
L.ItemSlotColor_cooking = 'Colore Scomparto Frigorifero'