--[[
	Bagnon Config Localization: Brasilian Portuguese
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'ptBR')
if not L then return end

L.Columns = 'Colunas'
L.Scale = 'Escala'
L.Spacing = 'Espaçamento'
L.Opacity = 'Transparência'
L.FrameColor = 'Cor de Fundo'
L.FrameBorderColor = 'Cor do Bordo'
L.Frame = 'Janela'
L.LockFramePositions = 'Bloquear posição das janelas'
L.ShowEmptyItemSlotBackground = 'Mostrar fundo em espaços para itens vazios'
L.HighlightItemsByQuality = 'Realçar itens por qualidade' 
L.HighlightUnusableItems = 'Realçar itens inutilizáveis'
L.HighlightQuestItems = 'Realçar itens de missão'
L.ReverseSlotOrdering = 'Inverter a ordem dos espaços para itens'
L.ColorItemSlotsByBagType = 'Colorir os espaços por tipo de saco'
L.FrameLayer = 'Camada'
L.EnableBagFrame = 'Ativar lista de sacos'
L.EnableMoneyFrame = 'Ativar dinheiro'
L.EnableDBOFrame = 'Ativar DataBroker'
L.EnableSearchToggle = 'Ativar botão da pesquisa'
L.EnableOptionsToggle = 'Ativar botão da configração'
L.EnableFrame_inventory = 'Ativar a janela da mochila'
L.EnableFrame_bank = 'Ativar a janela do banco'
L.SettingRequiresRestart = 'Esta definição só terá efeito da próxima vez que entrar no jogo'

L.EnableAutoDisplay_bank = 'Mostrar mochila quando visitar o banco'
L.EnableAutoDisplay_ah = 'Mostrar mochila quando visitar um leiloeiro'
L.EnableAutoDisplay_vendor = 'Fechar mochila quando abandonar um vendedor'
L.EnableAutoDisplay_trade = 'Mostrar mochila quando trocar itens'
L.EnableAutoDisplay_craft = 'Mostrar mochila quando abrir janela de profissão'
L.EnableAutoDisplay_mail = 'Mostrar mochila quando visitar uma caixa de correio'
L.EnableAutoDisplay_guildbank = 'Mostrar mochila quando visitar banco da guilda'
L.EnableAutoDisplay_player = 'Mostrar mochila quando abrir janela da personagem'
L.EnableAutoDisplay_combat = 'Fechar mochila quando entrar em combate'
L.EnableAutoDisplay_vehicle = 'Fechar mochila quando entrar num veículo'

L.DisplaySettings = 'Exibição Automática'
L.DisplaySettingsTitle = 'Pereferências de exibição automática'
L.FrameSettings = 'Preferências de Janela'
L.FrameSettingsTitle = 'Configuração específica para uma janela de Bagnon'
L.GeneralSettings = 'Preferências Gerais'
L.GeneralSettingsTitle = 'Configuração geral de Bagnon'
L.EnableBlizzardBagPassThrough = 'Mostrar janelas da Blizzard para sacos desligados'
L.EnableBagBreak = 'Ativar quebras entre os sacos'
L.ColorSettings = 'Preferências de Cor'
L.ColorSettingsTitle = 'Preferências de cor para os compartimentos para itens'
L.ItemHighlightOpacity = 'Quantidade de brilho para realçar'
L.EnableFlashFind = 'Ativar Flash Find'
L.EnableTipCount = 'Ativar contagem de itens nas dicas de interface'

L.ItemSlotColor_normal = 'Cor de espaços normais'
L.ItemSlotColor_leather = 'Cor de espaços para couraria'
L.ItemSlotColor_inscri = 'Cor de espaços para escrivania'
L.ItemSlotColor_herb = 'Cor de espaços para herborismo'
L.ItemSlotColor_enchant = 'Cor de espaços para encantamentos'
L.ItemSlotColor_engineer = 'Cor de espaços para engenharia'
L.ItemSlotColor_gem = 'Cor de espaços para joalheria'
L.ItemSlotColor_mine = 'Cor de espaços para mineração'
L.ItemSlotColor_tackle = 'Cor de espaços para caixas de pesca'