--[[
	Bagnon Config Localization: Russian
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'ruRU')
if not L then return end

L.Columns = 'Колонок'
L.Scale = 'Масштаб'
L.Spacing = 'Промежуток'
L.Opacity = 'Прозрачность'
L.FrameColor = 'Цвет окна'
L.FrameBorderColor = 'Цвет границы окна'
L.Frame = 'Окно'
L.LockFramePositions = 'Закрепить позицию окна'
L.ShowEmptyItemSlotBackground = 'Отображать фон пустых ячеек'
L.HighlightItemsByQuality = 'Подсветка предметов по качеству' 
L.HighlightUnusableItems = 'Подсветка неиспользуемых предметов'
L.HighlightQuestItems = 'Подсветка предметов для задания'
L.ReverseSlotOrdering = 'Обратить порядок ячеек сумкок'
L.ColorItemSlotsByBagType = 'Цвет пустых ячеек по типу сумки'
L.FrameLayer = 'Слой окна'
L.EnableBagFrame = 'Показывать кнопку сумок'
L.EnableMoneyFrame = 'Показывать область денег'
L.EnableDBOFrame = 'Показывать область databroker'
L.EnableSearchToggle = 'Показывать кнопку поиска'
L.EnableOptionsToggle = 'Показывать кнопку настроек'
L.EnableFrame_inventory = 'Включить область инвентаря'
L.EnableFrame_bank = 'Включить область банка'
L.SettingRequiresRestart = 'Настройки вступят в силу после следующего входа в игру или перезагрузки интерфейса,\nКомандой: /reloadui.'

L.EnableAutoDisplay_bank = 'Показать инвентарь при посещении банка.'
L.EnableAutoDisplay_ah = 'Показать инвентарь при посещении аукциона.'
L.EnableAutoDisplay_vendor = 'Показать инвентарь при посещении торговца.'
L.EnableAutoDisplay_trade = 'Показать инвентарь при обмене предметами.'
L.EnableAutoDisplay_craft = 'Показать инвентарь во время изготовления.'
L.EnableAutoDisplay_mail = 'Показать инвентарь во время просмотра почты.'
L.EnableAutoDisplay_guildbank = 'Показать инвентарь при посещении банка гильдии.'
L.EnableAutoDisplay_player = 'Показать инвентарь при открытии окна игрока.'
L.EnableAutoDisplay_combat = 'Закрыть инвентарь в режиме боя'
L.EnableAutoDisplay_vehicle = 'Закрыть инвентарь при посадке на средство передвижения'
L.EnableAutoDisplay_gems = 'Показать инвентарь при вставке камней в предметы'

L.DisplaySettings = 'Автопоявление'
L.DisplaySettingsTitle = 'Настройки автоматического открытия окна.'
L.FrameSettings = 'Настройки окна'
L.FrameSettingsTitle = 'Настройка окна Bagnon.'
L.GeneralSettings = 'Основные настройки'
L.GeneralSettingsTitle = 'Основные настройки Bagnon.'
L.EnableBlizzardBagPassThrough = 'Открывать стандартные окна для отключенных сумок.'
L.EnableBagBreak = 'Включить прерывание размещения сумок'
L.ColorSettings = 'Настройка окраски'
L.ColorSettingsTitle = 'Настройки окраски ячеек предметов'
L.ItemHighlightOpacity = 'Яркость подсветки предметов'
L.EnableFlashFind = 'Включить вспышку поиска'
L.EnableTipCount = 'Включить в подсказки предметов их количество'
L.EnableFading = 'Включить затухание окна'
L.AllowDisableBags = 'Отключить сумки при клике на них'

L.ItemSlotColor_normal = 'Обычный цвет ячейки сумки'
L.ItemSlotColor_leather = 'Цвет ячейки сумки кожевника'
L.ItemSlotColor_inscri = 'Цвет ячейки сумки начертателя'
L.ItemSlotColor_herb = 'Цвет ячейки сумки травника'
L.ItemSlotColor_enchant = 'Цвет ячейки сумки зачарователя'
L.ItemSlotColor_engineer = 'Цвет ячейки сумки инженера'
L.ItemSlotColor_gem = 'Цвет ячейки сумки ювелира'
L.ItemSlotColor_mine = 'Цвет ячейки сумки шахтера'
L.ItemSlotColor_tackle = 'Цвет ячейки рюкзака'

L.ItemSlotColor_ammo = 'Окраска ячейки боеприпасов'
L.ItemSlotColor_trade = 'Окраска ячейки товаров'
L.ItemSlotColor_shard = 'Окраска ячейки камней'