local L = LibStub("AceLocale-3.0"):NewLocale("PetJournalEnhanced", "ptBR")
if not L then return end

L["Ability Type"] = "Tipo de habilidade" -- Needs review
L["Available"] = "Disponível" -- Needs review
L["Balanced"] = "Balanço" -- Needs review
L["Breed"] = "Raça" -- Needs review
L["Can Battle"] = "Pode ir a Batalha" -- Needs review
L["Can't Battle"] = "Nao pode batalhar" -- Needs review
L["Can Trade"] = "Pode Negociar" -- Needs review
L["Can't Trade"] = "Não pode ser negociado" -- Needs review
L["Color pet borders"] = "Cor da borda dos pets" -- Needs review
L["Color pet names"] = "Cor do nome dos pets" -- Needs review
L["Continued"] = "Contínuo" -- Needs review
L["Display pet breed"] = "Mostra a raça do Pet" -- Needs review
L["Display predicted pet stats"] = "Mostra uma previa das estatísticas do Pet" -- Needs review
L["Filter pets by current zone"] = "Filtrar por região" -- Needs review
L["Highest Stat"] = "Maior Stat" -- Needs review
L["Instances"] = "Instâncias" -- Needs review
L["PET_THEORY_WARNING"] = "PET_THEORY_WARNING" -- Needs review
L["Powerful"] = "Força/Poder" -- Needs review
L["Quantity"] = "Quantidade" -- Needs review
L["Reset Filters"] = "Ressetar Filtros" -- Needs review
L["Reset player hidden pets"] = "Resseta pets ocultos" -- Needs review
L["Resilient"] = "Resiliência" -- Needs review
L["Show pets specialization"] = "Mostra a especialização do Pet" -- Needs review
L["Show player hidden pets"] = "Mostra os pets ocultos" -- Needs review
L["Show unique pet count"] = "Mostra quantidade de pet unico" -- Needs review
L["Sort Ascending"] = "Classifica por modo Ascendente" -- Needs review
L["Sort Descending"] = "Classifica por modo Descendente" -- Needs review
L["Sort Direction:"] = "Mode de Classificação" -- Needs review
L["Sort favorites to the top"] = "Classifica Preferidos primeiro" -- Needs review
L["Sorting"] = "Classificando" -- Needs review
L["Sort Order:"] = "Classifica por ordem" -- Needs review
L["Unique Pets"] = "Pets Unicos" -- Needs review
L["Unknown Zone"] = "Região desconhecida" -- Needs review
L["Zones"] = "Regiões" -- Needs review