-- This file is automagically generated.
-- Please visit http://www.wowace.com/projects/range-display/localization/
-- if you wish to help with the translation.

local L = LibStub("AceLocale-3.0"):NewLocale("RangeDisplay_Options", "zhCN")
if not L then return end
L["RangeDisplay"] = "距离提示"
L["Anchor to Mouse"] = "锚点定位到鼠标"
L["Auto hide"] = "自动隐藏"
L["Background Color"] = "背景颜色"
L["Background Options"] = "背景选项"
L["Background Texture"] = "背景材质"
L["Background Tile Size"] = "背景网格尺寸"
L["Border Color"] = "边框颜色"
L["Border Texture"] = "边框材质"
L["Border Thickness"] = "边框厚度"
L["Close range section"] = "近距离项"
L["Color"] = "颜色"
L["Copy section settings to other units"] = "复制分段设置到其他单位"
L["Default section"] = "默认项"
L["Enabled"] = "开启"
L["Enable this color section"] = "开启此色彩项目"
L["Enemy only"] = "仅敌对"
L["Enemy only sound"] = "仅敌对音效"
L["Font"] = "字体"
L["Font outline"] = "字体描边"
L["Font size"] = "字号"
L["Frame's background color"] = "框架背景颜色"
L["Frame's border color"] = "框架边框颜色"
L["Frame strata"] = "框架显示层面"
L["Height"] = "高度"
L["Hide the background if the range display is not active"] = "如果距离显示没有被激活则隐藏背景"
L["High"] = "最高层"
L["Locked"] = "锁定"
L["Lock/Unlock display frame"] = "锁定或解锁显示框"
L["Long range section"] = "远距离项"
L["Low"] = "最低层"
L["Reverse"] = "反向"
L["Medium"] = "中间层"
L["Medium range section"] = "中距离项"
L["Mute"] = "静音"
L["None"] = "无"
L["Normal"] = "正常"
L["Out of range section"] = "超出距离项"
L["Over limit display"] = "超出距离显示"
L["Play a sound when entering this range"] = "当进入这个距离范围时播放一个音效"
L["Range limit"] = "距离限制"
L["Ranges above this are not reported"] = "不提醒超出此数值的距离"
L["Short range section"] = "短距离项"
L["Show/Hide display if the target is further than range limit"] = "在目标超出距离时显示/隐藏距离框体"
L["Show range for enemy targets only"] = "仅显示敌对目标的距离"
L["Show max-min instead of min-max"] = "显示'最大距离-最小距离'，而不是'最小-最大'"
L["Strata"] = "层级"
L["Text"] = "文字"
L["Texture to use for the frame's background"] = "框架背景的材质"
L["Texture to use for the frame's border"] = "框架边框的材质"
L["The size used to tile the background texture"] = "网格背景尺寸"
L["The thickness of the border"] = "设置边框厚度"
L["Thick"] = "加粗"
L["Tile Background"] = "网格背景"
L["Tile the background texture"] = "网格背景材质"
L["Toggle sound"] = "开启/关闭音效"
L["Use Section Colors"] = "使用分段颜色"
L["Use warning sound for enemy targets only"] = "仅当目标是敌对时播放报警音效"
L["Warning Sound"] = "报警音效"
L["Warning Sound Name"] = "报警音效名字"
L["Width"] = "宽度"

