--[=[
HealersHaveToDie World of Warcraft Add-on
Copyright (c) 2009-2013 by John Wellesz (Archarodim@teaser.fr)
All rights reserved

Version 2.3-1-g25c34e5

This is a very simple and light add-on that rings when you hover or target a
unit of the opposite faction who healed someone during the last 60 seconds (can
be configured).
Now you can spot those nasty healers instantly and help them to accomplish their destiny!

This add-on uses the Ace3 framework.

type /hhtd to get a list of existing options.

-----
    Localization.lua
-----


--]=]


--[=[
--                      YOUR ATTENTION PLEASE
--
--         !!!!!!! TRANSLATORS TRANSLATORS TRANSLATORS !!!!!!!
--
--    Thank you very much for your interest in translating Healers Have To Die.
--    Do not edit this file. Use the localization interface available at the following address:
--
--      ##########################################################################
--      #  http://wow.curseforge.com/projects/healers-have-to-die/localization/  #
--      ##########################################################################
--
--    Your translations made using this interface will be automatically included in the next release.
--
--]=]


do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "enUS", true, true);

    if L then
        L["ACTIVE"] = "Active!"
L["Announcer"] = "Announcer"
L["Announcer_DESC"] = "This module allows you to manage chat and sound alerts"
L["AUTO_RAID_PARTY_INSTANCE"] = "Auto: Raid/Party/Instance"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "The announce to raid messages are not configured. Type /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "It's too soon (see the announce throttle setting)."
L["CHAT_POST_NO_HEALERS"] = "No healers on either sides :/ (yet)"
L["DESCRIPTION"] = "Spot those bloody healers instantly and help them accomplish their destiny! (PVP and PVE)"
L["DISABLED"] = [=[hhtd has been disabled!
Type '/hhtd on' to re-enable it.]=]
L["ENABLED"] = "enabled! Type /HHTDG to open its option panel"
L["HEALER_UNDER_ATTACK"] = "Healer friend %s is being attacked by %s"
L["HUMAN"] = "Human"
L["IDLE"] = "Idle"
L["INSTANCE_CHAT"] = "Instance chat"
L["IS_A_HEALER"] = "%s is a healer!"
L["LOG_ACTIVE"] = "Active!"
L["LOG_BELOW_THRESHOLD"] = " (below threshold)"
L["LOG_IDLE"] = "Idle"
L["NO_DATA"] = "No data"
L["NPC"] = "NPC"
L["NPH"] = "Name Plate Hooker"
L["NPH_DESC"] = "This module adds a red cross to enemy healers' name plates"
L["OPT_ANNOUNCE"] = "Show messages"
L["OPT_ANNOUNCE_DESC"] = "HHTD will display messages when you target or mouse-over an enemy healer."
L["OPT_CLEAR_LOGS"] = "Clear logs"
L["OPT_CORE_OPTIONS"] = "Core options"
L["OPT_DEBUG"] = "debugging logs"
L["OPT_DEBUG_DESC"] = "Enables / disables debugging"
L["OPT_DEBUGLEVEL"] = "debugging level"
L["OPT_DEBUGLEVEL_DESC"] = "debug level: 1=all, 2=warnings, 3=errors"
L["OPT_ENABLE_GEHR"] = "Enable Graphical Reporter"
L["OPT_ENABLE_GEHR_DESC"] = "Displays a graphical list of detected enemy healers with various features"
L["OPT_HEALER_FORGET_TIMER"] = "Healer Forget Timer"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "Set the Healer Forget Timer (the time in seconds an enemy will remain considered has a healer)"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "Heal amount (|cff00dd00%u|r) threshold"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Healers won't be detected until they reach this cumulative amount of healing based on a percentage of your own maximum health."
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "Protect friendly healers"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "Display an alert when a nearby friendly healers is attacked"
L["OPT_LOG"] = "Logging"
L["OPT_LOG_DESC"] = "Enables logging and adds a new 'Logs' tab to HHTD's option panel"
L["OPT_LOGS"] = "Logs"
L["OPT_LOGS_DESC"] = "Display HHTD detected healers and statistics"
L["OPT_MODULES"] = "Modules"
L["OPT_NPH_MARKER_SCALE"] = "Markers' scaling"
L["OPT_NPH_MARKER_SCALE_DESC"] = "Change markers' size"
L["OPT_NPH_MARKER_SETTINGS"] = "Markers' settings"
L["OPT_NPH_MARKER_X_OFFSET"] = "Horizontal offset"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "Move markers horizontally"
L["OPT_NPH_MARKER_Y_OFFSET"] = "Vertical offset"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "Move markers vertically"
L["OPT_NPH_WARNING1"] = [=[WARNING: Enemies' name-plates are currently disabled. HHTD cannot add its red cross symbol.
You can enable name-plates display through the WoW UI's options or by using the assigned key-stroke.]=]
L["OPT_NPH_WARNING2"] = [=[WARNING: Allies' name-plates are currently disabled. HHTD cannot add its healer symbol.
You can enable name-plates display through the WoW UI's options or by using the assigned key-stroke.]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "Disables HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "Enables HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "Post channel"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "Decide where your announce will be posted"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000IMPORTANT:|r Type |cff40ff40/hhtdp|r or bind a key to announce friendly healers to protect and enemy healers to focus.

(see World of Warcraft escape menu binding interface to bind a key)
]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "Chat announces"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "Enable announce to raid features."
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "Humans only"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "Do not include NPCs in the announce."
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "Text for enemy healers"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[Type a message inciting your team to focus enemy healers.

You must use the [HEALERS] keyword somewhere which will be automatically replaced by the names of the currently active healers.]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "There is one message for friends and one for foes, they cannot be the same."
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "Your message is too short!"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "The [HEALERS] keyword is missing!"
L["OPT_POST_ANNOUNCE_NUMBER"] = "Healers number"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "Set how many healers to include in each announce."
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "There is something wrong with one of the announce text."
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "Text for friendly healers"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[Type a message inciting your team to protect their healers.

You must use the [HEALERS] keyword somewhere which will be automatically replaced by the names of the currently active healers.]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "Announce to raid settings"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "Announce throttle"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "Set the minimum time in seconds between each possible announce."
L["OPT_PVE"] = "Enable for PVE"
L["OPT_PVE_DESC"] = "HHTD will also work for NPCs."
L["OPT_PVPHEALERSSPECSONLY"] = "Specialized players only"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "Only detect players specialized in healing. (this disables minimum heal amount filter for PVP)"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "Set friendly healers role"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "Will automatically set the raid HEALER role to friendly healers upon detection (if possible)"
L["OPT_SOUNDS"] = "Sound alerts"
L["OPT_SOUNDS_DESC"] = "HHTD will play a specific sound when you hover or target an enemy healer"
L["OPT_STRICTGUIDPVE"] = "Accurate PVE detection"
L["OPT_STRICTGUIDPVE_DESC"] = "When several NPCs share the same name, HHTD will only add a cross over those who actually healed instead of adding a cross to all of them. Note that most of the time, you'll need to target or mouse-over the unit for the cross to appear."
L["OPT_TESTONTARGET"] = "Test HHTD's behavior on current target"
L["OPT_TESTONTARGET_DESC"] = "Will mark your current target as a healer so you can test what happens."
L["OPT_TESTONTARGET_ENOTARGET"] = "You need to target something"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "Use minimum heal amount filter"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "Healers will have to heal for a specified amount before being tagged as such."
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "Display version and release date"
L["PARTY"] = "Party"
L["RELEASE_DATE"] = "Release Date:"
L["SAY"] = "Say"
L["VERSION"] = "version:"
L["YELL"] = "Yell"
L["YOU_GOT_HER"] = "You got %sher|r!"
L["YOU_GOT_HIM"] = "You got %shim|r!"
L["YOU_GOT_IT"] = "You got %sit|r!"
    end
end

do
local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "zhCN");

if L then
L["ACTIVE"] = "激活！"  
L["Announcer"] = "通报"
L["Announcer_DESC"] = "此模管理聊天和音效警报"
L["AUTO_RAID_PARTY_INSTANCE"] = "自动：团队/小队/副本"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "未配置团队通报信息。输入 /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "太快了（查看通报阈值设置）。"
L["CHAT_POST_NO_HEALERS"] = "哇靠，当前双方都没有治疗职业！:D（暂时的）"
L["DESCRIPTION"] = "立刻曝光那些该死的治疗并帮助他们走完自己的使命！（PvP 和 PvE）"
L["DISABLED"] = [=[hhtd 已被禁用！
输入“/hhtd on”来重新启用。]=]
L["ENABLED"] = "已启用！输入 /HHTDG 打开选项列表"
L["HEALER_UNDER_ATTACK"] = "友方治疗职业%s被%s攻击"
L["HUMAN"] = "人类"
L["IDLE"] = "发呆"
L["INSTANCE_CHAT"] = "副本消息"
L["IS_A_HEALER"] = "%s是治疗职业！"
L["LOG_ACTIVE"] = "激活！"
L["LOG_BELOW_THRESHOLD"] = "（低于阈值）"
L["LOG_IDLE"] = "发呆"
L["NO_DATA"] = "无数据"
L["NPC"] = "NPC"
L["NPH"] = "姓名版挂钩"
L["NPH_DESC"] = "此模块在敌对治疗姓名板上添加一个红十字"
L["OPT_ANNOUNCE"] = "显示信息"
L["OPT_ANNOUNCE_DESC"] = "当你的目标或是鼠标指向一个敌对治疗者时 HHTD 将显示信息。"
L["OPT_CLEAR_LOGS"] = "清除记录"
L["OPT_CORE_OPTIONS"] = "核心选项"
L["OPT_DEBUG"] = "除错"
L["OPT_DEBUG_DESC"] = "启用/禁用除错"
L["OPT_DEBUGLEVEL"] = "除错等级"
L["OPT_DEBUGLEVEL_DESC"] = "除错等级：1=全部，2=警报，3=错误"
L["OPT_ENABLE_GEHR"] = "启用图形报告"
L["OPT_ENABLE_GEHR_DESC"] = "显示敌对治疗多功能图形列表"
L["OPT_HEALER_FORGET_TIMER"] = "治疗职业遗忘计时器"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "设置治疗职业遗忘计时器（用于在一定时间内将一个敌人标记为治疗职业）"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "治疗值（|cff00dd00%u|r）阈值"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治疗职业当他们达到累积的治疗量根据自己的最大生命值的百分比之前不会被检测到。"
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "保护友方治疗职业"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "当附近的友方治疗职业被攻击时显示警报"
L["OPT_LOG"] = "正在记录"
L["OPT_LOG_DESC"] = "启用记录并添加一个新的“记录”标签到 HHTD 选项面板"
L["OPT_LOGS"] = "记录"
L["OPT_LOGS_DESC"] = "显示 HHTD 检测到的治疗和数据"
L["OPT_MODULES"] = "模块"
L["OPT_NPH_MARKER_SCALE"] = "标记缩放"
L["OPT_NPH_MARKER_SCALE_DESC"] = "更改标记尺寸"
L["OPT_NPH_MARKER_SETTINGS"] = "标记配置"
L["OPT_NPH_MARKER_X_OFFSET"] = "水平偏移量"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "水平移动标记"
L["OPT_NPH_MARKER_Y_OFFSET"] = "垂直偏移量"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "垂直移动标记"
L["OPT_NPH_WARNING1"] = [=[提示：敌方姓名版未被启用。HHTD 不能添加治疗标记。
可以通过游戏内界面选项开启姓名版显示或使用快捷键。]=]
L["OPT_NPH_WARNING2"] = [=[提示：友方姓名版未被启用。HHTD 不能添加治疗标记。
可以通过游戏内界面选项开启姓名版显示或使用快捷键。]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "禁用 HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "启用 HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "广播频道"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "选择广播通报的频道"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000主要：|r输入 |cff40ff40/hhtdp|r 或绑定按键通报保护友方治疗职业和特殊照顾敌方治疗职业。

（魔兽世界 ESC 菜单绑定界面设置按键绑定）]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "聊天通报"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "启用通报到团队功能。"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "只对人类"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "通报中不包含 NPC。"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "敌对治疗文本"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[输入一个消息鼓动你的队伍集中火力攻击敌方治疗职业。

必须使用 [HEALERS] 键值将被自动替换为当前激活治疗职业。]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "这有一个友好和敌对的信息，他们不能一样。"
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "你的信息太少了！"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "[HEALERS] 键值缺失！"
L["OPT_POST_ANNOUNCE_NUMBER"] = "治疗数量"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "设置每条通报上的治疗数量。"
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "通报文本里有什么东西出错。"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "友方治疗文本"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[输入一个信息鼓动团队保护他们的治疗职业。

必须使用 [HEALERS] 键值将被自动替换为当激活的治疗职业。]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "通报到团队设置"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "通报阈值"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "设置每条可能通报的最小时间间隔。"
L["OPT_PVE"] = "PvE 启用"
L["OPT_PVE_DESC"] = "HHTD 同样作用于 NPC。"
L["OPT_PVPHEALERSSPECSONLY"] = "治疗职业特定检测"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "只特定治疗玩家。（此项禁用 PvP 最小治疗量）"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "设置友方治疗职业角色"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "（如可能）自动设置检测团队治疗角色到友方治疗"
L["OPT_SOUNDS"] = "音效警报"
L["OPT_SOUNDS_DESC"] = "当你鼠标悬停或目标到一个敌对治疗时 HHTD 播放特定的音效。"
L["OPT_STRICTGUIDPVE"] = "精确 PvE 检测"
L["OPT_STRICTGUIDPVE_DESC"] = "当多个 NPC 共享相同的名称，HHTD 只会增加一个十字而不是全部。请注意，在十字出现之前大部分的时间需要切换目标或鼠标悬停在单位。"
L["OPT_TESTONTARGET"] = "在当前目标测试 HHTD 状态"
L["OPT_TESTONTARGET_DESC"] = "将标记当前目标为治疗者来测试发生了什么。"
L["OPT_TESTONTARGET_ENOTARGET"] = "需要一个目标"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "使用最少治疗值过滤"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治疗职业将有指定治疗数值前被标记等。"
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "显示版本和发布日期"
L["PARTY"] = "小队"
L["RELEASE_DATE"] = "发布日期："
L["SAY"] = "说"
L["VERSION"] = "版本："
L["YELL"] = "大喊"
L["YOU_GOT_HER"] = "你抓到%s她了|r！"
L["YOU_GOT_HIM"] = "你抓到%s他了|r！"
L["YOU_GOT_IT"] = "你抓到%s它了|r！"

    end
end

do
    local L = LibStub("AceLocale-3.0"):NewLocale("HealersHaveToDie", "zhTW");

    if L then
        L["ACTIVE"] = "啟動！"
L["Announcer"] = "通報"
L["Announcer_DESC"] = "此模組管理聊天和音效警報"
L["AUTO_RAID_PARTY_INSTANCE"] = "自動:團隊/隊伍/副本"
L["CHAT_POST_ANNOUNCE_FEATURE_NOT_CONFIGURED"] = "未配置團隊通報訊息。輸入 /HHTDG"
L["CHAT_POST_ANNOUNCE_TOO_SOON_WAIT"] = "太快了（查看通報閾值設置）。"
L["CHAT_POST_NO_HEALERS"] = "哇靠，當前雙方都沒有治療！"
L["DESCRIPTION"] = "立刻曝光那些該死的治療並幫助他們走完自己的使命！（PvP 和 PvE）"
L["DISABLED"] = [=[hhtd 已被禁用！
輸入“/hhtd on”來重新啟用。]=]
L["ENABLED"] = "已啟用！輸入 /HHTDG 開啟選項面板"
L["HEALER_UNDER_ATTACK"] = "友方治療者%s被%s攻擊"
L["HUMAN"] = "人類"
L["IDLE"] = "呆滯"
L["INSTANCE_CHAT"] = "副本頻道"
L["IS_A_HEALER"] = "%s是治療者！"
L["LOG_ACTIVE"] = "啟動！"
L["LOG_BELOW_THRESHOLD"] = "（低於閾值）"
L["LOG_IDLE"] = "呆滯"
L["NO_DATA"] = "無數據"
L["NPC"] = "NPC"
L["NPH"] = "姓名版掛鉤"
L["NPH_DESC"] = "此模組在敵方治療者姓名板上添加一個紅十字"
L["OPT_ANNOUNCE"] = "顯示訊息"
L["OPT_ANNOUNCE_DESC"] = "當你的目標或是鼠標指向一個敵對治療者時 HHTD 將顯示訊息。"
L["OPT_CLEAR_LOGS"] = "清除記錄"
L["OPT_CORE_OPTIONS"] = "核心選項"
L["OPT_DEBUG"] = "除錯"
L["OPT_DEBUG_DESC"] = "啟用/禁用除錯"
L["OPT_DEBUGLEVEL"] = "除錯等級"
L["OPT_DEBUGLEVEL_DESC"] = "除錯等級：1=全部，2 =警報，3 =錯誤"
L["OPT_ENABLE_GEHR"] = "啟用圖形報告"
L["OPT_ENABLE_GEHR_DESC"] = "顯示敵對治療多功能圖形列表"
L["OPT_HEALER_FORGET_TIMER"] = "治療忽略計時器"
L["OPT_HEALER_FORGET_TIMER_DESC"] = "設置治療忽略計時器（在幾秒鐘的時間敵人仍會被認為有個治療者）"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT"] = "治療值（|cff00dd00%u|r）閾值"
L["OPT_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治療者不會被偵測到直到他們累積一定數額的治療量(基於你最大血量的百分比)。"
L["OPT_HEALER_UNDER_ATTACK_ALERTS"] = "保護友方治療者"
L["OPT_HEALER_UNDER_ATTACK_ALERTS_DESC"] = "當附近的友方治療者被攻擊時顯示警報"
L["OPT_LOG"] = "正在記錄"
L["OPT_LOG_DESC"] = "啟用記錄並添加一個新的“記錄”標籤到 HHTD 選項面板"
L["OPT_LOGS"] = "記錄"
L["OPT_LOGS_DESC"] = "顯示 HHTD 檢測到的治療和數據"
L["OPT_MODULES"] = "模塊"
L["OPT_NPH_MARKER_SCALE"] = "標記縮放"
L["OPT_NPH_MARKER_SCALE_DESC"] = "更改標記尺寸"
L["OPT_NPH_MARKER_SETTINGS"] = "標記配置"
L["OPT_NPH_MARKER_X_OFFSET"] = "水平偏移量"
L["OPT_NPH_MARKER_X_OFFSET_DESC"] = "水平移動標記"
L["OPT_NPH_MARKER_Y_OFFSET"] = "垂直偏移量"
L["OPT_NPH_MARKER_Y_OFFSET_DESC"] = "垂直移動標記"
L["OPT_NPH_WARNING1"] = [=[警告：敵方姓名條目前是關閉的，HHTD無法加入紅十字標誌。
你可以在WoW的介面選項裏啟用姓名條顯示，或使用指定的按鍵。]=]
L["OPT_NPH_WARNING2"] = [=[警告：友方姓名條目前是關閉的，HHTD無法加入治療者標誌。
你可以在WoW的介面選項裏啟用姓名條顯示，或使用指定的按鍵。]=]
L["OPT_OFF"] = "off"
L["OPT_OFF_DESC"] = "禁用 HHTD"
L["OPT_ON"] = "on"
L["OPT_ON_DESC"] = "啟用 HHTD"
L["OPT_POST_ANNOUNCE_CHANNEL"] = "廣播頻道"
L["OPT_POST_ANNOUNCE_CHANNEL_DESC"] = "選擇廣播通報的頻道"
L["OPT_POST_ANNOUNCE_DESCRIPTION"] = [=[|cFFFF0000重要:|r 輸入 |cff40ff40/hhtdp|r 或是綁定一個按鍵以通報保護友方治療者與聚焦敵方治療者。
(請看魔獸世界ESC的快捷鍵設定介面以綁定一個按鍵)]=]
L["OPT_POST_ANNOUNCE_ENABLE"] = "聊天通報"
L["OPT_POST_ANNOUNCE_ENABLE_DESC"] = "啟用通報到團隊功能。"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY"] = "只對人類"
L["OPT_POST_ANNOUNCE_HUMAMNS_ONLY_DESC"] = "通報中不包含 NPC。"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE"] = "敵對治療文本"
L["OPT_POST_ANNOUNCE_KILL_MESSAGE_DESC"] = [=[輸入一個訊息以煽動你的團隊聚焦到敵方治療者。
你必須使用 [HEALERS]關鍵字，此字會自動替換為當前敵方治療者的名稱。]=]
L["OPT_POST_ANNOUNCE_MESSAGES_EQUAL"] = "這有一個友好和敵對的訊息，他們不能一樣。"
L["OPT_POST_ANNOUNCE_MESSAGE_TOO_SHORT"] = "你的訊息太少了！"
L["OPT_POST_ANNOUNCE_MISSING_KEYWORD"] = "[治療]鍵值缺失！"
L["OPT_POST_ANNOUNCE_NUMBER"] = "治療數量"
L["OPT_POST_ANNOUNCE_NUMBER_DESC"] = "設置每條通報上的治療數量。"
L["OPT_POST_ANNOUNCE_POST_MESSAGE_ISSUE"] = "通報文本里有什麼東西出錯。"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE"] = "友方治療文本"
L["OPT_POST_ANNOUNCE_PROTECT_MESSAGE_DESC"] = [=[輸入一個訊息調動團隊保護他們的治療。

你必須使用[HEALERS]關鍵字，而此字將被替換為當前啟動的治療者。]=]
L["OPT_POST_ANNOUNCE_SETTINGS"] = "通報到團隊設置"
L["OPT_POST_ANNOUNCE_THROTTLE"] = "通報閾值"
L["OPT_POST_ANNOUNCE_THROTTLE_DESC"] = "設置每條可能通報的最小時間間隔。"
L["OPT_PVE"] = "PvE 啟用"
L["OPT_PVE_DESC"] = "HHTD 同樣作用於 NPC。"
L["OPT_PVPHEALERSSPECSONLY"] = "治療特定檢測"
L["OPT_PVPHEALERSSPECSONLY_DESC"] = "只特定治療玩家。（此項禁用 PvP 最小治療量）"
L["OPT_SET_FRIENDLY_HEALERS_ROLE"] = "設置友方治療者角色"
L["OPT_SET_FRIENDLY_HEALERS_ROLE_DESC"] = "（如可能）自動設置檢測團隊治療職責到友方治療"
L["OPT_SOUNDS"] = "音效警報"
L["OPT_SOUNDS_DESC"] = "當你鼠標懸停或目標到一個敵對治療時 HHTD 播放特定的音效。"
L["OPT_STRICTGUIDPVE"] = "精確 PvE 檢測"
L["OPT_STRICTGUIDPVE_DESC"] = "當幾個NPC共享相同的名稱，HHTD將只會增加一個紅十字在真實的治療者而不是所有人上。請注意大多數時間，你需要指定目標或滑鼠停留一個單位以讓十字顯示。"
L["OPT_TESTONTARGET"] = "在當前目標測試 HHTD 狀態"
L["OPT_TESTONTARGET_DESC"] = "將標記當前目標為治療者來測試發生了什麼。"
L["OPT_TESTONTARGET_ENOTARGET"] = "需要一個目標"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT"] = "使用最少治療值過濾"
L["OPT_USE_HEALER_MINIMUM_HEAL_AMOUNT_DESC"] = "治療者需要治療特定數額的治療量才能被標記。"
L["OPT_VERSION"] = "version"
L["OPT_VERSION_DESC"] = "顯示版本和發佈日期"
L["PARTY"] = "小隊"
L["RELEASE_DATE"] = "發佈日期："
L["SAY"] = "說"
L["VERSION"] = "版本："
L["YELL"] = "大喊"
L["YOU_GOT_HER"] = "你抓到%s她了|r！"
L["YOU_GOT_HIM"] = "你抓到%s他了|r！"
L["YOU_GOT_IT"] = "你抓到%s它了|r！"
    end
end
