local L = LibStub("AceLocale-3.0"):NewLocale("PetJournalEnhanced", "zhTW")
if not L then return end

L["Ability Type"] = "技能類型"
L["Available"] = "可獲得品種"
L["Balanced"] = "平衡"
L["Breed"] = "品種"
L["Can Battle"] = "可對戰"
L["Can't Battle"] = "不可對戰"
L["Can Trade"] = "可交易"
L["Can't Trade"] = "不可交易"
L["Color pet borders"] = "邊框著色"
L["Color pet names"] = "名字著色"
L["Continued"] = "接續"
L["Display pet breed"] = "顯示寵物品種"
L["Display predicted pet stats"] = "顯示寵物預測的屬性"
L["Filter pets by current zone"] = "根據當前區域過濾寵物"
L["Highest Stat"] = "最高的屬性"
L["Instances"] = "副本"
L["PET_THEORY_WARNING"] = "警告:|nPetJournal Enhanced並不相容於Pet Theory。|n請移除PetJournal Enhanced或是Pet Theory其中之一。"
L["Powerful"] = "高攻擊"
L["Quantity"] = "品質"
L["Reset Filters"] = "重置過濾"
L["Reset player hidden pets"] = "重置玩家隱藏寵物"
L["Resilient"] = "高血量"
L["Show pets specialization"] = "顯示專精"
L["Show player hidden pets"] = "顯示玩家隱藏寵物"
L["Show unique pet count"] = "顯示獨特寵物數量"
L["Sort Ascending"] = "正序"
L["Sort Descending"] = "逆序"
L["Sort Direction:"] = "排序方向:"
L["Sort favorites to the top"] = "喜好寵物置頂"
L["Sorting"] = "排序"
L["Sort Order:"] = "排序方式:"
L["Unique Pets"] = "獨特寵物"
L["Unknown Zone"] = "未知區域"
L["Zones"] = "區域"




