local L = LibStub("AceLocale-3.0"):NewLocale("PetJournalEnhanced", "frFR")
if not L then return end

L["Ability Type"] = "Type de capacité" -- Needs review
L["Available"] = "Disponible" -- Needs review
L["Balanced"] = "Équilibré" -- Needs review
L["Breed"] = "Lignée" -- Needs review
L["Can Battle"] = "Peut combattre" -- Needs review
L["Can't Battle"] = "Ne peut combattre" -- Needs review
L["Can Trade"] = "Peut s'échanger" -- Needs review
L["Can't Trade"] = "Ne peut s'échanger" -- Needs review
L["Color pet borders"] = "Colorer la bordure des mascottes" -- Needs review
L["Color pet names"] = "Colorer le nom des mascottes" -- Needs review
L["Continued"] = "Suite" -- Needs review
L["Display pet breed"] = "Afficher la lignée des mascottes" -- Needs review
L["Display predicted pet stats"] = "Afficher les stats prévues" -- Needs review
L["Filter pets by current zone"] = "Filtrer selon la zone actuelle" -- Needs review
L["Highest Stat"] = "Stat la plus haute" -- Needs review
L["Instances"] = "Instances" -- Needs review
L["PET_THEORY_WARNING"] = "Attention :|nPetJournal Enhanced n'est pas compatible avec Pet Theory.|nVeuillez désinstaller l'un des deux." -- Needs review
L["Powerful"] = "Puissant" -- Needs review
L["Quantity"] = "Quantité" -- Needs review
L["Reset Filters"] = "Réinitialiser les filtres" -- Needs review
L["Reset player hidden pets"] = "Réinitialiser les mascottes cachées" -- Needs review
L["Resilient"] = "Résistant" -- Needs review
L["Show pets specialization"] = "Montrer les spécialisations des mascottes" -- Needs review
L["Show player hidden pets"] = "Montrer les mascottes cachées" -- Needs review
L["Show unique pet count"] = "Montrer le nombre de mascottes uniques" -- Needs review
L["Sort Ascending"] = "Tri ascendant" -- Needs review
L["Sort Descending"] = "Tri descendant" -- Needs review
L["Sort Direction:"] = "Sens du tri :" -- Needs review
L["Sort favorites to the top"] = "Mettre les favoris en haut" -- Needs review
L["Sorting"] = "Trier par" -- Needs review
L["Sort Order:"] = "Trier par :" -- Needs review
L["Unique Pets"] = "Mascottes uniques" -- Needs review
L["Unknown Zone"] = "Zone inconnue" -- Needs review
L["Zones"] = "Zones" -- Needs review