if( GetLocale() ~= "esES" ) then return end
local L = {}
L["2D"] = "2D"
L["3D"] = "3D"
L["A"] = "A"
L["Abbreviates unit names above 10 characters, \"Dark Rune Champion\" becomes \"D.R.Champion\" and \"Dark Rune Commoner\" becomes \"D.R.Commoner\"."] = "Abrevia nombres de las unidades de más de 10 carácteres, \"Dark Runa Champion\" se convierte en \"DRChampion\" y \"Dark Runa Commoner\" se convierte en \"DRCommoner\"." -- Needs review
L["Absolute incoming heal value, if 10,000 healing is incoming it will show 10,000."] = "Valor absoluto cura entrante, si la curación es de entrada 10000 se mostrará 10.000." -- Needs review
L["Add"] = "Añade"
L["Add new tag"] = "Añadir nueva etiqueta"
L["Add new text"] = "Añade nuevo texto"
L["Adds a bar indicating how much time is left on your ghoul timer, only used if you do not have a permanent ghoul."] = "Agrega una barra que indica cuánto tiempo queda en el cronómetro de tu demonio, sólo se utiliza si no tiene un demonio permanente." -- Needs review
L["Adds an empty bar that you can put text into as a way of uncluttering other bars."] = "Agrega una barra vacía que se puede poner texto, de forma que despeja otras barras." -- Needs review
L["Adds another mana bar to the player frame when you are in Bear or Cat form showing you how much mana you have."] = "Añade otra barra de maná al marco jugador cuando está en forma de oso o gato mostrando la cantidad de maná que tiene." -- Needs review
L["Adds %s to the list of units to be modified when you change values in this tab."] = "Añade %s a la lista de unidades para ser modificadas cuando cambias el valor en esta pestaña"
L["Add tags"] = "Añade etiquetas"
L["Advanced"] = "Avanzado"
L["AFK"] = "AUS"
L["AFK:%s"] = "AUS:%s"
L["AFK status"] = "Estado AUS"
L["AFK timer"] = "Tiempo AUS"
L["Aggro"] = "Amenaza"
L["Ammo"] = "Munición"
L["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Cantidad de energía que falta, si no hay ninguna falta no se muestra nada. Utiliza un formato corto, -13.850 se muestra como 13.8k, valores por debajo de 10.000 están en este formato." -- Needs review
L["Anchor point"] = "Punto de anclaje"
L["Anchor to"] = "Anclado a"
L["Anchor to another frame"] = "Anclado a otro marco"
L["Anchor to buffs"] = "Anclado a los buffs"
L["Anchor to debuffs"] = "Anclado a los debuff"
L["Aquatic"] = "Acuático"
L["Arena"] = "Arena"
L["Arenas"] = "Arenas"
L["Are you sure you want to delete this filter?"] = "¿Está seguro que desea eliminar este filtro?"
L["Are you sure you want to delete this tag?"] = "¿Está seguro que desea eliminar esta etiqueta?"
L["Are you sure you want to delete this text? All settings for it will be deleted."] = "¿Está seguro que desea eliminar este texto? Todos los ajustes de este serán eliminados" -- Needs review
L["Ascending"] = "Ascendente"
L["Aura border style"] = "Estilo del borde del Aura"
L["Aura Combo Points"] = "Puntos de Combo de Aura" -- Needs review
L["Aura filters"] = "Filtros de Auras"
L["Aura name"] = "Nombre del Aura"
L["Auras"] = "Auras"
L["Aura types to filter"] = "Filtro de tipo de Auras"
L["B"] = "B"
L["Background"] = "Fondo"
L["Background alpha"] = "Trasparencia del fondo"
L["Background/border"] = "Fondo/contorno"
L["Background color"] = "Color del fondo"
L["Bag indicator for master looters."] = "Bolsa indicadora para Maestro despojador" -- Needs review
L["Bars"] = "Barras"
L["Bar spacing"] = "Espacio entre barras" -- Needs review
L["Bar texture"] = "Textura de barras"
L["Battlegrounds"] = "Campos de Batalla"
L["Bear"] = "Oso"
L["BG"] = "CB" -- Needs review
L["BG Pet"] = "Mascota CB" -- Needs review
L["Blacklist"] = "Lista negra"
L["Blacklist filters"] = "Filtro de Lista negra"
L["Blacklists"] = "Listas negras" -- Needs review
L["Blizzard"] = "Blizzard"
L["Border"] = "Contorno"
L["Border alpha"] = "trasparencia contorno "
L["Border color"] = "Color del contorno "
L["Border highlighting"] = "Resaltado contorno "
L["Border thickness"] = "Grosor contorno"
L["Boss"] = "Jefe"
L["Boss units are for only certain fights, such as Blood Princes or the Gunship battle, you will not see them for every boss fight."] = "Unidades de Jefes son sólo para ciertas luchas, como los Princesa Sangrienta o de la batalla Gunship, no los vera para cada lucha del jefes."
L["Both"] = "Ambos"
L["Bottom"] = "Abajo"
L["Bottom Center"] = "Abajo centro"
L["Bottom Left"] = "Abajo izquierda"
L["Bottom Right"] = "Abajo derecha"
L["Buffs"] = "Buffs"
L["C"] = "C"
L["Cast"] = "Lanzar" -- Needs review
L["Cast bar"] = "Barra de lanzar" -- Needs review
L["Cast icon"] = "Icono de lanzar" -- Needs review
L["Casting"] = "Lanzando" -- Needs review
L["Cast interrupted"] = "Lanzar Interrumpido" -- Needs review
L["Cast name"] = "Nombre de Hechizo" -- Needs review
L["Cast time"] = "Tiempo lanzar" -- Needs review
L["Cast uninterruptible"] = "Lanzar ininterrumpible" -- Needs review
L["Cat"] = "Gato"
L["Category"] = "Categoría"
L["Center"] = "Centro"
L["Changes the health bar to the set hostile color (Red by default) when the unit takes aggro."] = "Cambia la barra de salud para el juego de colores hostil (rojo por defecto) cuando la unidad tiene agresividad." -- Needs review
L["Changes this widget into a bar, you will be able to change the height and ordering like you can change health and power bars."] = "Cambia este aplicación en una barra, que será capaz de cambiar la altura y ordenar como se puede cambiar las barras de salud y poder." -- Needs review
L["Channelling"] = "Canalizando"
L["Child units cannot be dragged, you will have to reposition them through /shadowuf."] = "Unidades filiales no se puede arrastrar, que tendrá que cambiar la posición a través de / shadowuf." -- Needs review
L["Class"] = "Clase"
L["Class color tag"] = "Etiqueta de color de clase"
L["Classes"] = "Clases"
L["Class icon"] = "Icono de clase"
L["Classification"] = "Classificación" -- Needs review
L["Classifications"] = "Clasificaciones"
L["Class name without coloring, use [classcolor][class][close] if you want the class name to be colored by class."] = "Nombre de la clase sin color, utilice [classcolor][class][close] si desea que el nombre de la clase que esté influido por la clase." -- Needs review
L["Class (Smart)"] = "Clase (inteligente)"
L["Clip"] = "sujetar" -- Needs review
L["Close color"] = "Cierra color" -- Needs review
L["Closes a color code, prevents colors from showing up on text that you do not want it to."] = "Cierra un código de color, evita que los colores a aparecer en el texto que usted no quiere que lo haga." -- Needs review
L["Code"] = "Código" -- Needs review
L["Color by class"] = "Color por clase" -- Needs review
L["Color by reaction on"] = "Color por reacción en" -- Needs review
L["Color code based on percentage of HP left on the unit, this works the same way as the color by health option. But for text instead of the entire bar."] = "Código de color en función del porcentaje de Salud a la izquierda en la unidad, esto funciona de la misma forma como el color de la opción de la salud. Pero para el texto en lugar de la barra entera." -- Needs review
L["Color code for general situation"] = "Código de color para situación general" -- Needs review
L["Color code for situation"] = "Código de color para situación" -- Needs review
L["Color code for the class, use [classcolor][class][close] if you want the class text to be colored by class"] = "Código de color por clase, utilice [classcolor][class][close] si desea que el texto de la clase esté influido por la clase" -- Needs review
L["Color code on aggro"] = "Codigo de color en agresivo" -- Needs review
L["Color health by"] = "Color de salud por" -- Needs review
L["Color on aggro"] = "Color en agresivo" -- Needs review
L["Color to use for health bars that are set to be colored by a static color."] = "Color a utilizar para las barras de salud que se establecen para ser coloreado con un color estático." -- Needs review
L["Color used when a cast cannot be interrupted, this is only used for PvE mobs."] = "Color que se utiliza cuando una lanzamiento no puede ser interrumpido, esta sólo se utiliza para las multitudes PvE." -- Needs review
L["Color used when a cast is a channel."] = "Color que se utiliza cuando un lanzamiento es una canalización." -- Needs review
L["Column growth"] = "Crecimiento de Columna" -- Needs review
L["Column spacing"] = "Separación de columna " -- Needs review
L["Combat alpha"] = "Trasparencia en Combate" -- Needs review
L["Combat fader"] = "Atenua en combate" -- Needs review
L["Combat fader will fade out all your frames while they are inactive and fade them back in once you are in combat or active."] = "Atenua en combate desvanecerá todos sus marcos, mientras que esta inactiva y desaparece de nuevo una vez que esté en combate o en activo." -- Needs review
L["Combat/resting status"] = "Combate/descanso estado" -- Needs review
L["Combat text"] = "Texto de combate" -- Needs review
L["Combo points"] = "Puntos de combo" -- Needs review
L["Combo Points"] = "Puntos de Combo" -- Needs review
L["Configuration to specific unit frames."] = "Configuración de unidades de marco especifico" -- Needs review
L["Current Eclipse, <0 is Lunar Energy and >0 is Solar Energy."] = "Eclipse activo, <0 es Eclipse Lunar y >0 es Energia Solar" -- Needs review
L["Eclipse (Druid)"] = "Eclipse (Druida)"
L["Has Aggro"] = "Tiene Aggro"
L["Minion"] = "Subdito" -- Needs review
L["%s frames"] = "%s marcos"
L["%s member"] = "%s miembro"
L["%s (%s): %s/%s (%.2f%% done)"] = "%s (%s): %s/%s (%.2f%% hecho)"

local ShadowUF = select(2, ...)
ShadowUF.L = setmetatable(L, {__index = ShadowUF.L})
