if( GetLocale() ~= "ptBR" ) then return end
local L = {}
L["2D"] = "2D"
L["3D"] = "3D"
L["A"] = "A"
L["Abbreviates unit names above 10 characters, \"Dark Rune Champion\" becomes \"D.R.Champion\" and \"Dark Rune Commoner\" becomes \"D.R.Commoner\"."] = "Abrevia os nomes das unidades com mais de 10 caracteres, \"Dark Rune Champion\" passa a \"D.R.Champion\" e \"Dark Rune Commoner\" passa a  \"D.R.Commoner\"."
L["Absolute incoming heal value, if 10,000 healing is incoming it will show 10,000."] = "Valor absoluto de cura a receber, se vai receber 10,000 de cura, então mostrará 10,000."
L["Add"] = "Adiciona"
L["Add new tag"] = "Adicionar nova tag"
L["Add new text"] = "Adicionar novo texto"
L["Adds a bar indicating how much time is left on your ghoul timer, only used if you do not have a permanent ghoul."] = "Adiciona uma barra a indicar quanto tempo resta no temporizador da ghoul, apenas é usado se não tiver uma ghoul permanente." -- Needs review
L["Adds an empty bar that you can put text into as a way of uncluttering other bars."] = "Adiciona uma barra onde pode por texto como forma de desatafulhar outras barras." -- Needs review
L["Adds another mana bar to the player frame when you are in Bear or Cat form showing you how much mana you have."] = "Adiciona uma outra barra de mana à moldura quando está em forma de Gato ou Urso indicando a mana que possui." -- Needs review
L["Adds rune bars and timers before runes refresh to the player frame."] = "Adiciona à moldura do jogador temporizadores de tempo restante para as runes refrescarem e barras de runes." -- Needs review
L["Adds %s to the list of units to be modified when you change values in this tab."] = "Adiciona %s à lista de unidades que vão ser modificadas quando muda valores neste separador." -- Needs review
L["Adds temporary enchants to the buffs for the player."] = "Adiciona encantamentos temporários aos feitiços benéficos para o jogador." -- Needs review
L["Adds totem bars with timers before they expire to the player frame."] = "Adiciona à moldura do jogador barras de totems com temporizadores de tempo restante para expirarem." -- Needs review
L["Add tags"] = "Adicionar tags" -- Needs review
L["Advanced"] = "Avançadas"
L["Advanced tag management, allows you to add your own custom tags."] = "Gestão avançada de tags, permite-lhe adicionar as suas próprias tags." -- Needs review
L["AFK"] = "LDT"
L["AFK:%s"] = "LDT:%s"
L["AFK status"] = "estado LDT"
L["AFK timer"] = "temporizador LDT"
L["After you hit export, you can give the below code to other Shadowed Unit Frames users and they will get your exact layout."] = "Depois de clicar em exportar, pode dar o código abaixo a outros utilizadores do Shadowed Unit Frames e eles irão ficar com a disposição das molduras igual à sua." -- Needs review
L["Aggro"] = "Aggro" -- Needs review
L["Alpha to use for bar backgrounds."] = "Alpha para usar no background da barra." -- Needs review
L["Ammo"] = "Munições" -- Needs review
L["Amount of health missing, if none is missing nothing is shown. Uses a short format, -18500 is shown as -18.5k, values below 10000 are formatted as is."] = "Quantidade de vida em falta, se há 0 em falta nada é mostrado. Utiliza um formato curto, -18500 é mostrado como -18.5k, valores abaixo de 10000 são formatados assim mesmo." -- Needs review
L["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Quantidade de power em falta, se faltar 0 nada será mostrado. Usa um formato curto, -13850 é mostrado como 13.8k, valores abaixo de 10000 são formatados assim mesmo." -- Needs review
L["Anchor point"] = "Ponto de ancoragem" -- Needs review
L["Anchor to"] = "Ancorar a" -- Needs review
L["Anchor to another frame"] = "Ancorar a outra moldura" -- Needs review
L["Anchor to buffs"] = "Ancorar aos buffs" -- Needs review
L["Anchor to debuffs"] = "Ancorar aos debuffs" -- Needs review
L["Aquatic"] = "Aquantico" -- Needs review
L["Arena"] = "Arena" -- Needs review
L["Arenas"] = "Arenas" -- Needs review
L["Are you sure you want to delete this filter?"] = "Tem a certeza que pretende apagar este filtro?" -- Needs review
L["Are you sure you want to delete this tag?"] = "Tem a certeza que quer apagar esta tag?" -- Needs review
L["Are you sure you want to delete this text? All settings for it will be deleted."] = "Tem a certeza que quer apagar este texto? Todas as definições do mesmo serão apagadas." -- Needs review
L["Ascending"] = "Ascendente" -- Needs review
L["Aura border style"] = "Estilo da aura da aresta" -- Needs review
L["Aura filters"] = "Filtros de aura" -- Needs review
L["Aura name"] = "Nome da aura" -- Needs review
L["Auras"] = "Auras" -- Needs review
L["Aura types to filter"] = "Tipos de filtros de aura" -- Needs review
L["B"] = "B" -- Needs review
L["Background"] = "Background" -- Needs review
L["Background alpha"] = "Alpha de background" -- Needs review
L["Background/border"] = "Background/border" -- Needs review
L["Background color"] = "Cor de background" -- Needs review
L["Bag indicator for master looters."] = "Indicador de saco para master looters" -- Needs review
L["Bars"] = "Barras" -- Needs review
L["Bar spacing"] = "Espaçamento da barra" -- Needs review
L["Bar texture"] = "Textura da barra" -- Needs review
L["Battlegrounds"] = "Battlegrounds" -- Needs review
L["Bear"] = "Urso" -- Needs review
L["Blacklist"] = "Lista negra" -- Needs review
L["Blacklist filters"] = "Filtros de lista negra" -- Needs review
L["Blacklists"] = "Listas negras" -- Needs review
L["Blizzard"] = "Blizzard" -- Needs review
L["Border"] = "Aresta" -- Needs review
L["Border alpha"] = "Alpha da aresta" -- Needs review
L["Border color"] = "Cor da aresta" -- Needs review
L["Border highlighting"] = "Border highlighting" -- Needs review
L["Border thickness"] = "Grossura da aresta" -- Needs review
L["Boss"] = "Boss" -- Needs review
L["%s frames"] = "%s moldura"
L["%s member"] = "%s membro"
L["%s (%s): %s/%s (%.2f%% done)"] = "%s (%s): %s/%s (%.2f%% terminado)"

local ShadowUF = select(2, ...)
ShadowUF.L = setmetatable(L, {__index = ShadowUF.L})
