--[[
    Bagnon Config Localization: Spanish
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'esES') or LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'esMX')
if not L then return end

L.Columns = 'Columnas'
L.Scale = 'Escala'
L.Spacing = 'Espacio'
L.Opacity = 'Opacidad'
L.FrameColor = 'Color del fondo'
L.FrameBorderColor = 'Color del borde'
L.Frame = 'Mochila'
L.Bank = 'Banco'
L.LockFramePositions = 'Bloquear posiciones de marcos'
L.ShowEmptyItemSlotBackground = 'Mostrar un fondo para las ranuras de objetos vacías'
L.HighlightItemsByQuality = 'Resalte objetos por calidad'
L.HighlightUnusableItems = 'Resalte objetos inutilizables'
L.HighlightQuestItems = 'Resalte objetos de misiones'
L.ReverseSlotOrdering = 'Orden inverso de ranuras en bolsas'
L.ColorItemSlotsByBagType = 'Colorear ranuras de objetos vacías por tipo de bolsa'
L.FrameLayer = 'Estrato'
L.EnableBagFrame = 'Mostrar las bolsas'
L.EnableMoneyFrame = 'Mostrar el dinero'
L.EnableDBOFrame = 'Mostrar DataBroker'
L.EnableSearchToggle = 'Mostrar el botón de búsqueda'
L.EnableOptionsToggle = 'Mostrar el botón de opciones'
L.EnableFrame_inventory = 'Activar la ventana de mochila'
L.EnableFrame_bank = 'Activar la ventana de banco'
L.SettingRequiresRestart = 'Esta opción no se aplicará hasta la próxima vez que conectar o recargar la interfaz.'

L.EnableAutoDisplay_bank = 'Abrir mochila cuando visitar el banco'
L.EnableAutoDisplay_ah = 'Abrir mochila cuando visitar la casa de subastas'
L.EnableAutoDisplay_vendor = 'Cerrar inventory cuando salir del mercader'
L.EnableAutoDisplay_trade = 'Abrir mochila cuando comerciar'
L.EnableAutoDisplay_craft = 'Abrir mochila para abrir la ventana de profesión'
L.EnableAutoDisplay_mail = 'Abrir mochila cuando visitar la buzón'
L.EnableAutoDisplay_guildbank = 'Abrir mochila cuando visitar el banco de hermandad'
L.EnableAutoDisplay_player = 'Abrir mochila cuando abrir el panel del personaje'
L.EnableAutoDisplay_combat = 'Cerrar mochila cuando entrar en combate'
L.EnableAutoDisplay_vehicle = 'Cerrar mochila cuando entrar en un vehículo'
L.EnableAutoDisplay_gems = 'Abrir mochila cuando insertar gemas'

L.DisplaySettings = 'Exhibición automática'
L.DisplaySettingsTitle = 'Opciones para abrir o cerrar automáticamente las ventanas'
L.FrameSettings = 'Opciones de ventana'
L.FrameSettingsTitle = 'Opciones específicas para una ventana de Bagnon'
L.GeneralSettings = 'Opciones generales'
L.GeneralSettingsTitle = 'Opciones generales para Bagnon'
L.EnableBlizzardBagPassThrough = 'Mostrar ventanas de Blizzard para bolsas desactivadas'
L.EnableBagBreak = 'Activar descansos entre bolsas'
L.ColorSettings = 'Opciones de color'
L.ColorSettingsTitle = 'Opciones de colores de las ranuras de objetos'
L.ItemHighlightOpacity = 'Brillo del resaltado de objectos'
L.EnableFlashFind = 'Activar Flash Find'
L.EnableTipCount = 'Mostrar recuento de objetos en tooltips'
L.EnableFading = 'Activar desaparición de ventanas'
L.AllowDisableBags = 'Desactivar bolsas al hacer clic'

L.ItemSlotColor_normal = 'Color de ranuras normales'
L.ItemSlotColor_leather = 'Color de ranuras para peletería'
L.ItemSlotColor_inscri = 'Color de ranuras para inscripción'
L.ItemSlotColor_herb = 'Color de ranuras para hierbas'
L.ItemSlotColor_enchant = 'Color de ranuras para encantamiento'
L.ItemSlotColor_engineer = 'Color de ranuras para ingeniería'
L.ItemSlotColor_gem = 'Color de ranuras para gemas'
L.ItemSlotColor_mine = 'Color de ranuras para minería'
L.ItemSlotColor_tackle = 'Color de ranuras de aparejos'