--[[
	Bagnon Config Localization: French Language
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'frFR')
if not L then return end

L.Columns = 'Colonnes'
L.Scale = 'Echelle'
L.Spacing = 'Espacement'
L.Opacity = 'Opacité'
L.FrameColor = 'Couleur de la fenêtre'
L.FrameBorderColor = 'Couleur de bordure de la fenêtre'
L.Frame = 'Fenêtre'
L.Bank = 'Banque'
L.LockFramePositions = 'Bloquer la position des fenêtres'
L.ShowEmptyItemSlotBackground = 'Affiche un fond sur les emplacements vides'
L.HighlightItemsByQuality = 'Surligne les objets par qualité' 
L.HighlightUnusableItems = 'Surligne les objets inutiles'
L.HighlightQuestItems = 'Surligne les objets de quête'
L.ReverseSlotOrdering = 'Inverse l\'ordre de tri'
L.ColorItemSlotsByBagType = 'Colorise les emplacements vides par type de sac'
L.FrameLayer = 'Couche'
L.EnableBagFrame = 'Activer la fenêtre du sac'
L.EnableMoneyFrame = 'Activer l\'affichage des revenus'
L.EnableDBOFrame = 'Activer le DataBroker'
L.EnableSearchToggle = 'Activer le champ de recherche'
L.EnableOptionsToggle = 'Activer l\'affichage des options'
L.EnableFrame_inventory = 'Activer la fenêtre de l\'inventaire'
L.EnableFrame_bank = 'Activer la fenêtre de la banque'
L.SettingRequiresRestart = 'Cette option prendra effet au prochain chargement'

L.EnableAutoDisplay_bank = 'Affiche votre inventaire quand vous visitez la banque'
L.EnableAutoDisplay_ah = 'Affiche votre inventaire quand vous visitez l\'hôtel des ventes'
L.EnableAutoDisplay_vendor = 'Ferme votre inventaire quand vous quittez un marchand'
L.EnableAutoDisplay_trade = 'Affiche votre inventaire quand vous parlez à un commerçant'
L.EnableAutoDisplay_craft = 'Affiche votre inventaire quand vous craftez'
L.EnableAutoDisplay_mail = 'Affiche votre inventaire quand vous relevez votre courrier'
L.EnableAutoDisplay_guildbank = 'Affiche votre inventaire quand vous visitez votre banque de guilde'
L.EnableAutoDisplay_player = 'Affiche votre inventaire quand vous ouvrez la fenêtre de votre personnage'
L.EnableAutoDisplay_combat = 'Ferme votre inventaire quand vous entrez en combat'
L.EnableAutoDisplay_vehicle = 'Ferme votre inventaire quand vous montez dans un véhicule'
L.EnableAutoDisplay_gems = 'Affiche votre inventaire quand vous sertissez vos objets'

L.DisplaySettings = 'Affichage Automatique'
L.DisplaySettingsTitle = 'Options de l\'affichage automatique'
L.FrameSettings = 'Options des Fenêtres'
L.FrameSettingsTitle = 'Configuration des options spécifiques à une fenêtre de Bagnon'
L.GeneralSettings = 'Options Générales'
L.GeneralSettingsTitle = 'Configuration des options générales de Bagnon'
L.EnableBlizzardBagPassThrough = 'Afficher les cadres de Blizzard pour les sacs désactivés'
L.EnableBagBreak = 'Activer séparation entre les sacs'
L.ColorSettings = 'Options de couleur'
L.ColorSettingsTitle = 'Options de colorisation des emplacements'
L.ItemHighlightOpacity = 'Contours lumineux des objets'
L.EnableFlashFind = 'Activer résultat éclair'
L.EnableTipCount = 'Activer l\'info-bulle du compteur d\'objets'
L.EnableFading = 'Activer le fading des fenêtres'
L.AllowDisableBags = 'Désactive les sacs quand activé'

L.ItemSlotColor_normal = 'Couleur des emplacements normaux'
L.ItemSlotColor_leather = 'Couleur des emplacements de sac Travail du Cuir'
L.ItemSlotColor_inscri = 'Couleur des emplacements de sac Calligraphie'
L.ItemSlotColor_herb = 'Couleur des emplacements de sac Herboristerie'
L.ItemSlotColor_enchant = 'Couleur des emplacements de sac Enchantement'
L.ItemSlotColor_engineer = 'Couleur des emplacements de sac Ingénierie'
L.ItemSlotColor_gem = 'Couleur des emplacements de sac de Gemmes'
L.ItemSlotColor_mine = 'Couleur des emplacements de sac de Minage'
L.ItemSlotColor_tackle = 'Couleur des emplacements de sac de Pêche'