
BuildEnv(...)

local L = LibStub('AceLocale-3.0'):GetLocale('WowSocial_UI')

ADDON_LOGO = [[Interface\AddOns\WowSocial_UI\Media\Icon]]

ClassData = {}
RaceData = {
    Human = L.Human,
    Dwarf = L.Dwarf,
    NightElf = L.NightElf,
    Gnome = L.Gnome,
    Draenei = L.Draenei,
    Worgen = L.Worgen,
    Orc = L.Orc,
    Scourge = L.Scourge,
    Tauren = L.Tauren,
    Troll = L.Troll,
    Goblin = L.Goblin,
    BloodElf = L.BloodElf,
    Pandaren = L.Pandaren,
}

for i = 1, GetNumClasses() do
    local name, tag, id = GetClassInfo(i)

    ClassData[tag] = name
end

RACE_ICON_TCOORDS = {
    ['HUMAN_MALE']      = {0, 0.125, 0, 0.25},
    ['DWARF_MALE']      = {0.125, 0.25, 0, 0.25},
    ['GNOME_MALE']      = {0.25, 0.375, 0, 0.25},
    ['NIGHTELF_MALE']   = {0.375, 0.5, 0, 0.25},

    ['TAUREN_MALE']     = {0, 0.125, 0.25, 0.5},
    ['SCOURGE_MALE']    = {0.125, 0.25, 0.25, 0.5},
    ['TROLL_MALE']      = {0.25, 0.375, 0.25, 0.5},
    ['ORC_MALE']        = {0.375, 0.5, 0.25, 0.5},

    ['HUMAN_FEMALE']    = {0, 0.125, 0.5, 0.75},  
    ['DWARF_FEMALE']    = {0.125, 0.25, 0.5, 0.75},
    ['GNOME_FEMALE']    = {0.25, 0.375, 0.5, 0.75},
    ['NIGHTELF_FEMALE'] = {0.375, 0.5, 0.5, 0.75},

    ['TAUREN_FEMALE']   = {0, 0.125, 0.75, 1.0},   
    ['SCOURGE_FEMALE']  = {0.125, 0.25, 0.75, 1.0}, 
    ['TROLL_FEMALE']    = {0.25, 0.375, 0.75, 1.0}, 
    ['ORC_FEMALE']      = {0.375, 0.5, 0.75, 1.0}, 

    ['BLOODELF_MALE']   = {0.5, 0.625, 0.25, 0.5},
    ['BLOODELF_FEMALE'] = {0.5, 0.625, 0.75, 1.0}, 

    ['DRAENEI_MALE']    = {0.5, 0.625, 0, 0.25},
    ['DRAENEI_FEMALE']  = {0.5, 0.625, 0.5, 0.75}, 

    ['GOBLIN_MALE']     = {0.625, 0.750, 0.25, 0.5},
    ['GOBLIN_FEMALE']   = {0.625, 0.750, 0.75, 1.0},

    ['WORGEN_MALE']     = {0.625, 0.750, 0, 0.25},
    ['WORGEN_FEMALE']   = {0.625, 0.750, 0.5, 0.75},

    ['PANDAREN_MALE']   = {0.760, 0.880, 0, 0.25},
    ['PANDAREN_FEMALE'] = {0.760, 0.880, 0.5, 0.75},
}

InterestList = {
    L['任务'],
    L['地下城'],
    L['团队副本'],
    L['PvP'],
    L['角色扮演'],
    L['发呆'],
}

OnlineTimeList = {
    L['周一'],
    L['周二'],
    L['周三'],
    L['周四'],
    L['周五'],
    L['周末'],
}

CityData = {
    [0] = {
        [1] = '北京', [2] = '上海', [3] = '天津', [4] = '重庆', [5] = '河北', [6] = '山西', [7] = '内蒙古', [8] = '辽宁', [9] = '吉林', [10] = '黑龙江', [11] = '江苏', [12] = '浙江', [13] = '安徽', [14] = '福建', [15] = '江西', [16] = '山东', [17] = '河南', [18] = '湖北', [19] = '湖南', [20] = '广东', [21] = '广西', [22] = '海南', [23] = '四川', [24] = '贵州', [25] = '云南', [26] = '西藏', [27] = '陕西', [28] = '甘肃', [29] = '宁夏', [30] = '青海', [31] = '新疆', [32] = '香港', [33] = '澳门', [34] = '台湾',
    },
    [1] = {
        [101] = '东城', [102] = '西城', [103] = '崇文', [104] = '宣武', [105] = '朝阳', [106] = '丰台', [107] = '石景山', [108] = '海淀', [109] = '门头沟', [110] = '房山', [111] = '通州', [112] = '顺义', [113] = '昌平', [114] = '大兴', [115] = '平谷', [116] = '怀柔', [117] = '密云', [118] = '延庆',
    },
    [2] = {
        [201] = '黄浦', [202] = '卢湾', [203] = '徐汇', [204] = '长宁', [205] = '静安', [206] = '普陀', [207] = '闸北', [208] = '虹口', [209] = '杨浦', [210] = '闵行', [211] = '宝山', [212] = '嘉定', [213] = '浦东', [214] = '金山', [215] = '松江', [216] = '青浦', [217] = '南汇', [218] = '奉贤', [219] = '崇明', 
    },
    [3] = {
        [301] = '和平', [302] = '东丽', [303] = '河东', [304] = '西青', [305] = '河西', [306] = '津南', [307] = '南开', [308] = '北辰', [309] = '河北', [310] = '武清', [311] = '红挢', [312] = '塘沽', [313] = '汉沽', [314] = '大港', [315] = '宁河', [316] = '静海', [317] = '宝坻', [318] = '蓟县',
    },
    [4] = {
        [401] = '巴南', [402] = '北碚', [403] = '璧山', [404] = '长寿', [405] = '城口', [406] = '大渡口', [407] = '大足', [408] = '垫江', [409] = '丰都', [410] = '奉节', [411] = '涪陵', [412] = '合川', [413] = '江北', [414] = '江津', [415] = '九龙坡', [416] = '开县', [417] = '梁平', [418] = '南岸', [419] = '南川', [420] = '彭水', [421] = '綦江', [422] = '黔江', [423] = '荣昌', [424] = '沙坪坝', [425] = '石柱', [426] = '双桥', [427] = '铜梁', [428] = '潼南', [429] = '万盛', [430] = '万州', [431] = '巫山', [432] = '巫溪', [433] = '武隆', [434] = '秀山', [435] = '永川', [436] = '酉阳', [437] = '渝北', [438] = '渝中', [439] = '云阳', [440] = '忠县',
    },
    [5] = {
        [501] = '石家庄', [502] = '邯郸', [503] = '邢台', [504] = '保定', [505] = '张家口', [506] = '承德', [507] = '廊坊', [508] = '唐山', [509] = '秦皇岛', [510] = '沧州', [511] = '衡水',
    },
    [6] = {
        [601] = '太原', [602] = '大同', [603] = '阳泉', [604] = '长治', [605] = '晋城', [606] = '朔州', [607] = '吕梁', [608] = '忻州', [609] = '晋中', [610] = '临汾',
    },
    [7] = {
        [701] = '呼和浩特', [702] = '包头', [703] = '乌海', [704] = '赤峰', [705] = '呼伦贝尔', [706] = '阿拉善', [707] = '鄂尔多斯', [708] = '兴安', [709] = '乌兰察布', [710] = '锡林郭勒', [711] = '巴彦淖尔', [712] = '通辽',
    },
    [8] = {
        [801] = '沈阳', [802] = '大连', [803] = '鞍山', [804] = '抚顺', [805] = '本溪', [806] = '丹东', [807] = '锦州', [808] = '营口', [809] = '阜新', [810] = '辽阳', [811] = '盘锦', [812] = '铁岭', [813] = '朝阳', [814] = '葫芦岛',
    },
    [9] = {
        [901] = '长春', [902] = '吉林', [903] = '四平', [904] = '辽源', [905] = '通化', [906] = '白山', [907] = '松原', [908] = '白城', [909] = '延边',
    },
    [10] = {
        [1001] = '哈尔滨', [1002] = '齐齐哈尔', [1003] = '牡丹江', [1004] = '佳木斯', [1005] = '大庆', [1006] = '绥化', [1007] = '鹤岗', [1008] = '鸡西', [1009] = '黑河', [1010] = '双鸭山', [1011] = '伊春', [1012] = '七台河', [1013] = '大兴安岭',
    },
    [11] = {
        [1101] = '南京', [1102] = '镇江', [1103] = '苏州', [1104] = '南通', [1105] = '扬州', [1106] = '盐城', [1107] = '徐州', [1108] = '连云港', [1109] = '常州', [1110] = '无锡', [1111] = '宿迁', [1112] = '泰州', [1113] = '淮安',
    },
    [12] = {
        [1201] = '杭州', [1202] = '宁波', [1203] = '温州', [1204] = '嘉兴', [1205] = '湖州', [1206] = '绍兴', [1207] = '金华', [1208] = '衢州', [1209] = '舟山', [1210] = '台州', [1211] = '丽水',
    },
    [13] = {
        [1301] = '合肥', [1302] = '芜湖', [1303] = '蚌埠', [1304] = '马鞍山', [1305] = '淮北', [1306] = '铜陵', [1307] = '安庆', [1308] = '黄山', [1309] = '滁州', [1310] = '宿州', [1311] = '池州', [1312] = '淮南', [1313] = '巢湖', [1314] = '阜阳', [1315] = '六安', [1316] = '宣城', [1317] = '亳州',
    },
    [14] = {
        [1401] = '福州', [1402] = '厦门', [1403] = '莆田', [1404] = '三明', [1405] = '泉州', [1406] = '漳州', [1407] = '南平', [1408] = '龙岩', [1409] = '宁德',
    },
    [15] = {
        [1501] = '南昌市', [1502] = '景德镇', [1503] = '九江', [1504] = '鹰潭', [1505] = '萍乡', [1506] = '新馀', [1507] = '赣州', [1508] = '吉安', [1509] = '宜春', [1510] = '抚州', [1511] = '上饶',
    },
    [16] = {
        [1601] = '济南', [1602] = '青岛', [1603] = '淄博', [1604] = '枣庄', [1605] = '东营', [1606] = '烟台', [1607] = '潍坊', [1608] = '济宁', [1609] = '泰安', [1610] = '威海', [1611] = '日照', [1612] = '莱芜', [1613] = '临沂', [1614] = '德州', [1615] = '聊城', [1616] = '滨州', [1617] = '菏泽',
    },
    [17] = {
        [1701] = '郑州', [1702] = '开封', [1703] = '洛阳', [1704] = '平顶山', [1705] = '安阳', [1706] = '鹤壁', [1707] = '新乡', [1708] = '焦作', [1709] = '濮阳', [1710] = '许昌', [1711] = '漯河', [1712] = '三门峡', [1713] = '南阳', [1714] = '商丘', [1715] = '信阳', [1716] = '周口', [1717] = '驻马店', [1718] = '济源',
    },
    [18] = {
        [1801] = '武汉', [1802] = '宜昌', [1803] = '荆州', [1804] = '襄樊', [1805] = '黄石', [1806] = '荆门', [1807] = '黄冈', [1808] = '十堰', [1809] = '恩施', [1810] = '潜江', [1811] = '天门', [1812] = '仙桃', [1813] = '随州', [1814] = '咸宁', [1815] = '孝感', [1816] = '鄂州', [1817] = '神农架',
    },
    [19] = {
        [1901] = '长沙', [1902] = '常德', [1903] = '株洲', [1904] = '湘潭', [1905] = '衡阳', [1906] = '岳阳', [1907] = '邵阳', [1908] = '益阳', [1909] = '娄底', [1910] = '怀化', [1911] = '郴州', [1912] = '永州', [1913] = '湘西', [1914] = '张家界',
    },
    [20] = {
        [2001] = '广州', [2002] = '深圳', [2003] = '珠海', [2004] = '汕头', [2005] = '东莞', [2006] = '中山', [2007] = '佛山', [2008] = '韶关', [2009] = '江门', [2010] = '湛江', [2011] = '茂名', [2012] = '肇庆', [2013] = '惠州', [2014] = '梅州', [2015] = '汕尾', [2016] = '河源', [2017] = '阳江', [2018] = '清远', [2019] = '潮州', [2020] = '揭阳', [2021] = '云浮',
    },
    [21] = {
        [2101] = '南宁', [2102] = '柳州', [2103] = '桂林', [2104] = '梧州', [2105] = '北海', [2106] = '防城港', [2107] = '钦州', [2108] = '贵港', [2109] = '玉林', [2110] = '南宁', [2111] = '柳州', [2112] = '贺州', [2113] = '百色', [2114] = '河池',
    },
    [22] = {
        [2201] = '海口', [2202] = '三亚',
    },
    [23] = {
        [2301] = '成都', [2302] = '阿坝', [2303] = '巴中', [2304] = '达州', [2305] = '德阳', [2306] = '甘孜', [2307] = '广安', [2308] = '广元', [2309] = '乐山', [2310] = '凉山', [2311] = '泸州', [2312] = '眉山', [2313] = '绵阳', [2314] = '内江', [2315] = '南充', [2316] = '攀枝花', [2317] = '遂宁', [2318] = '雅安', [2319] = '宜宾', [2320] = '资阳', [2321] = '自贡',
    },
    [24] = {
        [2401] = '贵阳', [2402] = '六盘水', [2403] = '遵义', [2404] = '安顺', [2405] = '铜仁', [2406] = '黔西南', [2407] = '毕节', [2408] = '黔东南', [2409] = '黔南',
    },
    [25] = {
        [2501] = '昆明', [2502] = '保山', [2503] = '楚雄', [2504] = '大理', [2505] = '德宏', [2506] = '迪庆', [2507] = '红河', [2508] = '丽江', [2509] = '临沧', [2510] = '怒江', [2511] = '曲靖', [2512] = '思茅', [2513] = '文山', [2514] = '西双版纳', [2515] = '玉溪', [2516] = '昭通',
    },
    [26] = {
        [2601] = '拉萨', [2602] = '日喀则', [2603] = '山南', [2604] = '林芝', [2605] = '昌都', [2606] = '阿里', [2607] = '那曲',
    },
    [27] = {
        [2701] = '西安', [2702] = '宝鸡', [2703] = '咸阳', [2704] = '铜川', [2705] = '渭南', [2706] = '延安', [2707] = '榆林', [2708] = '汉中', [2709] = '安康', [2710] = '商洛',
    },
    [28] = {
        [2801] = '兰州', [2802] = '嘉峪关', [2803] = '金昌', [2804] = '白银', [2805] = '天水', [2806] = '酒泉', [2807] = '张掖', [2808] = '武威', [2809] = '定西', [2810] = '陇南', [2811] = '平凉', [2812] = '庆阳', [2813] = '临夏', [2814] = '甘南',
    },
    [29] = {
        [2901] = '银川', [2902] = '石嘴山', [2903] = '吴忠', [2904] = '固原', [2905] = '中卫',
    },
    [30] = {
        [3001] = '西宁', [3002] = '海东', [3003] = '海南', [3004] = '海北', [3005] = '黄南', [3006] = '玉树', [3007] = '果洛', [3008] = '海西',
    },
    [31] = {
        [3101] = '乌鲁木齐', [3102] = '阿克苏', [3103] = '阿拉尔', [3104] = '阿勒泰', [3105] = '巴音郭楞', [3106] = '博尔塔拉', [3107] = '昌吉', [3108] = '哈密', [3109] = '和田', [3110] = '喀什', [3111] = '克拉玛依', [3112] = '克孜勒苏柯尔克孜', [3113] = '石河子', [3114] = '塔城', [3115] = '图木舒克', [3116] = '吐鲁番', [3117] = '五家渠', [3118] = '伊犁',
    },
    [32] = {
        [3201] = '北区', [3202] = '大埔区', [3203] = '东区', [3204] = '观塘区', [3205] = '黄大仙区', [3206] = '九龙', [3207] = '葵青区', [3208] = '离岛区', [3209] = '南区', [3210] = '荃湾区', [3211] = '沙田区', [3212] = '深水埗区', [3213] = '屯门区', [3214] = '湾仔区', [3215] = '西贡区', [3216] = '香港', [3217] = '新界', [3218] = '油尖旺区', [3219] = '元朗区', [3220] = '中西区',
    },
    [33] = {
        [3301] = '澳门',
    },
    [34] = {
        [3401] = '台北', [3402] = '高雄', [3403] = '台中', [3404] = '台南', [3405] = '屏东', [3406] = '南投', [3407] = '云林', [3408] = '新竹', [3409] = '彰化', [3410] = '苗栗', [3411] = '嘉义', [3412] = '花莲', [3413] = '桃园', [3414] = '宜兰', [3415] = '基隆', [3416] = '台东', [3417] = '金门', [3418] = '马祖', [3419] = '澎湖',
    },
}

EmoteData = { 
    { Name = 'rt1',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_1]] },
    { Name = 'rt2',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_2]] },
    { Name = 'rt3',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_3]] },
    { Name = 'rt4',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_4]] },
    { Name = 'rt5',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_5]] },
    { Name = 'rt6',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_6]] },
    { Name = 'rt7',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_7]] },
    { Name = 'rt8',         Icon = [[Interface\TargetingFrame\UI-RaidTargetingIcon_8]] },
    { Name = L.Angel,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\angel.tga]] }, 
    { Name = L.Angry,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\angry.tga]] }, 
    { Name = L.Biglaugh,    Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\biglaugh.tga]] }, 
    { Name = L.Clap,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\clap.tga]] }, 
    { Name = L.Cool,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\cool.tga]] }, 
    { Name = L.Cry,         Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\cry.tga]] }, 
    { Name = L.Cute,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\cutie.tga]] }, 
    { Name = L.Despise,     Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\despise.tga]] }, 
    { Name = L.Dreamsmile,  Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\dreamsmile.tga]] }, 
    { Name = L.Embarras,    Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\embarrass.tga]] }, 
    { Name = L.Evil,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\evil.tga]] }, 
    { Name = L.Excited,     Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\excited.tga]] }, 
    { Name = L.Faint,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\faint.tga]] }, 
    { Name = L.Fight,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\fight.tga]] }, 
    { Name = L.Flu,         Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\flu.tga]] }, 
    { Name = L.Freeze,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\freeze.tga]] }, 
    { Name = L.Frown,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\frown.tga]] }, 
    { Name = L.Greet,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\greet.tga]] }, 
    { Name = L.Grimace,     Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\grimace.tga]] }, 
    { Name = L.Growl,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\growl.tga]] }, 
    { Name = L.Happy,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\happy.tga]] }, 
    { Name = L.Heart,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\heart.tga]] }, 
    { Name = L.Horror,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\horror.tga]] }, 
    { Name = L.Ill,         Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\ill.tga]] }, 
    { Name = L.Innocent,    Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\innocent.tga]] }, 
    { Name = L.Kongfu,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\kongfu.tga]] }, 
    { Name = L.Love,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\love.tga]] }, 
    { Name = L.Mail,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\mail.tga]] }, 
    { Name = L.Makeup,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\makeup.tga]] }, 
    { Name = L.Mario,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\mario.tga]] }, 
    { Name = L.Meditate,    Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\meditate.tga]] }, 
    { Name = L.Miserable,   Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\miserable.tga]] }, 
    { Name = L.Okay,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\okay.tga]] }, 
    { Name = L.Pretty,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\pretty.tga]] }, 
    { Name = L.Puke,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\puke.tga]] }, 
    { Name = L.Shake,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\shake.tga]] }, 
    { Name = L.Shout,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\shout.tga]] }, 
    { Name = L.Silent,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\shuuuu.tga]] }, 
    { Name = L.Shy,         Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\shy.tga]] }, 
    { Name = L.Sleep,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\sleep.tga]] }, 
    { Name = L.Smile,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\smile.tga]] }, 
    { Name = L.Suprise,     Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\suprise.tga]] }, 
    { Name = L.Surrender,   Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\surrender.tga]] }, 
    { Name = L.Sweat,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\sweat.tga]] }, 
    { Name = L.Tear,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\tear.tga]] }, 
    { Name = L.Tears,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\tears.tga]] }, 
    { Name = L.Think,       Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\think.tga]] }, 
    { Name = L.Titter,      Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\titter.tga]] }, 
    { Name = L.Ugly,        Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\ugly.tga]] }, 
    { Name = L.Victory,     Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\victory.tga]] }, 
    { Name = L.Volunteer,   Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\volunteer.tga]] }, 
    { Name = L.Wronged,     Icon = [[Interface\AddOns\WowSocial_UI\Media\Icon\wronged.tga]] }, 
}

AvatarList = {
    [[Ability_Ambush]],
    [[Ability_AnimusDraw]],
    [[Ability_AnimusOrbs]],
    [[Ability_BackStab]],
    [[ability_boss_lordanthricystgreen]],
    [[Ability_BullRush]],
    [[Ability_CheapShot]],
    [[Ability_Creature_Amber_01]],
    [[Ability_Creature_Amber_02]],
    [[Ability_Creature_Cursed_01]],
    [[Ability_Creature_Cursed_02]],
    [[Ability_Creature_Cursed_03]],
    [[Ability_Creature_Cursed_04]],
    [[Ability_Creature_Cursed_05]],
    [[Ability_Creature_Disease_01]],
    [[Ability_Creature_Disease_02]],
    [[Ability_Creature_Disease_03]],
    [[Ability_Creature_Disease_04]],
    [[Ability_Creature_Disease_05]],
    [[Ability_Creature_Poison_01]],
    [[Ability_Creature_Poison_02]],
    [[Ability_Creature_Poison_03]],
    [[Ability_Creature_Poison_04]],
    [[Ability_Creature_Poison_05]],
    [[Ability_Creature_Poison_06]],
    [[Ability_CriticalStrike]],
    [[Ability_Crown_of_the_Heavens_Icon]],
    [[Ability_DeathKnight_AoeDeathGrip]],
    [[Ability_DeathKnight_Asphixiate]],
    [[ability_deathknight_boneshield]],
    [[ability_deathknight_brittlebones]],
    [[Ability_DeathKnight_DeathSiphon]],
    [[Ability_DeathKnight_DeathSiphon2]],
    [[Ability_DeathKnight_DesecratedGround]],
    [[ability_deathknight_desolation]],
    [[ability_deathknight_hemorrhagicfever]],
    [[Ability_DeathKnight_IcyGrip]],
    [[ability_deathknight_pillaroffrost]],
    [[Ability_DeathKnight_RemorselessWinters]],
    [[Ability_DeathKnight_RemorselessWinters2]],
    [[Ability_DeathKnight_RoilingBlood]],
    [[ability_deathknight_runicimpowerment]],
    [[ability_deathknight_sanguinfortitude]],
    [[Ability_DeathKnight_SoulReaper]],
    [[ability_deathknight_summongargoyle]],
    [[ability_deathwing_assualtaspects]],
    [[ability_deathwing_bloodcorruption_death]],
    [[ability_deathwing_bloodcorruption_earth]],
    [[ability_deathwing_cataclysm]],
    [[ability_deathwing_fierygrip]],
    [[ability_deathwing_grasping_tendrils]],
    [[ability_deathwing_grasping_tendrilsgreen]],
    [[Ability_deathwing_sealarmorbreachgreen]],
    [[ability_deathwing_sealarmorbreachtga]],
    [[ability_deathwing_shrapnel]],
    [[Ability_Defend]],
    [[Ability_Devour]],
    [[Ability_Druid_AquaticForm]],
    [[Ability_Druid_AstralStorm]],
    [[Ability_Druid_BalanceofPower]],
    [[Ability_Druid_Bash]],
    [[Ability_Druid_Berserk]],
    [[Ability_Druid_CatForm]],
    [[Ability_Druid_CatFormAttack]],
    [[Ability_Druid_ChallangingRoar]],
    [[Ability_Druid_Cower]],
    [[Ability_Druid_Cyclone]],
    [[Ability_Druid_Dash]],
    [[ABILITY_DRUID_DEMORALIZINGROAR]],
    [[Ability_Druid_Disembowel]],
    [[Ability_Druid_Dreamstate]],
    [[Ability_Druid_EarthandSky]],
    [[Ability_Druid_Eclipse]],
    [[Ability_Druid_EclipseOrange]],
    [[Ability_Druid_EmpoweredRejuvination]],
    [[Ability_Druid_EmpoweredTouch]],
    [[Ability_Druid_Enrage]],
    [[Ability_Druid_FerociousBite]],
    [[Ability_Druid_FlightForm]],
    [[Ability_Druid_Flourish]],
    [[Ability_Druid_ForceofNature]],
    [[Ability_Druid_GaleWinds]],
    [[Ability_Druid_GiftoftheEarthmother]],
    [[Ability_Druid_HealingInstincts]],
    [[Ability_Druid_ImprovedMoonkinForm]],
    [[Ability_Druid_ImprovedTreeForm]],
    [[Ability_Druid_InfectedWound]],
    [[Ability_Druid_KingoftheJungle]],
    [[Ability_Druid_Lacerate]],
    [[Ability_Druid_LunarGuidance]],
    [[Ability_Druid_ManaTree]],
    [[Ability_Druid_Mangle]],
    [[Ability_Druid_Mangle.tga]],
    [[Ability_Druid_Mangle2]],
    [[Ability_Druid_MasterShapeshifter]],
    [[Ability_Druid_Maul]],
    [[Ability_Druid_NaturalPerfection]],
    [[ABILITY_DRUID_NOURISH]],
    [[Ability_Druid_OwlkinFrenzy]],
    [[Ability_Druid_PredatoryInstincts]],
    [[Ability_Druid_PrimalAgression]],
    [[Ability_Druid_PrimalPrecision]],
    [[Ability_Druid_PrimalTenacity]],
    [[Ability_Druid_Prowl]],
    [[Ability_Druid_Rake]],
    [[Ability_Druid_Ravage]],
    [[Ability_Druid_Replenish]],
    [[Ability_Druid_SkinTeeth]],
    [[Ability_Druid_Starfall]],
    [[Ability_Druid_SupriseAttack]],
    [[Ability_Druid_Swipe]],
    [[Ability_Druid_TigersRoar]],
    [[Ability_Druid_TravelForm]],
    [[Ability_Druid_TreeofLife]],
    [[Ability_Druid_TwilightsWrath]],
    [[Ability_Druid_Typhoon]],
    [[Ability_DualWield]],
    [[Ability_DualWieldSpecialization]],
    [[Ability_Ensnare]],
    [[Ability_EyeOfTheOwl]],
    [[Ability_FiegnDead]],
    [[Ability_Fixated_State_Blue]],
    [[Ability_Fixated_State_Green]],
    [[Ability_Fixated_State_Orange]],
    [[Ability_Fixated_State_Purple]],
    [[Ability_Fixated_State_Red]],
    [[Ability_Fixated_State_Yellow]],
    [[Ability_Garrosh_Empowered_Whirling_Corruption]],
    [[Ability_Garrosh_Hellscreams_Warsong]],
    [[Ability_Garrosh_Siege_Engine]],
    [[Ability_Garrosh_Touch_Of_Yshaarj]],
    [[Ability_Garrosh_Whirling_Corruption]],
    [[Ability_GhoulFrenzy]],
    [[Ability_GlaiveToss]],
    [[Ability_GolemStormBolt]],
    [[Ability_GolemThunderClap]],
    [[Ability_Gouge]],
    [[Ability_HeroicLeap]],
    [[Ability_Hibernation]],
    [[Ability_Hisek_Aim]],
    [[Ability_Hunter_AimedShot]],
    [[Ability_Hunter_AnimalHandler]],
    [[Ability_Hunter_AspectMastery]],
    [[Ability_Hunter_AspectoftheFox]],
    [[Ability_Hunter_AspectoftheIronHawk]],
    [[Ability_Hunter_AspectOfTheMonkey]],
    [[Ability_Hunter_AspectoftheViper]],
    [[Ability_Hunter_Assassinate]],
    [[Ability_Hunter_Assassinate2]],
    [[Ability_Hunter_BeastCall]],
    [[Ability_Hunter_BeastCall02]],
    [[Ability_Hunter_BeastMastery]],
    [[Ability_Hunter_BeastSoothe]],
    [[Ability_Hunter_BeastTaming]],
    [[Ability_Hunter_BeastTraining]],
    [[Ability_Hunter_BeastWithin]],
    [[ABILITY_HUNTER_BESTIALDISCIPLINE]],
    [[Ability_Hunter_BlackIceTrap]],
    [[Ability_Hunter_Blindingshot]],
    [[Ability_Hunter_Camouflage]],
    [[Ability_Hunter_CatlikeReflexes]],
    [[Ability_Hunter_ChimeraShot2]],
    [[Ability_Hunter_CobraShot]],
    [[Ability_Hunter_CobraStrikes]],
    [[Ability_Hunter_CombatExperience]],
    [[Ability_Hunter_CriticalShot]],
    [[Ability_Hunter_Crossfire]],
    [[Ability_Hunter_DisarmingShot]],
    [[Ability_Hunter_Displacement]],
    [[Ability_Hunter_EagleEye]],
    [[Ability_Hunter_Efficiency]],
    [[Ability_Hunter_Efficiency_brown]],
    [[Ability_Hunter_ExplosiveShot]],
    [[Ability_Hunter_FerociousInspiration]],
    [[Ability_Hunter_Fervor]],
    [[Ability_Hunter_FocusedAim]],
    [[Ability_Hunter_FocusFire]],
    [[Ability_Hunter_GlacialTrap]],
    [[Ability_Hunter_GoForTheThroat]],
    [[Ability_Hunter_Harass]],
    [[ABILITY_HUNTER_HUNTERVSWILD]],
    [[Ability_Hunter_HuntingParty]],
    [[Ability_Hunter_ImprovedSteadyShot]],
    [[Ability_Hunter_ImprovedTracking]],
    [[Ability_Hunter_KillCommand]],
    [[Ability_Hunter_LockAndLoad]],
    [[ABILITY_HUNTER_LONGEVITY]],
    [[Ability_Hunter_LongShots]],
    [[Ability_Hunter_MarkedForDeath]],
    [[Ability_Hunter_MasterMarksman]],
    [[ABILITY_HUNTER_MASTERSCALL]],
    [[Ability_Hunter_MasterTactitian]],
    [[Ability_Hunter_MendPet]],
    [[Ability_Hunter_Misdirection]],
    [[Ability_Hunter_MurderofCrows]],
    [[Ability_Hunter_OneWithNature]],
    [[Ability_Hunter_Pathfinding]],
    [[ABILITY_HUNTER_PATHFINDING2]],
    [[Ability_Hunter_Pet_Assist]],
    [[Ability_Hunter_Pet_Bat]],
    [[Ability_Hunter_Pet_Bear]],
    [[Ability_Hunter_Pet_Boar]],
    [[Ability_Hunter_Pet_Cat]],
    [[Ability_Hunter_Pet_Chimera]],
    [[Ability_Hunter_Pet_CoreHound]],
    [[Ability_Hunter_Pet_Crab]],
    [[Ability_Hunter_Pet_Crocolisk]],
    [[Ability_Hunter_Pet_Devilsaur]],
    [[Ability_Hunter_Pet_DragonHawk]],
    [[Ability_Hunter_Pet_Gorilla]],
    [[Ability_Hunter_Pet_GoTo]],
    [[Ability_Hunter_Pet_Hyena]],
    [[Ability_Hunter_Pet_Moth]],
    [[Ability_Hunter_Pet_NetherRay]],
    [[Ability_Hunter_Pet_Owl]],
    [[Ability_Hunter_Pet_Raptor]],
    [[Ability_Hunter_Pet_Ravager]],
    [[Ability_Hunter_Pet_Rhino]],
    [[Ability_Hunter_Pet_Scorpid]],
    [[Ability_Hunter_Pet_Silithid]],
    [[Ability_Hunter_Pet_Spider]],
    [[Ability_Hunter_Pet_Sporebat]],
    [[Ability_Hunter_Pet_TallStrider]],
    [[Ability_Hunter_Pet_Turtle]],
    [[Ability_Hunter_Pet_Vulture]],
    [[Ability_Hunter_Pet_WarpStalker]],
    [[Ability_Hunter_Pet_Wasp]],
    [[Ability_Hunter_Pet_WindSerpent]],
    [[Ability_Hunter_Pet_Wolf]],
    [[Ability_Hunter_Pet_Worm]],
    [[Ability_Hunter_PiercingShots]],
    [[Ability_Hunter_PointofNoEscape]],
    [[ABILITY_HUNTER_POSTHASTE]],
    [[Ability_Hunter_PotentVenom]],
    [[Ability_Hunter_Quickshot]],
    [[Ability_Hunter_RapidKilling]],
    [[Ability_Hunter_RapidRegeneration]],
    [[Ability_Hunter_Readiness]],
    [[Ability_Hunter_ResistanceIsFutile]],
    [[Ability_Hunter_Resourcefulness]],
    [[Ability_Hunter_RunningShot]],
    [[ABILITY_HUNTER_SEPARATIONANXIETY]],
    [[Ability_Hunter_SerpentSwiftness]],
    [[ABILITY_HUNTER_SICKEM]],
    [[Ability_Hunter_SilentHunter]],
    [[Ability_Hunter_SnakeTrap]],
    [[Ability_Hunter_SniperShot]],
    [[Ability_Hunter_SniperTraining]],
    [[Ability_Hunter_SteadyShot]],
    [[Ability_Hunter_SurvivalInstincts]],
    [[Ability_Hunter_SwiftStrike]],
    [[Ability_Hunter_ThrilloftheHunt]],
    [[Ability_Hunter_TrapLauncher]],
    [[Ability_Hunter_WildQuiver]],
    [[Ability_Hunter_ZenArchery]],
    [[Ability_ImpalingBolt]],
    [[Ability_Karoz_Leap]],
    [[Ability_Kick]],
    [[Ability_Kilruk_Reave]],
    [[Ability_Mage_ArcaneBarrage]],
    [[Ability_Mage_BrainFreeze]],
    [[Ability_Mage_Burnout]],
    [[Ability_Mage_ChilledToTheBone]],
    [[Ability_Mage_ColdAsIce]],
    [[Ability_Mage_ConjureFoodRank10]],
    [[Ability_Mage_ConjureFoodRank12]],
    [[Ability_Mage_ConjureFoodRank9]],
    [[Ability_Mage_ConjureWater11]],
    [[Ability_Mage_DeepFreeze]],
    [[Ability_Mage_FieryPayback]],
    [[Ability_Mage_FireStarter]],
    [[Ability_Mage_FrostFireBolt]],
    [[Ability_Mage_FrostJaw]],
    [[ability_mage_GreaterInvisibility]],
    [[Ability_Mage_HotStreak]],
    [[Ability_Mage_ImprovedPolymorph]],
    [[Ability_Mage_IncantersAbsorbtion]],
    [[Ability_Mage_LivingBomb]],
    [[Ability_Mage_MissileBarrage]],
    [[ABILITY_MAGE_MOLTENARMOR]],
    [[Ability_Mage_NetherWindPresence]],
    [[Ability_Mage_PotentSpirit]],
    [[Ability_Mage_ShatterShield]],
    [[Ability_Mage_StudentOfTheMind]],
    [[Ability_Mage_TimeWarp]],
    [[Ability_Mage_TormentOfTheWeak]],
    [[ABILITY_MAGE_WINTERSGRASP]],
    [[Ability_Mage_WorldInFlames]],
    [[Ability_mage_worldinflamesgreen]],
    [[Ability_Malkorok_BlightofYshaarj_Green]],
    [[Ability_Malkorok_BlightofYshaarj_Red]],
    [[Ability_Malkorok_BlightofYshaarj_Yellow]],
    [[Ability_Marksmanship]],
    [[Ability_MeleeDamage]],
    [[Ability_Miling]],
    [[Ability_Monk_Ascension]],
    [[ability_monk_BlackoutKick]],
    [[Ability_monk_BoughStrike]],
    [[Ability_Monk_BreathofFire]],
    [[Ability_Monk_ChargingOxWave]],
    [[ability_Monk_ChiBrew]],
    [[Ability_Monk_ChiCocoon]],
    [[Ability_Monk_ChiWave]],
    [[Ability_Monk_ClashingOxCharge]],
    [[Ability_Monk_CracklingJadeLightning]],
    [[ability_monk_cranekick]],
    [[Ability_Monk_CraneKick_New]],
    [[Ability_Monk_DampenHarm]],
    [[Ability_Monk_DeadlyReach]],
    [[ability_monk_dpsstance]],
    [[ability_monk_dragonkick]],
    [[Ability_Monk_DrunkenHaze]],
    [[Ability_Monk_ElusiveAle]],
    [[Ability_Monk_EnergizingWine]],
    [[Ability_Monk_ExpelHarm]],
    [[Ability_Monk_ExplodingJadeBlossom]],
    [[Ability_Monk_FlyingDragonKick]],
    [[Ability_Monk_ForceSphere]],
    [[Ability_Monk_FortifyingAle]],
    [[Ability_Monk_FortifyingAle_New]],
    [[Ability_Monk_Guard]],
    [[Ability_Monk_HealthSphere]],
    [[ability_monk_Jab]],
    [[Ability_Monk_JasmineForceTea]],
    [[Ability_Monk_LeeroftheOx]],
    [[Ability_Monk_LegacyOfTheEmperor]],
    [[Ability_Monk_LegSweep]],
    [[ability_monk_PalmStrike]],
    [[Ability_Monk_Paralysis]],
    [[Ability_Monk_PowerStrikes]],
    [[Ability_Monk_PrideOfTheTiger]],
    [[Ability_Monk_Provoke]],
    [[ability_Monk_QuiPunch]],
    [[ability_monk_QuiTornado]],
    [[Ability_Monk_RenewingMists]],
    [[Ability_Monk_RisingSunKick]],
    [[ability_monk_roll]],
    [[ability_monk_roundhousekick]],
    [[Ability_Monk_RushingJadeWind]],
    [[Ability_Monk_Shuffle]],
    [[Ability_Monk_SoothingMists]],
    [[Ability_Monk_Sparring]],
    [[Ability_Monk_SpearHand]],
    [[ability_monk_staffstrike]],
    [[ability_monk_standingkick]],
    [[Ability_Monk_SummonSerpentStatue]],
    [[Ability_Monk_SummonTigerStatue]],
    [[Ability_Monk_SurgingMist]],
    [[Ability_Monk_ThunderFocusTea]],
    [[Ability_Monk_TigereyeBrandy]],
    [[Ability_Monk_TigerPalm]],
    [[Ability_Monk_TigersLust]],
    [[Ability_Monk_TouchOfDeath]],
    [[Ability_Monk_TouchofKarma]],
    [[Ability_Monk_Uplift]],
    [[Ability_Monk_ZenFlight]],
    [[Ability_Monk_ZenMeditation]],
    [[Ability_Paladin_ArtofWar]],
    [[Ability_Paladin_BeaconofLight]],
    [[Ability_Paladin_BlessedHands]],
    [[Ability_Paladin_BlessedMending]],
    [[Ability_Paladin_BlindingLight]],
    [[Ability_Paladin_BlindingLight2]],
    [[ability_Paladin_Clemency]],
    [[Ability_Paladin_Conviction]],
    [[ABILITY_PALADIN_DIVINESTORM]],
    [[Ability_Paladin_EnlightenedJudgements]],
    [[Ability_Paladin_GaurdedbytheLight]],
    [[Ability_Paladin_HammeroftheRighteous]],
    [[Ability_Paladin_HolyAvenger]],
    [[Ability_Paladin_InfusionofLight]],
    [[Ability_Paladin_JudgementBlue]],
    [[Ability_Paladin_JudgementofthePure]],
    [[Ability_Paladin_JudgementoftheWise]],
    [[Ability_Paladin_JudgementRed]],
    [[Ability_Paladin_JudgementsoftheJust]],
    [[Ability_Paladin_LongArmoftheLaw]],
    [[Ability_Paladin_ProtectorOfTheInnocent]],
    [[Ability_Paladin_RighteousVengeance]],
    [[Ability_Paladin_SacredCleansing]],
    [[Ability_Paladin_SanctifiedWrath]],
    [[Ability_Paladin_SelflessHealer]],
    [[Ability_Paladin_SheathofLight]],
    [[Ability_Paladin_ShieldoftheTemplar]],
    [[Ability_Paladin_ShieldofVengeance]],
    [[Ability_Paladin_SpeedofLight]],
    [[Ability_Paladin_SwiftRetribution]],
    [[Ability_Paladin_TouchedbyLight]],
    [[Ability_Paladin_TurnEvil]],
    [[ability_Paladin_Veneration]],
    [[Ability_Parry]],
    [[Ability_Pet_Baneling]],
    [[Ability_Physical_Taunt]],
    [[Ability_PierceDamage]],
    [[Ability_PoisonArrow]],
    [[ABILITY_POISONS]],
    [[ABILITY_POISONSTING]],
    [[Ability_Priest_AngelicBulwark]],
    [[Ability_Priest_AngelicFeather]],
    [[Ability_Priest_Archangel]],
    [[Ability_Priest_Atonement]],
    [[Ability_Priest_BindingPrayers]],
    [[Ability_Priest_Cascade]],
    [[Ability_Priest_Cascade_Shadow]],
    [[Ability_Priest_Darkness]],
    [[Ability_Priest_Evangelism]],
    [[Ability_Priest_Flashoflight]],
    [[Ability_Priest_FocusedWill]],
    [[Ability_Priest_Halo]],
    [[Ability_Priest_Halo_Shadow]],
    [[Ability_Priest_HeavanlyVoice]],
    [[Ability_Priest_PathofTheDevout]],
    [[Ability_Priest_Phantasm]],
    [[Ability_Priest_ReflectiveShield]],
    [[Ability_Priest_ShadowyApparition]],
    [[Ability_Priest_Silence]],
    [[Ability_Priest_SoulWarding]],
    [[Ability_Priest_SurgeOfDarkness]],
    [[Ability_Priest_VoidShift]],
    [[Ability_Racial_Aberration]],
    [[Ability_Racial_Avatar]],
    [[Ability_Racial_BearForm]],
    [[Ability_Racial_BestDealsAnywhere]],
    [[Ability_Racial_BetterLivingThroughChemistry]],
    [[Ability_Racial_BloodRage]],
    [[Ability_Racial_Cannibalize]],
    [[Ability_Racial_Darkflight]],
    [[Ability_Racial_Flayer]],
    [[Ability_Racial_PackHobgoblin]],
    [[Ability_Racial_RocketBarrage]],
    [[Ability_Racial_RocketJump]],
    [[Ability_Racial_RunningWild]],
    [[Ability_Racial_ShadowMeld]],
    [[Ability_Racial_TimeIsMoney]],
    [[Ability_Racial_TwoForms]],
    [[Ability_Racial_Ultravision]],
    [[Ability_Repair]],
    [[Ability_RewindTime]],
    [[Ability_Rhyolith_Immolation]],
    [[Ability_Rhyolith_LavaPool]],
    [[Ability_Rhyolith_MagmaFlow_Wave]],
    [[Ability_Rhyolith_MagmaFlow_Whole]],
    [[Ability_Rhyolith_Volcano]],
    [[Ability_Rikkal_Genetics]],
    [[Ability_Rogue_Ambush]],
    [[ability_rogue_blackjack]],
    [[Ability_Rogue_BladeTwisting]],
    [[Ability_Rogue_BloodSplatter]],
    [[Ability_Rogue_BloodyEye]],
    [[Ability_Rogue_CheatDeath]],
    [[ability_rogue_combatexpertise]],
    [[ability_rogue_combatexpertisetga]],
    [[ability_rogue_combatreadiness]],
    [[Ability_Rogue_CutToTheChase]],
    [[Ability_Rogue_DeadenedNerves]],
    [[ability_rogue_deadliness]],
    [[Ability_Rogue_DeadlyBrew]],
    [[ability_rogue_deadlymomentum]],
    [[Ability_Rogue_DeviousPoisons]],
    [[ability_rogue_dirtydeeds]],
    [[Ability_Rogue_Disembowel]],
    [[Ability_Rogue_Disguise]],
    [[Ability_Rogue_Dismantle]],
    [[Ability_Rogue_Distract]],
    [[Ability_Rogue_DualWeild]],
    [[ability_rogue_energeticrecovery]],
    [[Ability_Rogue_EnvelopingShadows]],
    [[Ability_Rogue_Eviscerate]],
    [[Ability_Rogue_FanofKnives]],
    [[Ability_Rogue_FeignDeath]],
    [[Ability_Rogue_Feint]],
    [[Ability_Rogue_FindWeakness]],
    [[Ability_Rogue_FleetFooted]],
    [[Ability_Rogue_FocusedAttacks]],
    [[Ability_Rogue_Garrote]],
    [[Ability_Rogue_HonorAmongstThieves]],
    [[Ability_Rogue_HungerforBlood]],
    [[ability_rogue_improvedrecuperate]],
    [[ability_rogue_imrovedrecuperate]],
    [[Ability_Rogue_KidneyShot]],
    [[Ability_Rogue_MasterOfSubtlety]],
    [[Ability_Rogue_MurderSpree]],
    [[Ability_Rogue_NervesOfSteel]],
    [[ability_rogue_preparation]],
    [[Ability_Rogue_PreyontheWeak]],
    [[Ability_Rogue_QuickRecovery]],
    [[ability_rogue_recuperate]],
    [[ability_rogue_redirect]],
    [[ability_rogue_reinforcedleather]],
    [[ability_rogue_restlessblades]],
    [[Ability_Rogue_Rupture]],
    [[ability_rogue_ruthlessness]],
    [[ability_rogue_sanguinaryvein]],
    [[ability_rogue_sealfate]],
    [[Ability_Rogue_ShadowDance]],
    [[Ability_Rogue_Shadowstep]],
    [[Ability_Rogue_ShadowStrikes]],
    [[Ability_Rogue_ShroudOfConcealment]],
    [[Ability_Rogue_SinisterCalling]],
    [[Ability_Rogue_SlaughterfromtheShadows]],
    [[Ability_Rogue_SliceDice]],
    [[ability_rogue_smoke]],
    [[Ability_Rogue_Sprint]],
    [[Ability_Rogue_StayofExecution]],
    [[ability_rogue_sturdyrecuperate]],
    [[Ability_Rogue_SurpriseAttack]],
    [[Ability_Rogue_SurpriseAttack2]],
    [[Ability_Rogue_ThrowingSpecialization]],
    [[Ability_Rogue_TricksOftheTrade]],
    [[Ability_Rogue_Trip]],
    [[Ability_Rogue_TurntheTables]],
    [[Ability_Rogue_UnfairAdvantage]],
    [[ability_rogue_venomouswounds]],
    [[Ability_Rogue_Versatility]],
    [[ability_rogue_vigor]],
    [[Ability_Rogue_Waylay]],
    [[Ability_Rogue_WrongfullyAccused]],
    [[ABILITY_SAP]],
    [[ABILITY_SEAL]],
    [[ABILITY_SEARINGARROW]],
    [[Ability_Shaman_AncestralGuidance]],
    [[Ability_Shaman_Ascendance]],
    [[Ability_Shaman_AstralShift]],
    [[Ability_Shaman_CleanseSpirit]],
    [[Ability_Shaman_EchooftheElements]],
    [[Ability_Shaman_FortifyingWaters]],
    [[Ability_Shaman_FreedomWolf]],
    [[Ability_Shaman_HealingTide]],
    [[Ability_Shaman_Heroism]],
    [[Ability_Shaman_Lavalash]],
    [[Ability_Shaman_MultiTotemActivation]],
    [[Ability_Shaman_RepulsionTotem]],
    [[Ability_Shaman_StoneBulwark]],
    [[Ability_Shaman_Stormstrike]],
    [[Ability_Shaman_TotemCooldownRefund]],
    [[Ability_Shaman_TotemRelocation]],
    [[Ability_Shaman_TranquilMindTotem]],
    [[Ability_Shaman_WaterShield]],
    [[Ability_Shaman_WindwalkTotem]],
    [[Ability_ShaWaterElemental_Reform]],
    [[Ability_ShaWaterElemental_Split]],
    [[Ability_ShaWaterElemental_Swirl]],
    [[Ability_ShockWave]],
    [[ABILITY_SHOOTWAND]],
    [[Ability_Siege_Engineer_Automatic_repair_beam]],
    [[Ability_Siege_Engineer_Death_from_above]],
    [[Ability_Siege_Engineer_detonate]],
    [[Ability_Siege_Engineer_Magnetic_Crush]],
    [[Ability_Siege_Engineer_Magnetic_Lasso]],
    [[Ability_Siege_Engineer_Overload]],
    [[Ability_Siege_Engineer_pattern_recognition]],
    [[Ability_Siege_Engineer_Protective_Frenzy]],
    [[Ability_Siege_Engineer_Purification_beam]],
    [[Ability_Siege_Engineer_Sockwave_Missile]],
    [[Ability_Siege_Engineer_Superheated]],
    [[Ability_Skeer_BloodLetting]],
    [[Ability_Smash]],
    [[Ability_Spy]],
    [[Ability_Stealth]],
    [[Ability_SteelMelee]],
    [[Ability_Suffocate]],
    [[ability_tetanus]],
    [[Ability_TheBlackArrow]],
    [[Ability_Throw]],
    [[Ability_ThunderBolt]],
    [[Ability_ThunderClap]],
    [[Ability_ThunderKing_BallLightning]],
    [[Ability_ThunderKing_Decapitate]],
    [[Ability_ThunderKing_KickShell]],
    [[Ability_ThunderKing_LightningWhip]],
    [[Ability_ThunderKing_Maim]],
    [[Ability_ThunderKing_Overcharge]],
    [[Ability_ThunderKing_RockfallHigh]],
    [[Ability_ThunderKing_RockfallLow]],
    [[Ability_ThunderKing_SpinningShell]],
    [[Ability_ThunderKing_Thunderstruck]],
    [[Ability_TitanKeeper_Amalgam]],
    [[Ability_TitanKeeper_Cleanse]],
    [[Ability_TitanKeeper_CleansingOrb]],
    [[Ability_TitanKeeper_Corrupt]],
    [[Ability_TitanKeeper_CorruptionDot]],
    [[Ability_TitanKeeper_ExpelCorruption]],
    [[Ability_TitanKeeper_ExtractCorruption]],
    [[Ability_TitanKeeper_Phasing]],
    [[Ability_TitanKeeper_PiercingCorruption]],
    [[Ability_TitanKeeper_Quarantine]],
    [[Ability_TitanKeeper_ResidualCorruption]],
    [[Ability_TitanKeeper_TestofConfidence]],
    [[Ability_TitanKeeper_TestofSerenity]],
    [[Ability_TitanKeeper_TitanicSmash]],
    [[Ability_TitanKeeper_UncheckedCorruption]],
    [[Ability_TouchofAnimus]],
    [[ability_toughness]],
    [[Ability_TownWatch]],
    [[Ability_Tracking]],
    [[Ability_TrueShot]],
    [[Ability_UpgradeMoonGlaive]],
    [[Ability_Vanish]],
    [[Ability_Vehicle_DemolisherFlameCatapult]],
    [[Ability_Vehicle_DemolisherRam]],
    [[Ability_Vehicle_ElectroCharge]],
    [[Ability_Vehicle_LaunchPlayer]],
    [[Ability_Vehicle_LiquidPyrite]],
    [[Ability_Vehicle_LiquidPyrite_blue]],
    [[Ability_Vehicle_LoadSelfCatapult]],
    [[Ability_Vehicle_OilJets]],
    [[Ability_Vehicle_PlagueBarrel]],
    [[Ability_Vehicle_PlayerLoaded]],
    [[Ability_Vehicle_PowertoWheels]],
    [[Ability_Vehicle_ReloadAmmo]],
    [[Ability_Vehicle_RocketBoost]],
    [[Ability_Vehicle_ShellShieldGenerator]],
    [[Ability_Vehicle_SiegeEngineCannon]],
    [[Ability_Vehicle_SiegeEngineCharge]],
    [[Ability_Vehicle_SiegeEngineRam]],
    [[Ability_Vehicle_SonicShockwave]],
    [[ability_warlock_ancientgrimoire]],
    [[Ability_Warlock_Avoidance]],
    [[Ability_Warlock_Backdraft]],
    [[Ability_warlock_backdraftgreen]],
    [[ability_warlock_baneofhavoc]],
    [[ability_warlock_burningembers]],
    [[Ability_warlock_burningembersgreen]],
    [[Ability_Warlock_ChaosBolt]],
    [[ability_warlock_Coil2]],
    [[ability_warlock_Coil3]],
    [[ability_warlock_darkarts]],
    [[Ability_Warlock_DemonicEmpowerment]],
    [[Ability_Warlock_DemonicPower]],
    [[Ability_Warlock_EmpoweredImp]],
    [[Ability_Warlock_EverlastingAffliction]],
    [[Ability_Warlock_FireandBrimstone]],
    [[Ability_warlock_fireandbrimstonegreen]],
    [[ability_warlock_handofguldan]],
    [[Ability_Warlock_Haunt]],
    [[Ability_warlock_HowlofTerror]],
    [[Ability_Warlock_ImprovedDemonicTactics]],
    [[ability_warlock_inferno]],
    [[Ability_Warlock_infernogreen]],
    [[Ability_Warlock_MoltenCore]],
    [[ability_warlock_moltencoregreen]],
    [[ability_warlock_MortalCoil]],
    [[Ability_Warlock_ShadowFlame]],
    [[ability_warlock_shadowfurytga]],
    [[ability_warlock_SoulLink]],
    [[ability_warlock_soulsiphon]],
    [[ability_warlock_soulswap]],
    [[ability_warlock_whiplash]],
    [[Ability_Warrior_BattleShout]],
    [[Ability_Warrior_Bladestorm]],
    [[Ability_Warrior_BloodBath]],
    [[Ability_Warrior_BloodFrenzy]],
    [[Ability_Warrior_BloodNova]],
    [[Ability_Warrior_Bloodsurge]],
    [[Ability_Warrior_BullRush]],
    [[Ability_Warrior_Challange]],
    [[Ability_Warrior_Charge]],
    [[Ability_Warrior_Cleave]],
    [[Ability_Warrior_ColossusSmash]],
    [[Ability_Warrior_CommandingShout]],
    [[Ability_Warrior_CriticalBlock]],
    [[Ability_Warrior_DecisiveStrike]],
    [[Ability_Warrior_DefensiveStance]],
    [[Ability_Warrior_Devastate]],
    [[Ability_Warrior_Disarm]],
    [[Ability_Warrior_DragonRoar]],
    [[Ability_Warrior_EndlessRage]],
    [[Ability_Warrior_FocusedRage]],
    [[Ability_Warrior_FuriousResolve]],
    [[Ability_Warrior_ImprovedDisciplines]],
    [[Ability_Warrior_Incite]],
    [[Ability_Warrior_InnerRage]],
    [[Ability_Warrior_IntensifyRage]],
    [[Ability_Warrior_Intervene]],
    [[Ability_Warrior_OffensiveStance]],
    [[Ability_Warrior_PunishingBlow]],
    [[Ability_Warrior_RallyingCry]],
    [[Ability_Warrior_Rampage]],
    [[Ability_Warrior_Revenge]],
    [[Ability_Warrior_Riposte]],
    [[Ability_Warrior_Safeguard]],
    [[Ability_Warrior_SavageBlow]],
    [[Ability_Warrior_SecondWind]],
    [[Ability_Warrior_ShatteringThrow]],
    [[Ability_Warrior_ShieldBash]],
    [[Ability_Warrior_ShieldBreak]],
    [[Ability_Warrior_ShieldGuard]],
    [[Ability_Warrior_ShieldMastery]],
    [[Ability_Warrior_ShieldReflection]],
    [[Ability_Warrior_ShieldWall]],
    [[Ability_Warrior_Shockwave]],
    [[Ability_Warrior_StalwartProtector]],
    [[Ability_Warrior_StrengthOfArms]],
    [[Ability_Warrior_Sunder]],
    [[Ability_Warrior_SwordandBoard]],
    [[Ability_Warrior_Throwdown]],
    [[Ability_Warrior_Throwdown_2]],
    [[Ability_Warrior_TitansGrip]],
    [[Ability_Warrior_Trauma]],
    [[Ability_Warrior_UnrelentingAssault]],
    [[Ability_Warrior_VictoryRush]],
    [[Ability_Warrior_Vigilance]],
    [[Ability_Warrior_Warbringer]],
    [[Ability_Warrior_WarCry]],
    [[Ability_WarStomp]],
    [[Ability_Whirlwind]],
    [[Ability_Worgen_DarkFlight]],
    [[achievment_Boss_Blackhorn]],
    [[achievment_Boss_Hagara]],
    [[achievment_Boss_Madnessofdeathwing]],
    [[achievment_Boss_morchok]],
    [[achievment_Boss_spineofdeathwing]],
    [[achievment_Boss_ultraxion]],
    [[achievment_Boss_wellofeternity]],
    [[achievment_Boss_yorsahj]],
    [[achievment_Boss_zonozz]],
    [[achievment_raid_houroftwilight]],
    [[Archaeology_5_0_AnatomicalDummy]],
    [[Archaeology_5_0_ApothecaryTins]],
    [[Archaeology_5_0_CarvedBronzeMirror]],
    [[Archaeology_5_0_ChangKiBoard]],
    [[Archaeology_5_0_CrackedMoguRunestone]],
    [[Archaeology_5_0_EdictsOfTheThunderKing]],
    [[Archaeology_5_0_EmptyKegOfBrewfatherXinWoYin]],
    [[Archaeology_5_0_GoldInlaidPorcelainFuneraryFigurine]],
    [[Archaeology_5_0_IronAmulet]],
    [[Archaeology_5_0_Keystone_Mogu]],
    [[Archaeology_5_0_Keystone_Pandaren]],
    [[Archaeology_5_0_ManaclesOfRebellion]],
    [[Archaeology_5_0_MoguCoin]],
    [[Archaeology_5_0_PandarenTeaSet]],
    [[Archaeology_5_0_PearlOfYulon]],
    [[Archaeology_5_0_PetrifiedBoneWhip]],
    [[Archaeology_5_0_QuilenStatuette]],
    [[Archaeology_5_0_SpearOfXuen]],
    [[Archaeology_5_0_StandardOfNuzao]],
    [[Archaeology_5_0_TerracottaArm]],
    [[Archaeology_5_0_ThunderKingInsignia]],
    [[Archaeology_5_0_TwinSteinSetOfBrewfatherQuanTouKuo]],
    [[Archaeology_5_0_UmbrellaOfChiJi]],
    [[Archaeology_5_0_WalkingCaneOfBrewfatherRenYun]],
    [[Archaeology_5_0_WarlordsBrandingIron]],
    [[Archaeology_5_0_WornMonumentLedger]],
    [[Axe_1H_Draenei_B_01]],
    [[Axe_1H_Horde_D_04_icon]],
    [[Axe_2H_AhnQiraj_D_02_icon]],
    [[Bow_1h_430Future_C_01]],
    [[BOW_1H_PVP400_C_01]],
    [[braised_turtle3]],
    [[ClassIcon_DeathKnight]],
    [[ClassIcon_Druid]],
    [[ClassIcon_Hunter]],
    [[ClassIcon_Mage]],
    [[ClassIcon_Monk]],
    [[ClassIcon_Paladin]],
    [[ClassIcon_Priest]],
    [[ClassIcon_Rogue]],
    [[ClassIcon_Shaman]],
    [[ClassIcon_Warlock]],
    [[ClassIcon_Warrior]],
    [[Class_Monk]],
    [[Creatureportrait_AltarofAir_01]],
    [[Creatureportrait_AltarofEarth_01]],
    [[Creatureportrait_AltarofFlame]],
    [[Creatureportrait_AltarofFrost_01]],
    [[Creatureportrait_BE_ScryingOrb_Epic]],
    [[Creatureportrait_Blackrockv2_Shieldgong]],
    [[Creatureportrait_Blackrockv2_Shieldgong_02]],
    [[Creatureportrait_Blackrockv2_Shieldgong_Broken]],
    [[Creatureportrait_Blackrock_ChainsOfWoe]],
    [[Creatureportrait_Bubble]],
    [[Creatureportrait_Cannon03]],
    [[Creatureportrait_Creature_Iceblock]],
    [[Creatureportrait_Cyclone_Nodebris]],
    [[Creatureportrait_Darkshoreboat]],
    [[Creatureportrait_FK_PlagueBarrel]],
    [[Creatureportrait_Garalon]],
    [[Creatureportrait_Goblin_Rocket]],
    [[Creatureportrait_G_Bomb_02]],
    [[Creatureportrait_IllidanCrystal01]],
    [[Creatureportrait_infernal_ball_02]],
    [[Creatureportrait_Mageportal_Undercity]],
    [[Creatureportrait_Nexus_Floating_Disc]],
    [[Creatureportrait_Plague Sprayer]],
    [[Creatureportrait_portal_alteracvalleyhorde]],
    [[Creatureportrait_Portal_ArathiBasinAlliance]],
    [[Creatureportrait_portal_arathibasinhorde]],
    [[Creatureportrait_Portal_EyeOfTheStormAlliance]],
    [[Creatureportrait_portal_eyeofthestormhorde]],
    [[Creatureportrait_Portal_isleofconquestAlliance]],
    [[Creatureportrait_portal_isleofconquesthorde]],
    [[Creatureportrait_portal_strandoftheancients]],
    [[Creatureportrait_portal_warsonggulchhorde]],
    [[Creatureportrait_Pygmy_Drums_02]],
    [[Creatureportrait_RopeLadder01]],
    [[Creatureportrait_Saberworg]],
    [[Creatureportrait_Saltwater_Star]],
    [[Creatureportrait_SC_Blighter]],
    [[Creatureportrait_SC_EyeofAcherus_02]],
    [[Creatureportrait_SC_Wagon]],
    [[Creatureportrait_TwilightsHammer_DragonEgg_01]],
    [[Creatureportrait_TwilightsHammer_DragonEgg_02]],
    [[Creatureportrait_TwilightsHammer_DragonEgg_Red_01]],
    [[Creatureportrait_Twilightshammer_lava_magicball]],
    [[Creatureportrait_TwilightsHammer_MagicalDevice_04]],
    [[Creatureportrait_TwilightsHammer_SummoningPortal_Water01]],
    [[Creatureportrait_UL_Chandelier]],
    [[Creature_SporeMushroom]],
    [[Demoralizing_banner]],
    [[Druid_Ability_Wildmushroom_a]],
    [[Druid_Ability_Wildmushroom_b]],
    [[ExpansionIcon_BurningCrusade]],
    [[ExpansionIcon_Cataclysm]],
    [[ExpansionIcon_Classic]],
    [[ExpansionIcon_MistsofPandaria]],
    [[ExpansionIcon_WrathoftheLichKing]],
    [[Firearm_2H_Rifle_PVP400_C_01]],
    [[Icon_Scenarios]],
    [[Item_enchantedpearl]],
    [[Item_Fierysilkgland]],
    [[Item_SocketedBracer]],
    [[Item_sparkofragnoros]],
    [[Mocking_Banner]],
    [[Monk_Ability_AvertHarm]],
    [[Monk_Ability_CherryManaTea]],
    [[Monk_Ability_FistofFury]],
    [[Monk_Ability_SummonOxStatue]],
    [[Monk_Ability_Transcendence]],
    [[Monk_Stance_DrunkenOx]],
    [[Monk_Stance_WhiteTiger]],
    [[Monk_Stance_WiseSerpent]],
    [[NV_Boots_Cloth_PVPWarlock_C_01]],
    [[PALADIN_HOLY]],
    [[Paladin_icon_speedoflight]],
    [[Paladin_Protection]],
    [[Paladin_Retribution]],
    [[PandarenRacial_Bouncy]],
    [[PandarenRacial_Epicurean]],
    [[PandarenRacial_Gourmand]],
    [[PandarenRacial_InnerPeace]],
    [[Plate_RaidDeathKnight_K_01_Belt]],
    [[Plate_RaidDeathKnight_K_01_Boot]],
    [[Plate_RaidDeathKnight_K_01_Bracer]],
    [[Plate_RaidDeathKnight_K_01_Chest]],
    [[Plate_RaidDeathKnight_K_01_Glove]],
    [[Plate_RaidDeathKnight_K_01_Helm]],
    [[Plate_RaidDeathKnight_K_01_Pant]],
    [[Plate_RaidDeathKnight_K_01_Shoulder]],
    [[Polearm_2h_DeathwingRaidDW_D_01]],
    [[Portal_AlteracValleyAlliance]],
    [[Portal_WarsongGulchAlliance]],
    [[Priest_icon_Chakra]],
    [[Priest_icon_Chakra_blue]],
    [[Priest_icon_Chakra_green]],
    [[Priest_icon_Chakra_red]],
    [[Priest_icon_InneWill]],
    [[Priest_spell_leapoffaith_a]],
    [[Priest_spell_leapoffaith_b]],
    [[Racial_Dwarf_FindTreasure]],
    [[RACIAL_ORC_BERSERKERSTRENGTH]],
    [[RACIAL_TROLL_BERSERK]],
    [[Raf-Icon]],
    [[Rogue_BurstofSpeed]],
    [[Rogue_DirtyTricks]],
    [[Rogue_Leeching_Poison]],
    [[Rogue_Nerve _Strike]],
    [[Rogue_Paralytic_Poison]],
    [[Rogue_ShadowFocus]],
    [[Rogue_Subterfuge]],
    [[Secrets_of_the_Empire_Icon]],
    [[Shaman_talent_ElementalBlast]],
    [[Shaman_talent_PrimalElementalist]],
    [[Shaman_talent_UnleashedFury]],
    [[SOR-mail]],
    [[Spell_Arcane_Arcane01]],
    [[Spell_Arcane_Arcane02]],
    [[Spell_Arcane_Arcane03]],
    [[Spell_Arcane_Arcane04]],
    [[Spell_Arcane_ArcanePotency]],
    [[Spell_Arcane_ArcaneResilience]],
    [[Spell_Arcane_ArcaneTactics]],
    [[Spell_Arcane_ArcaneTorrent]],
    [[Spell_Arcane_Blast]],
    [[Spell_Arcane_Blink]],
    [[Spell_Arcane_FocusedPower]],
    [[Spell_Arcane_ManaTap]],
    [[Spell_Arcane_MassDispel]],
    [[Spell_Arcane_MindMastery]],
    [[Spell_Arcane_PortalDalaran]],
    [[Spell_Arcane_PortalDalaranCrater]],
    [[Spell_Arcane_PortalDarnassus]],
    [[Spell_Arcane_PortalExodar]],
    [[Spell_Arcane_PortalIronForge]],
    [[Spell_Arcane_PortalOrgrimmar]],
    [[Spell_Arcane_PortalShattrath]],
    [[Spell_Arcane_PortalSilvermoon]],
    [[Spell_Arcane_PortalStonard]],
    [[Spell_Arcane_PortalStormWind]],
    [[Spell_Arcane_PortalTheramore]],
    [[Spell_Arcane_PortalThunderBluff]],
    [[Spell_Arcane_PortalTolBarad]],
    [[Spell_Arcane_PortalUnderCity]],
    [[Spell_arcane_portal_valeofblossoms]],
    [[Spell_Arcane_PrismaticCloak]],
    [[Spell_Arcane_Rune]],
    [[Spell_Arcane_StarFire]],
    [[Spell_Arcane_StudentOfMagic]],
    [[Spell_Arcane_TeleportDalaran]],
    [[Spell_Arcane_TeleportDalaranCrater]],
    [[Spell_Arcane_TeleportDarnassus]],
    [[Spell_Arcane_TeleportExodar]],
    [[Spell_Arcane_TeleportIronForge]],
    [[SPELL_ARCANE_TELEPORTMOONGLADE]],
    [[Spell_Arcane_TeleportOrgrimmar]],
    [[Spell_Arcane_TeleportShattrath]],
    [[Spell_Arcane_TeleportSilvermoon]],
    [[Spell_Arcane_TeleportStonard]],
    [[Spell_Arcane_TeleportStormWind]],
    [[Spell_Arcane_TeleportTheramore]],
    [[Spell_Arcane_TeleportThunderBluff]],
    [[Spell_Arcane_TeleportTolBarad]],
    [[Spell_Arcane_TeleportUnderCity]],
    [[spell_arcane_valeofblossoms]],
    [[spell_brew_bolt_dark]],
    [[spell_brew_bolt_medium]],
    [[spell_brew_bolt_wheat]],
    [[spell_brew_dark]],
    [[spell_brew_medium]],
    [[spell_brew_wheat]],
    [[Spell_BrokenHeart]],
    [[Spell_BurningSoul]],
    [[Spell_ChargeNegative]],
    [[Spell_ChargePositive]],
    [[Spell_DeathKnight_AntiMagicZone]],
    [[Spell_DeathKnight_ArmyOfTheDead]],
    [[Spell_DeathKnight_BladedArmor]],
    [[Spell_DeathKnight_BloodPlague]],
    [[Spell_Deathknight_BloodPresence]],
    [[Spell_DeathKnight_BloodTap]],
    [[Spell_DeathKnight_Butcher]],
    [[Spell_Deathknight_ClassIcon]],
    [[Spell_DeathKnight_DarkConviction]],
    [[Spell_Deathknight_DeathStrike]],
    [[Spell_DeathKnight_EmpowerRuneBlade]],
    [[Spell_DeathKnight_EmpowerRuneBlade2]],
    [[Spell_DeathKnight_Explode_Ghoul]],
    [[Spell_DeathKnight_Festering_strike]],
    [[Spell_DeathKnight_FrostFever]],
    [[Spell_Deathknight_FrostPresence]],
    [[Spell_DeathKnight_FrozenRuneWeapon]],
    [[Spell_DeathKnight_IceBoundFortitude]],
    [[Spell_DeathKnight_IceTouch]],
    [[Spell_Deathknight_IcyTalons]],
    [[Spell_DeathKnight_MindFreeze]],
    [[Spell_DeathKnight_PathOfFrost]],
    [[Spell_Deathknight_PlagueStrike]],
    [[Spell_DeathKnight_RuneTap]],
    [[Spell_DeathKnight_ScourgeStrike]],
    [[Spell_DeathKnight_SpellDeflection]],
    [[Spell_DeathKnight_Strangulate]],
    [[Spell_DeathKnight_Subversion]],
    [[Spell_DeathKnight_SummonDeathCharger]],
    [[Spell_DeathKnight_Thrash_Ghoul]],
    [[Spell_Deathknight_UnholyPresence]],
    [[Spell_DeathKnight_Vendetta]],
    [[Spell_deathvortex]],
    [[Spell_druid_astralstorm]],
    [[Spell_druid_bearhug]],
    [[Spell_druid_displacement]],
    [[Spell_Druid_feralchargecat]],
    [[Spell_druid_incarnation]],
    [[Spell_druid_ironbark]],
    [[Spell_druid_massentanglement]],
    [[Spell_druid_mightofursoc]],
    [[Spell_Druid_stamedingroar]],
    [[Spell_Druid_stampedingroar_cat]],
    [[Spell_druid_swarm]],
    [[Spell_druid_symbiosis]],
    [[spell_druid_thrash]],
    [[Spell_druid_tirelesspursuit]],
    [[Spell_druid_ursolsvortex]],
    [[Spell_druid_wildburst]],
    [[Spell_druid_wildcharge]],
    [[spell_Druid_Wildmushroom]],
    [[Spell_druid_wildmushroom_bloom]],
    [[Spell_druid_wildmushroom_frenzy]],
    [[Spell_Fel_ElementalDevastation]],
    [[Spell_Fel_FireBolt]],
    [[Spell_Fel_Incinerate]],
    [[Spell_festergutgas]],
    [[Spell_FireFrost Orb]],
    [[Spell_FireResistanceTotem_01]],
    [[Spell_Fire_BlueCano]],
    [[Spell_Fire_BlueFire]],
    [[Spell_Fire_BlueFireNova]],
    [[Spell_Fire_BlueFireward]],
    [[Spell_Fire_BlueFlameBolt]],
    [[Spell_Fire_BlueFlameBreath]],
    [[Spell_Fire_BlueFlameRing]],
    [[Spell_Fire_BlueFlameStrike]],
    [[Spell_Fire_BlueHellfire]],
    [[Spell_Fire_BlueImmolation]],
    [[Spell_Fire_BluePyroblast]],
    [[Spell_Fire_BlueRainOfFire]],
    [[Spell_Fire_BurningSpeed]],
    [[Spell_Fire_Burnout]],
    [[Spell_fire_burnoutgreen]],
    [[SPELL_FIRE_ELEMENTALDEVASTATION]],
    [[Spell_Fire_Elemental_Totem]],
    [[Spell_Fire_EnchantWeapon]],
    [[Spell_Fire_Felcano]],
    [[Spell_Fire_FelFire]],
    [[Spell_Fire_FelFireNova]],
    [[Spell_Fire_FelFireward]],
    [[Spell_Fire_FelFlameBolt]],
    [[Spell_Fire_FelFlameBreath]],
    [[Spell_Fire_FelFlameRing]],
    [[Spell_Fire_FelFlameStrike]],
    [[Spell_Fire_FelHellfire]],
    [[Spell_Fire_FelImmolation]],
    [[Spell_Fire_FelPyroblast]],
    [[Spell_Fire_FelRainOfFire]],
    [[Spell_Fire_Fire]],
    [[Spell_Fire_FireArmor]],
    [[Spell_Fire_Fireball]],
    [[Spell_Fire_Fireball02]],
    [[Spell_fire_fireballgreen]],
    [[Spell_fire_fireballgreen2]],
    [[Spell_Fire_FireBolt]],
    [[Spell_Fire_FireBolt02]],
    [[Spell_Fire_FlameBlades]],
    [[Spell_Fire_FlameBolt]],
    [[Spell_Fire_FlameShock]],
    [[Spell_Fire_FlameTounge]],
    [[Spell_Fire_Flare]],
    [[Spell_Fire_FrostResistanceTotem]],
    [[Spell_Fire_Immolation]],
    [[Spell_Fire_Incinerate]],
    [[Spell_Fire_LavaSpawn]],
    [[Spell_Fire_MasterOfElements]],
    [[Spell_Fire_MeteorStorm]],
    [[Spell_Fire_MoltenBlood]],
    [[Spell_fire_moltenbloodgreen]],
    [[Spell_Fire_PlayingWithFire]],
    [[Spell_fire_playingwithfiregreen]],
    [[Spell_Fire_Ragnaros_LavaBolt]],
    [[Spell_fire_ragnaros_lavaboltgreen]],
    [[Spell_Fire_Ragnaros_MoltenInferno]],
    [[Spell_fire_ragnaros_molteninfernogreen]],
    [[Spell_Fire_Ragnaros_SplittingBlow]],
    [[Spell_Fire_Ragnaros_Supernova]],
    [[Spell_Fire_Rune]],
    [[Spell_Fire_SealOfFire]],
    [[Spell_Fire_SearingTotem]],
    [[Spell_Fire_SelfDestruct]],
    [[Spell_Fire_SoulBurn]],
    [[Spell_Fire_SunKey]],
    [[Spell_Fire_TotemOfWrath]],
    [[Spell_Fire_TwilightCano]],
    [[Spell_Fire_TwilightFire]],
    [[Spell_Fire_TwilightFireward]],
    [[Spell_Fire_TwilightFlameBolt]],
    [[Spell_Fire_TwilightFlameBreath]],
    [[Spell_Fire_TwilightFlameStrike]],
    [[Spell_Fire_TwilightHellfire]],
    [[Spell_Fire_TwilightImmolation]],
    [[Spell_Fire_TwilightNova]],
    [[Spell_Fire_TwilightPyroblast]],
    [[Spell_Fire_TwilightRainOfFire]],
    [[Spell_Fire_Volcano]],
    [[Spell_Fire_WindsofWoe]],
    [[Spell_Frostfire Orb]],
    [[Spell_FrostResistanceTotem_01]],
    [[Spell_Frost_ArcticWinds]],
    [[Spell_Frost_ChainsOfIce]],
    [[Spell_Frost_ChillingArmor]],
    [[Spell_Frost_ChillingBlast]],
    [[Spell_Frost_ChillingBolt]],
    [[Spell_Frost_ColdHearted]],
    [[Spell_Frost_FireResistanceTotem]],
    [[Spell_Frost_FreezingBreath]],
    [[Spell_Frost_Frost]],
    [[Spell_Frost_FrostArmor]],
    [[Spell_Frost_FrostArmor02]],
    [[Spell_Frost_FrostBlast]],
    [[Spell_Frost_Frostbolt]],
    [[Spell_Frost_FrostBolt02]],
    [[Spell_Frost_FrostBrand]],
    [[Spell_Frost_FrostNova]],
    [[Spell_Frost_FrostShock]],
    [[Spell_Frost_FrostWard]],
    [[Spell_Frost_FrozenCore]],
    [[Spell_Frost_FrozenOrb]],
    [[Spell_Frost_Glacier]],
    [[Spell_Frost_Ice Shards]],
    [[Spell_Frost_IceClaw]],
    [[Spell_Frost_IceFloes]],
    [[Spell_Frost_IceShard]],
    [[Spell_Frost_IceShock]],
    [[Spell_Frost_IceStorm]],
    [[Spell_Frost_ManaBurn]],
    [[Spell_Frost_ManaRecharge]],
    [[Spell_Frost_Piercing Chill]],
    [[Spell_Frost_Ring of Frost]],
    [[Spell_Frost_Stun]],
    [[Spell_Frost_SummonWaterElemental]],
    [[Spell_Frost_SummonWaterElemental_2]],
    [[Spell_Frost_WindWalkOn]],
    [[Spell_Frost_Wisp]],
    [[Spell_Frost_WizardMark]],
    [[Spell_Holiday_ToW_SpiceCloud]],
    [[Spell_Holy_Absolution]],
    [[Spell_Holy_ArcaneIntellect]],
    [[Spell_Holy_ArdentDefender]],
    [[Spell_Holy_AshesToAshes]],
    [[Spell_Holy_Aspiration]],
    [[Spell_Holy_AuraMastery]],
    [[Spell_Holy_AuraOfLight]],
    [[Spell_Holy_AvengersShield]],
    [[SPELL_HOLY_AVENGINEWRATH]],
    [[Spell_Holy_BlessedLife]],
    [[Spell_Holy_BlessedRecovery]],
    [[Spell_Holy_BlessedResillience]],
    [[Spell_Holy_BlessingOfAgility]],
    [[Spell_Holy_BlessingOfProtection]],
    [[Spell_Holy_BlessingOfStamina]],
    [[Spell_Holy_BlessingOfStrength]],
    [[Spell_Holy_BlindingHeal]],
    [[SPELL_HOLY_BORROWEDTIME]],
    [[Spell_Holy_ChampionsBond]],
    [[Spell_Holy_ChampionsGrace]],
    [[Spell_Holy_Chastise]],
    [[Spell_Holy_CircleOfRenewal]],
    [[Spell_Holy_ConsumeMagic]],
    [[Spell_Holy_Crusade]],
    [[Spell_Holy_CrusaderAura]],
    [[Spell_Holy_CrusaderStrike]],
    [[SPELL_HOLY_DEVINEAEGIS]],
    [[Spell_Holy_Devotion]],
    [[SPELL_HOLY_DEVOTIONAURA]],
    [[SPELL_HOLY_DISPELMAGIC]],
    [[Spell_Holy_DivineHymn]],
    [[Spell_Holy_DivineIllumination]],
    [[Spell_Holy_DivineIntervention]],
    [[Spell_Holy_DivineProtection]],
    [[Spell_Holy_DivineProvidence]],
    [[Spell_Holy_DivinePurpose]],
    [[Spell_Holy_DivineShield]],
    [[Spell_Holy_DivineSpirit]],
    [[Spell_Holy_Dizzy]],
    [[Spell_Holy_ElunesGrace]],
    [[Spell_Holy_EmpowerChampion]],
    [[Spell_Holy_Excorcism]],
    [[Spell_Holy_Excorcism_02]],
    [[Spell_Holy_EyeforanEye]],
    [[Spell_Holy_Fanaticism]],
    [[Spell_Holy_FistOfJustice]],
    [[Spell_Holy_FlashHeal]],
    [[Spell_Holy_GreaterBlessingofKings]],
    [[Spell_Holy_GreaterBlessingofLight]],
    [[Spell_Holy_GreaterBlessingofSalvation]],
    [[Spell_Holy_GreaterBlessingofSanctuary]],
    [[Spell_Holy_GreaterBlessingofWisdom]],
    [[Spell_Holy_GreaterHeal]],
    [[Spell_Holy_GuardianSpirit]],
    [[Spell_Holy_HarmUndeadAura]],
    [[Spell_Holy_Heal]],
    [[Spell_Holy_Heal02]],
    [[Spell_Holy_HealingAura]],
    [[Spell_Holy_HealingFocus]],
    [[Spell_Holy_Heroism]],
    [[Spell_Holy_HolyBolt]],
    [[Spell_Holy_HolyGuidance]],
    [[Spell_Holy_HolyNova]],
    [[Spell_Holy_HolyProtection]],
    [[Spell_Holy_HolySmite]],
    [[Spell_Holy_HopeAndGrace]],
    [[Spell_Holy_ImpHolyConcentration]],
    [[Spell_Holy_ImprovedResistanceAuras]],
    [[Spell_Holy_InnerFire]],
    [[Spell_Holy_LastingDefense]],
    [[Spell_Holy_LayOnHands]],
    [[Spell_Holy_LesserHeal]],
    [[Spell_Holy_LesserHeal02]],
    [[Spell_Holy_LightsGrace]],
    [[Spell_Holy_MagicalSentry]],
    [[Spell_Holy_MindSooth]],
    [[Spell_Holy_MindVision]],
    [[Spell_Holy_NullifyDisease]],
    [[Spell_Holy_PainSupression]],
    [[Spell_Holy_Penance]],
    [[SPELL_HOLY_PERSECUTION]],
    [[Spell_Holy_PersuitofJustice]],
    [[Spell_Holy_Power]],
    [[Spell_Holy_PowerInfusion]],
    [[Spell_Holy_PowerWordBarrier]],
    [[Spell_Holy_PowerWordShield]],
    [[Spell_Holy_PrayerOfFortitude]],
    [[Spell_Holy_PrayerOfHealing]],
    [[Spell_Holy_PrayerOfHealing02]],
    [[Spell_Holy_PrayerOfMendingtga]],
    [[Spell_Holy_PrayerofShadowProtection]],
    [[Spell_Holy_PrayerofSpirit]],
    [[Spell_Holy_ProclaimChampion]],
    [[Spell_Holy_ProclaimChampion_02]],
    [[Spell_Holy_PureOfHeart]],
    [[Spell_Holy_Purify]],
    [[Spell_Holy_PurifyingPower]],
    [[Spell_Holy_Rapture]],
    [[Spell_Holy_Rebuke]],
    [[Spell_Holy_Redemption]],
    [[Spell_Holy_RemoveCurse]],
    [[Spell_Holy_Renew]],
    [[Spell_Holy_Restoration]],
    [[Spell_Holy_Resurrection]],
    [[Spell_Holy_Retribution]],
    [[Spell_Holy_RetributionAura]],
    [[Spell_Holy_ReviveChampion]],
    [[Spell_Holy_RighteousFury]],
    [[Spell_Holy_RighteousnessAura]],
    [[Spell_Holy_Rune]],
    [[Spell_Holy_SealOfBlood]],
    [[Spell_Holy_SealOfFury]],
    [[Spell_Holy_SealOfMight]],
    [[Spell_Holy_SealOfProtection]],
    [[Spell_Holy_SealOfRighteousness]],
    [[Spell_Holy_SealOfSacrifice]],
    [[Spell_Holy_SealOfSalvation]],
    [[Spell_Holy_SealOfValor]],
    [[Spell_Holy_SealOfVengeance]],
    [[Spell_Holy_SealOfWisdom]],
    [[Spell_Holy_SealOfWrath]],
    [[Spell_Holy_SearingLight]],
    [[Spell_Holy_SearingLightPriest]],
    [[Spell_Holy_SenseUndead]],
    [[Spell_Holy_Serendipity]],
    [[SPELL_HOLY_SILENCE]],
    [[Spell_Holy_SpellWarding]],
    [[Spell_Holy_SpiritualGuidence]],
    [[Spell_Holy_Stoicism]],
    [[Spell_Holy_SummonChampion]],
    [[Spell_Holy_SummonLightwell]],
    [[Spell_Holy_SurgeOfLight]],
    [[Spell_Holy_SymbolOfHope]],
    [[Spell_Holy_TestOfFaith]],
    [[Spell_Holy_TurnUndead]],
    [[Spell_Holy_UnyieldingFaith]],
    [[Spell_Holy_Vindication]],
    [[Spell_Holy_WeaponMastery]],
    [[Spell_Holy_WordFortitude]],
    [[Spell_Hunter_AspectOfTheHawk]],
    [[Spell_Hunter_AspectOfTheIronHawk]],
    [[Spell_Hunter_BlackIceTrap]],
    [[Spell_Hunter_IceTrap]],
    [[Spell_Ice_Lament]],
    [[Spell_Ice_MagicDamage]],
    [[Spell_Ice_Rune]],
    [[Spell_Impending_Victory]],
    [[Spell_lfieblood]],
    [[spell_lifegivingseed]],
    [[SPELL_LIFEGIVINGSPEED]],
    [[Spell_Lightning_LightningBolt01]],
    [[Spell_MageArmor]],
    [[Spell_Mage_AlterTime]],
    [[Spell_Mage_ConjuredManaBuns]],
    [[Spell_Mage_ConjuredManaPudding]],
    [[spell_Mage_Curtainoffrost]],
    [[spell_Mage_Flameorb]],
    [[Spell_Mage_FrostBomb]],
    [[Spell_Mage_IceFlows]],
    [[Spell_Mage_InfernoBlast]],
    [[spell_Mage_NetherTempest]],
    [[Spell_Mage_PresenceOfMind]],
    [[Spell_Mage_RuneOfPower]],
    [[Spell_Mage_TemporalShield]],
    [[Spell_Magic_FeatherFall]],
    [[Spell_Magic_GreaterBlessingofKings]],
    [[Spell_Magic_LesserInvisibilty]],
    [[Spell_Magic_MageArmor]],
    [[Spell_Magic_ManaGain]],
    [[Spell_Magic_PolymorphChicken]],
    [[Spell_Magic_PolymorphPig]],
    [[Spell_Magic_PolymorphRabbit]],
    [[Spell_Misc_ConjureManaJewel]],
    [[Spell_Misc_Drink]],
    [[Spell_Misc_EmotionAfraid]],
    [[Spell_Misc_EmotionAngry]],
    [[Spell_Misc_EmotionHappy]],
    [[Spell_Misc_EmotionSad]],
    [[Spell_Misc_Food]],
    [[Spell_Misc_HellifrePVPCombatMorale]],
    [[Spell_Misc_PetHeal]],
    [[Spell_Misc_WarsongBrutal]],
    [[Spell_Misc_WarsongFocus]],
    [[Spell_Misc_WateringCan]],
    [[spell_misc_zandalari_council_soulswap]],
    [[Spell_Monk_BrewmasterTraining]],
    [[Spell_Monk_Brewmaster_Spec]],
    [[Spell_Monk_DiffuseMagic]],
    [[Spell_Monk_EnvelopingMist]],
    [[Spell_Monk_MistWeaver_Spec]],
    [[Spell_Monk_NimbleBrew]],
    [[Spell_Monk_RingofPeace]],
    [[Spell_Monk_WindWalker_Spec]],
    [[Spell_Monk_ZenPilgrimage]],
    [[Spell_Nature_AbolishMagic]],
    [[Spell_Nature_Acid_01]],
    [[Spell_Nature_AgitatingTotem]],
    [[Spell_Nature_AncestralGuardian]],
    [[Spell_Nature_AstralRecal]],
    [[Spell_Nature_AstralRecalGroup]],
    [[Spell_Nature_BloodLust]],
    [[Spell_Nature_Brilliance]],
    [[Spell_Nature_CallStorm]],
    [[Spell_Nature_ChainLightning]],
    [[Spell_Nature_CorrosiveBreath]],
    [[Spell_Nature_CrystalBall]],
    [[Spell_Nature_Cyclone]],
    [[Spell_Nature_DiseaseCleansingTotem]],
    [[Spell_Nature_DoublePolymorph1]],
    [[Spell_Nature_DoublePolymorph2]],
    [[Spell_Nature_Drowsy]],
    [[Spell_Nature_DryadDispelMagic]],
    [[Spell_Nature_EarthBind]],
    [[Spell_Nature_EarthBindTotem]],
    [[Spell_Nature_EarthElemental_Totem]],
    [[Spell_Nature_Earthquake]],
    [[Spell_Nature_EarthShock]],
    [[Spell_Nature_ElementalAbsorption]],
    [[Spell_Nature_ElementalPrecision_1]],
    [[Spell_Nature_ElementalPrecision_2]],
    [[Spell_Nature_ElementalShields]],
    [[Spell_Nature_EnchantArmor]],
    [[Spell_Nature_EyeOfTheStorm]],
    [[Spell_Nature_FaerieFire]],
    [[Spell_Nature_FarSight]],
    [[Spell_Nature_FocusedMind]],
    [[Spell_Nature_ForceOfNature]],
    [[Spell_Nature_GiftoftheWaterSpirit]],
    [[Spell_Nature_GiftoftheWild]],
    [[Spell_Nature_GroundingTotem]],
    [[Spell_Nature_GuardianWard]],
    [[SPELL_NATURE_HEALINGTOUCH]],
    [[Spell_Nature_HealingWaveGreater]],
    [[Spell_Nature_HealingWaveLesser]],
    [[SPELL_NATURE_HEALINGWAY]],
    [[Spell_Nature_HeavyPolymorph1]],
    [[Spell_Nature_HeavyPolymorph2]],
    [[Spell_Nature_InsectSwarm]],
    [[spell_nature_insect_swarm2]],
    [[Spell_Nature_Lightning]],
    [[Spell_Nature_LightningBolt]],
    [[Spell_Nature_LightningOverload]],
    [[Spell_Nature_LightningShield]],
    [[Spell_Nature_MagicImmunity]],
    [[Spell_Nature_ManaRegenTotem]],
    [[Spell_Nature_MassTeleport]],
    [[Spell_Nature_MentalQuickness]],
    [[Spell_Nature_MirrorImage]],
    [[Spell_Nature_MoonGlow]],
    [[Spell_Nature_MoonKey]],
    [[Spell_Nature_NatureBlessing]],
    [[Spell_Nature_NatureGuardian]],
    [[Spell_Nature_NatureResistanceTotem]],
    [[Spell_Nature_NaturesBlessing]],
    [[Spell_Nature_NaturesWrath]],
    [[Spell_Nature_NatureTouchDecay]],
    [[Spell_Nature_NatureTouchGrow]],
    [[Spell_Nature_NullifyDisease]],
    [[Spell_Nature_NullifyPoison]],
    [[Spell_Nature_NullifyPoison_02]],
    [[Spell_Nature_NullWard]],
    [[Spell_Nature_PoisonCleansingTotem]],
    [[Spell_Nature_Polymorph]],
    [[Spell_Nature_Polymorph_Cow]],
    [[Spell_Nature_Preservation]],
    [[Spell_Nature_ProtectionformNature]],
    [[Spell_Nature_Purge]],
    [[Spell_Nature_RavenForm]],
    [[Spell_Nature_Regenerate]],
    [[Spell_Nature_Regeneration]],
    [[Spell_Nature_Regeneration_02]],
    [[Spell_Nature_Reincarnation]],
    [[Spell_Nature_Rejuvenation]],
    [[Spell_Nature_RemoveCurse]],
    [[Spell_Nature_RemoveDisease]],
    [[Spell_Nature_ResistMagic]],
    [[Spell_Nature_ResistNature]],
    [[Spell_Nature_Riptide]],
    [[Spell_Nature_RockBiter]],
    [[Spell_Nature_Rune]],
    [[Spell_Nature_Sentinal]],
    [[Spell_Nature_ShamanRage]],
    [[Spell_Nature_SicklyPolymorph]],
    [[Spell_Nature_SkinofEarth]],
    [[Spell_Nature_Sleep]],
    [[Spell_Nature_Slow]],
    [[Spell_Nature_SlowingTotem]],
    [[Spell_Nature_SlowPoison]],
    [[Spell_Nature_SpiritArmor]],
    [[Spell_Nature_SpiritWolf]],
    [[Spell_Nature_StarFall]],
    [[Spell_Nature_StoneClawTotem]],
    [[Spell_Nature_StoneSkinTotem]],
    [[Spell_Nature_StormReach]],
    [[Spell_Nature_StrangleVines]],
    [[Spell_Nature_Strength]],
    [[Spell_Nature_StrengthOfEarthTotem02]],
    [[Spell_Nature_Swiftness]],
    [[Spell_Nature_Thorns]],
    [[SPELL_NATURE_THUNDERCLAP]],
    [[Spell_Nature_TimeStop]],
    [[Spell_Nature_Tranquility]],
    [[Spell_Nature_TremorTotem]],
    [[Spell_Nature_UndyingStrength]],
    [[Spell_Nature_UnleashedRage]],
    [[Spell_Nature_UnrelentingStorm]],
    [[Spell_Nature_UnyeildingStamina]],
    [[Spell_Nature_Web]],
    [[Spell_Nature_Windfury]],
    [[Spell_Nature_WispHeal]],
    [[Spell_Nature_WispSplode]],
    [[Spell_Nature_WispSplodeGreen]],
    [[Spell_Nature_WrathofAir_Totem]],
    [[Spell_Nature_WrathV2]],
    [[Spell_Paladin_Clarityofpurpose]],
    [[spell_Paladin_divinecircle]],
    [[Spell_Paladin_ExecutionSentence]],
    [[Spell_Paladin_HammerOfWrath]],
    [[Spell_Paladin_HolyPrism]],
    [[Spell_Paladin_Inquisition]],
    [[Spell_Paladin_Lightofdawn]],
    [[spell_Paladin_LightsHammer]],
    [[Spell_Paladin_templarsverdict]],
    [[Spell_Priest_AngelicBulwark]],
    [[Spell_Priest_BurningWill]],
    [[Spell_Priest_Chakra]],
    [[Spell_Priest_DivineStar]],
    [[Spell_Priest_DivineStar_Holy]],
    [[Spell_Priest_DivineStar_Shadow]],
    [[Spell_Priest_DivineStar_Shadow2]],
    [[Spell_Priest_FinalPrayer]],
    [[spell_priest_mindspike]],
    [[Spell_Priest_PathofDevout]],
    [[SPELL_PRIEST_PSYFIEND]],
    [[spell_priest_shadoworbs]],
    [[Spell_Priest_SpectralGuise]],
    [[Spell_Priest_VoidShift]],
    [[SPELL_PRIEST_VOIDTENDRILS]],
    [[Spell_Priest_VowofUnity]],
    [[Spell_quicksand]],
    [[Spell_Sandbolt]],
    [[Spell_sandelemental]],
    [[Spell_SandExplosion]],
    [[Spell_Sandstorm]],
    [[Spell_Shadow_AnimateDead]],
    [[Spell_Shadow_AntiMagicShell]],
    [[Spell_Shadow_AntiShadow]],
    [[Spell_Shadow_AuraOfDarkness]],
    [[Spell_Shadow_BlackPlague]],
    [[Spell_Shadow_BloodBoil]],
    [[Spell_Shadow_BurningSpirit]],
    [[Spell_Shadow_CallofBone]],
    [[Spell_Shadow_CarrionSwarm]],
    [[Spell_Shadow_Charm]],
    [[Spell_Shadow_ChillTouch]],
    [[Spell_Shadow_ConeOfSilence]],
    [[Spell_Shadow_CreepingPlague]],
    [[Spell_Shadow_Cripple]],
    [[Spell_Shadow_Curse]],
    [[Spell_Shadow_CurseOfAchimonde]],
    [[Spell_Shadow_CurseOfMannoroth]],
    [[Spell_Shadow_CurseOfSargeras]],
    [[Spell_Shadow_CurseOfTounges]],
    [[Spell_Shadow_DarkRitual]],
    [[Spell_Shadow_DarkSummoning]],
    [[Spell_Shadow_DeadofNight]],
    [[Spell_Shadow_DeathAndDecay]],
    [[Spell_Shadow_DeathCoil]],
    [[Spell_Shadow_DeathPact]],
    [[Spell_Shadow_DeathScream]],
    [[Spell_Shadow_DeathsEmbrace]],
    [[Spell_Shadow_DemonBreath]],
    [[Spell_Shadow_DemonForm]],
    [[Spell_Shadow_DemonicCircleSummon]],
    [[Spell_Shadow_DemonicCircleTeleport]],
    [[Spell_Shadow_DemonicEmpathy]],
    [[Spell_Shadow_DemonicFortitude]],
    [[Spell_Shadow_DemonicPact]],
    [[Spell_Shadow_DemonicTactics]],
    [[Spell_Shadow_DestructiveSoul]],
    [[Spell_Shadow_DetectInvisibility]],
    [[Spell_Shadow_DetectLesserInvisibility]],
    [[Spell_Shadow_DevouringPlague.]],
    [[Spell_Shadow_Dispersion]],
    [[Spell_Shadow_EnslaveDemon]],
    [[Spell_Shadow_EvilEye]],
    [[Spell_Shadow_FelArmour]],
    [[Spell_Shadow_FelMending]],
    [[Spell_Shadow_FingerOfDeath]],
    [[Spell_Shadow_FocusedPower]],
    [[Spell_Shadow_Fumble]],
    [[Spell_Shadow_GatherShadows]],
    [[Spell_Shadow_GhostKey]],
    [[Spell_Shadow_GrimWard]],
    [[Spell_Shadow_Haunting]],
    [[Spell_Shadow_ImpPhaseShift]],
    [[Spell_Shadow_ImprovedVampiricEmbrace]],
    [[Spell_Shadow_LastingAffliction]],
    [[Spell_Shadow_LastingAfflictions]],
    [[Spell_Shadow_LifeDrain]],
    [[Spell_Shadow_LifeDrain02]],
    [[Spell_Shadow_ManaBurn]],
    [[Spell_Shadow_ManaFeed]],
    [[Spell_Shadow_Metamorphosis]],
    [[Spell_Shadow_MindBomb]],
    [[Spell_Shadow_MindFlay]],
    [[Spell_Shadow_MindRot]],
    [[Spell_Shadow_MindShear]],
    [[SPELL_SHADOW_MINDSTEAL]],
    [[Spell_Shadow_MindTwisting]],
    [[Spell_Shadow_Misery]],
    [[Spell_Shadow_NetherCloak]],
    [[Spell_Shadow_NetherProtection]],
    [[Spell_Shadow_NightOfTheDead]],
    [[Spell_Shadow_PainAndSuffering]],
    [[Spell_Shadow_PainfulAfflictions]],
    [[Spell_Shadow_PainSpike]],
    [[Spell_Shadow_Possession]],
    [[Spell_Shadow_PsychicHorrors]],
    [[Spell_Shadow_PsychicScream]],
    [[Spell_Shadow_RagingScream]],
    [[Spell_Shadow_RainOfFire]],
    [[Spell_Shadow_RaiseDead]],
    [[Spell_Shadow_Requiem]],
    [[Spell_Shadow_RitualOfSacrifice]],
    [[Spell_Shadow_Rune]],
    [[Spell_Shadow_SacrificialShield]],
    [[Spell_Shadow_ScourgeBuild]],
    [[Spell_Shadow_SealOfKings]],
    [[Spell_Shadow_SeedOfDestruction]],
    [[Spell_Shadow_Shadesofdarkness]],
    [[Spell_Shadow_ShadeTrueSight]],
    [[Spell_Shadow_ShadowandFlame]],
    [[Spell_Shadow_ShadowBolt]],
    [[Spell_Shadow_ShadowEmbrace]],
    [[Spell_Shadow_Shadowfiend]],
    [[Spell_Shadow_Shadowform]],
    [[Spell_Shadow_Shadowfury]],
    [[Spell_Shadow_ShadowMend]],
    [[Spell_Shadow_ShadowPact]],
    [[Spell_Shadow_ShadowPower]],
    [[Spell_Shadow_ShadowWard]],
    [[Spell_Shadow_ShadowWordDominate]],
    [[Spell_Shadow_ShadowWordPain]],
    [[Spell_Shadow_SiphonMana]],
    [[Spell_Shadow_Skull]],
    [[Spell_Shadow_SoothingKiss]],
    [[Spell_Shadow_SoulGem]],
    [[Spell_Shadow_SoulLeech]],
    [[Spell_Shadow_SoulLeech_1]],
    [[Spell_Shadow_SoulLeech_2]],
    [[Spell_Shadow_SoulLeech_3]],
    [[Spell_Shadow_SpectralSight]],
    [[Spell_Shadow_SummonFelGuard]],
    [[Spell_Shadow_SummonFelHunter]],
    [[Spell_Shadow_SummonImp]],
    [[Spell_Shadow_SummonInfernal]],
    [[Spell_Shadow_SummonSuccubus]],
    [[Spell_Shadow_SummonVoidWalker]],
    [[Spell_Shadow_Teleport]],
    [[Spell_Shadow_Twilight]],
    [[SPELL_SHADOW_TWISTEDFAITH]],
    [[Spell_Shadow_UnholyFrenzy]],
    [[Spell_Shadow_UnholyStrength]],
    [[Spell_Shadow_UnstableAffliction_1]],
    [[Spell_Shadow_UnstableAffliction_2]],
    [[Spell_Shadow_UnstableAffliction_3]],
    [[Spell_Shadow_UnstableAfllictions]],
    [[Spell_Shadow_UnsummonBuilding]],
    [[Spell_Shadow_VampiricAura]],
    [[Spell_Shadow_ZDemonFormGreen]],
    [[Spell_Shaman_AncestralAwakening]],
    [[Spell_Shaman_AstralShift]],
    [[spell_Shaman_Bindelemental]],
    [[Spell_Shaman_BlessingOfEternals]],
    [[Spell_Shaman_BlessingOfTheEternals]],
    [[spell_Shaman_convection]],
    [[Spell_Shaman_Dropall_01]],
    [[Spell_Shaman_Dropall_02]],
    [[Spell_Shaman_Dropall_03]],
    [[Spell_Shaman_EarthlivingWeapon]],
    [[spell_Shaman_Earthquake]],
    [[Spell_Shaman_ElementalOath]],
    [[Spell_Shaman_FeralSpirit]],
    [[spell_Shaman_Firenova]],
    [[spell_Shaman_focusedstrikes]],
    [[Spell_Shaman_GiftEarthmother]],
    [[Spell_Shaman_Hex]],
    [[Spell_Shaman_ImprovedEarthShield]],
    [[spell_Shaman_ImprovedFirenova]],
    [[spell_shaman_Improvedreincarnation]],
    [[Spell_Shaman_ImprovedStormstrike]],
    [[spell_shaman_ImproveLavaLash]],
    [[Spell_Shaman_LavaBurst]],
    [[Spell_Shaman_LavaFlow]],
    [[spell_Shaman_Lavasurge]],
    [[Spell_Shaman_MaelstromWeapon]],
    [[spell_Shaman_Measuredinsight]],
    [[Spell_Shaman_primalstrike]],
    [[Spell_Shaman_SpectralTransformation]],
    [[Spell_Shaman_SpiritLink]],
    [[spell_Shaman_spiritwalkersgrace]],
    [[Spell_Shaman_StaticShock]],
    [[Spell_Shaman_StormEarthFire]],
    [[Spell_Shaman_ThunderStorm]],
    [[Spell_Shaman_TidalWaves]],
    [[Spell_Shaman_TotemRecall]],
    [[spell_Shaman_Unleashweapon_Earth]],
    [[spell_Shaman_Unleashweapon_Flame]],
    [[spell_Shaman_Unleashweapon_Frost]],
    [[spell_Shaman_Unleashweapon_Life]],
    [[spell_Shaman_Unleashweapon_Wind]],
    [[Spell_Totem_WardOfDraining]],
    [[Spell_unused]],
    [[Spell_unused2]],
    [[Spell_volatilefiregreen]],
    [[Spell_Warlock_DarkRegeneration]],
    [[Spell_Warlock_DemonicPortal_Green]],
    [[Spell_Warlock_DemonicPortal_Purple]],
    [[spell_warlock_demonsoul]],
    [[spell_Warlock_Focusshadow]],
    [[Spell_Warlock_HarvestofLife]],
    [[spell_Warlock_Soulburn]],
    [[Spell_Warlock_SummonAbyssal]],
    [[Spell_Warlock_SummonImpOutland]],
    [[Spell_Warlock_SummonTerrorGuard]],
    [[Spell_Warlock_SummonWrathguard]],
    [[Spell_warrior_wildstrike]],
    [[spell_yorsahj_bloodboil_black]],
    [[spell_yorsahj_bloodboil_blue]],
    [[spell_yorsahj_bloodboil_green]],
    [[spell_yorsahj_bloodboil_purple]],
    [[spell_yorsahj_bloodboil_yellow]],
    [[Stave_2H_Tarecgosa_E_01BaseStaff]],
    [[Stave_2H_Tarecgosa_E_01Stage1]],
    [[Stave_2H_Tarecgosa_E_01Stage2]],
    [[Stave_2H_Tarecgosa_E_01StageFinal]],
    [[Stormspear_Empowered_Icon]],
    [[Stormspear_Unempowered_Icon]],
    [[Sword_1h_PVPCataclysmS3_C_02]],
    [[Sword_1h_PVPPandariaS1_C_01]],
    [[TalentSpec_Druid_Balance]],
    [[TalentSpec_Druid_Feral_Bear]],
    [[TalentSpec_Druid_Feral_Cat]],
    [[TalentSpec_Druid_Restoration]],
    [[TimelessCoin-Bloody]],
    [[TimelessCoin]],
    [[Tradeskill_Inscription_BlackOx]],
    [[Tradeskill_Inscription_JadeSerpent]],
    [[Tradeskill_Inscription_RedCrane]],
    [[Tradeskill_Inscription_WhiteTiger]],
    [[TRADE_ARCHAEOLOGY]],
    [[TRADE_ARCHAEOLOGY_ANCIENTORCSHAMANHEADDRESS]],
    [[TRADE_ARCHAEOLOGY_ANTLEREDCLOAKCLASP]],
    [[TRADE_ARCHAEOLOGY_AQIR_ARTIFACTFRAGMENT]],
    [[Trade_Archaeology_Aqir_hieroglyphic]],
    [[TRADE_ARCHAEOLOGY_ARAKKOA_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_ARAKKOA_CRYSTALSHARD]],
    [[Trade_Archaeology_BlackenedStaff]],
    [[Trade_Archaeology_BlackTrilobite]],
    [[TRADE_ARCHAEOLOGY_BLADEDORCSCEPTER]],
    [[TRADE_ARCHAEOLOGY_BLOODYSATYRSCEPTER]],
    [[Trade_Archaeology_Bones of Transformation]],
    [[TRADE_ARCHAEOLOGY_BURNINGDEMONSCEPTER]],
    [[TRADE_ARCHAEOLOGY_CANDLESTUB]],
    [[Trade_Archaeology_Carved Harp of Exotic Wood]],
    [[Trade_Archaeology_Carved Wildhammer Gryphon Figurine]],
    [[TRADE_ARCHAEOLOGY_CATSTATUEEMERALDEYES]],
    [[TRADE_ARCHAEOLOGY_CHESTOFTINYGLASSANIMALS]],
    [[TRADE_ARCHAEOLOGY_CRACKEDCRYSTALVIAL]],
    [[Trade_Archaeology_CthunsPuzzleBox]],
    [[Trade_Archaeology_Decorated Leather Boot Heel]],
    [[TRADE_ARCHAEOLOGY_DELICATEMUSICBOX]],
    [[TRADE_ARCHAEOLOGY_DENTEDSHIELD]],
    [[Trade_Archaeology_Dignified Draenei Portrait]],
    [[Trade_Archaeology_DinosaurSkeleton]],
    [[Trade_Archaeology_Draenei Candelabra]],
    [[Trade_Archaeology_DraeneiRelic]],
    [[TRADE_ARCHAEOLOGY_DRAENEI_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_DRAENEI_TOME]],
    [[Trade_Archaeology_DruidPriestStatueSet]],
    [[TRADE_ARCHAEOLOGY_DWARF_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_DWARF_RUNESTONE]],
    [[TRADE_ARCHAEOLOGY_ENGRAVEDSCIMITARPOMMEL]],
    [[TRADE_ARCHAEOLOGY_FOSSIL_DINOSAURBONE]],
    [[TRADE_ARCHAEOLOGY_FOSSIL_FERN]],
    [[TRADE_ARCHAEOLOGY_FOSSIL_SNAILSHELL]],
    [[TRADE_ARCHAEOLOGY_GEMMEDDRINKINGCUP]],
    [[Trade_Archaeology_GeneralBeauregardsLastStand]],
    [[Trade_Archaeology_GoldChamberPot]],
    [[Trade_Archaeology_HairpinSilverMalachite]],
    [[Trade_Archaeology_HighborneSoulMirror]],
    [[TRADE_ARCHAEOLOGY_HIGHBORNE_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_HIGHBORNE_SCROLL]],
    [[Trade_Archaeology_Insect in Amber]],
    [[TRADE_ARCHAEOLOGY_JEWELEDDWARFSCEPTER]],
    [[Trade_Archaeology_KaldoreiWindChimes]],
    [[TRADE_ARCHAEOLOGY_MITHRILNECKLACE]],
    [[Trade_Archaeology_NaaruCrystal]],
    [[TRADE_ARCHAEOLOGY_NERUBIANSPIDERSCEPTER]],
    [[TRADE_ARCHAEOLOGY_NERUBIAN_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_NERUBIAN_OBELISK]],
    [[TRADE_ARCHAEOLOGY_NOTCHEDSWORD]],
    [[TRADE_ARCHAEOLOGY_OGRE2HANDEDHAMMER]],
    [[Trade_Archaeology_OldGodTrinket]],
    [[TRADE_ARCHAEOLOGY_ORC_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_ORC_BLOODTEXT]],
    [[Trade_Archaeology_Pendant of the Aqir]],
    [[Trade_Archaeology_QueenAzshara DressingGown]],
    [[Trade_Archaeology_Ring of the BoyEmperor]],
    [[TRADE_ARCHAEOLOGY_RUSTEDSTEAKKNIFE]],
    [[Trade_Archaeology_Sand Castle]],
    [[Trade_Archaeology_Sceptor of AzAqir]],
    [[Trade_Archaeology_Scimitar of the Sirocco]],
    [[Trade_Archaeology_Shark Jaws]],
    [[Trade_Archaeology_ShriveledMonkeyPaw]],
    [[TRADE_ARCHAEOLOGY_SILVERDAGGER]],
    [[Trade_Archaeology_SilverDoorKnocker of Female Dwarf]],
    [[TRADE_ARCHAEOLOGY_SILVERSCROLLCASE]],
    [[TRADE_ARCHAEOLOGY_SKETCHDESERTPALACE]],
    [[TRADE_ARCHAEOLOGY_SOAPSTONESCARABNECKLACE]],
    [[TRADE_ARCHAEOLOGY_SPINEDQUILLBOARSCEPTER]],
    [[Trade_Archaeology_Staff of Ammunrae]],
    [[Trade_Archaeology_StaffofSorcerer_Than Thaurissan]],
    [[TRADE_ARCHAEOLOGY_STONESHIELD]],
    [[Trade_Archaeology_TheInnkeepersDaughter]],
    [[TRADE_ARCHAEOLOGY_TINYBRONZESCORPION]],
    [[Trade_Archaeology_TinyDinosaurSkeleton]],
    [[TRADE_ARCHAEOLOGY_TINYOASISMOSAIC]],
    [[TRADE_ARCHAEOLOGY_TITAN_FRAGMENT]],
    [[Trade_Archaeology_TrollBatIdol]],
    [[TRADE_ARCHAEOLOGY_TROLLBATSCEPTER]],
    [[Trade_Archaeology_TrollLizardFootCharm]],
    [[Trade_Archaeology_TrollTooth w GoldFilling]],
    [[TRADE_ARCHAEOLOGY_TROLL_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_TROLL_TABLET]],
    [[Trade_Archaeology_Troll_VoodooDoll]],
    [[TRADE_ARCHAEOLOGY_TUSKARR_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_TUSKARR_STELE]],
    [[Trade_Archaeology_TyrandesFavoriteDoll]],
    [[TRADE_ARCHAEOLOGY_ULDUMCANOPICJAR]],
    [[TRADE_ARCHAEOLOGY_VRYKUL_ARTIFACTFRAGMENT]],
    [[TRADE_ARCHAEOLOGY_VRYKUL_RUNESTICK]],
    [[Trade_Archaeology_WhiteHydraFigurine]],
    [[TRADE_ARCHAEOLOGY_WINGEDHELM]],
    [[Trade_Archaeology_WispAmulet]],
    [[TRADE_ARCHAEOLOGY_ZINROKH SWORD]],
    [[Trade_BlackSmithing]],
    [[Trade_BrewPoison]],
    [[Trade_Cooking_2]],
    [[Trade_Enchanting_GreaterMysteriousEssence]],
    [[Trade_Enchanting_LargeEtherealShard]],
    [[Trade_Enchanting_LesserMysteriousEssence]],
    [[Trade_Enchanting_SmallEtherealShard]],
    [[Trade_Engraving]],
    [[Trade_Fishing]],
    [[Trade_Herbalism]],
    [[Trade_LeatherWorking]],
    [[Trade_Mining]],
    [[Trade_Tailoring]],
    [[T_RobotIcon]],
    [[Warlock_ Bloodstone]],
    [[Warlock_ Healthstone]],
    [[Warlock_Curse_Shadow]],
    [[Warlock_Curse_Shadow_Aura]],
    [[Warlock_Curse_Weakness]],
    [[Warlock_Curse_Weakness_Aura]],
    [[Warlock_GrimoireofCommand]],
    [[Warlock_GrimoireofSacrifice]],
    [[Warlock_GrimoireofService]],
    [[Warlock_HourOfTwilight]],
    [[WARLOCK_SACRIFICIAL_PACT]],
    [[Warlock_SiphonLife]],
    [[Warlock_SpellDrain]],
    [[WARLOCK_SUMMON_ BEHOLDER]],
    [[Warlock_Summon_ Shivan]],
    [[WARLOCK_SUMMON_ VOIDLORD]],
    [[Warlock_Summon_DoomGuard]],
    [[Warrior_DisruptingShout]],
    [[Warrior_DoubleTime]],
    [[warrior_skullbanner]],
    [[Warrior_talent_icon_Avatar]],
    [[Warrior_talent_icon_Blitz]],
    [[Warrior_talent_icon_BloodandThunder]],
    [[Warrior_talent_icon_Deadlycalm]],
    [[Warrior_talent_icon_FuryInTheBlood]],
    [[Warrior_talent_icon_InnerRage]],
    [[Warrior_talent_icon_LambsToTheSlaughter]],
    [[Warrior_talent_icon_mastercleaver]],
    [[Warrior_talent_icon_SingleMindedFury]],
    [[Warrior_talent_icon_Skirmisher]],
    [[Warrior_talent_icon_Stormbolt]],
    [[Warrior_talent_icon_Thunderstruck]],
    [[Warrior_Wild_strike]],
}

setmetatable(AvatarList, {__index = function()
    return [[Trade_Archaeology_TheInnkeepersDaughter]]
end})

do
    CityMenuTable = {}
    
    tinsert(CityMenuTable, {
        value = 0,
        text = L['保密'],
    })

    for i, v in ipairs(CityData[0]) do
        local info = {
            value = i,
            text = v,
            hasArrow = true,
            notClickable = true,
            menuTable = {}
        }
        tinsert(CityMenuTable, info)

        local j = i*100 + 1
        while CityData[i][j] do
            tinsert(info.menuTable, {
                value = j,
                text = CityData[i][j],
                full = v .. ' - ' .. CityData[i][j],
            })

            j=j+1
        end
    end
end

AVATAR_LIST_COUNT = #AvatarList
