if GetLocale() == "ptBR" then


function iclllocaleui()

	arallbuttonmaint = "Listar por Zona" -- Needs review
	arallbuttontak = "Táticas" -- Needs review
		areachatlist1 = "raide"
	areachatlist2 = "aviso de raide"
	areachatlist3 = "oficial"
	areachatlist4 = "grupo"
	areachatlist5 = "guilda"
	areachatlist6 = "dizer"
	areachatlist7 = "gritar"
	areachatlist8 = "si próprio" -- Needs review
	rallachdonel1 = "completo" -- Needs review
	rallachdonel2 = "incompleto" -- Needs review
	rallachievekologarnhp1 = "800K - 1 mln" -- Needs review
	rallachievekologarnhp2 = "3 mln - 4 mln" -- Needs review
	rallachiverepl1 = "Conquistas não completadas em" -- Needs review
	rallachiverepl10 = "ListaLista completa de conquistas necessárias para 'glória do herói/aventureiro' em" -- Needs review
	rallachiverepl11 = "Conquistas necessárias para 'glória do herói/aventureiro' NÃO foram encontradas nessa zona." -- Needs review
	rallachiverepl12 = "Lista completa de conquistas incompletas em" -- Needs review
	rallachiverepl13 = "Conquistas incompletas para" -- Needs review
	rallachiverepl14 = "Lista de todas as conquistas para" -- Needs review
	rallachiverepl15 = "Nenhuma conquista encontrada para o chefe atual com as opções definidas." -- Needs review
	rallachiverepl16 = "Conquistas incompletas para 'glória do herói/aventureiro' para" -- Needs review
	rallachiverepl17 = "Lista completa de conquistas necessárias para 'glória do herói/aventureiro' para" -- Needs review
	rallachiverepl18 = "Lista completa de conquistas incompletas para" -- Needs review
	rallachiverepl19 = "Lista completa de TODAS as conquistas em" -- Needs review
	rallachiverepl2 = "Você completou todas as conquistas daqui." -- Needs review
	rallachiverepl3 = "Local atual não é uma raide ou uma masmorra heróica." -- Needs review
	rallachiverepl4 = "Lista de todas as conquistas em" -- Needs review
	rallachiverepl5 = "Conquistas de grupo desse local não foram encontradas no banco de dados." -- Needs review
	rallachiverepl6 = "Verificação de conquistas desativada." -- Needs review
	rallachiverepl7 = "Mais de 10 conquistas foram encontradas (|cff00ff00%s|r). Lista completa disponível na janela de opções do addon (/rach - Listar por zona)" -- Needs review
	rallachiverepl8 = "Conquistas incompletas para 'glória do herói/aventureiro' em" -- Needs review
	rallachiverepl9 = "Você completou todas as conquistas para 'glória do herói/aventureiro'  nesta zona." -- Needs review
	rallbutton2 = "Escolha outro local" -- Needs review
	rallbutton3 = "<<< Voltar para configurações" -- Needs review
	rallchatshowboss = "Mostrar no chat" -- Needs review
	ralldefaulttactic1 = "Existme ~85 zumbis na rua de inicio, então você precisa de:\n1. Matar o primeiro chefe.\n2. 1.Levar o segundo chefe até a porta da estalagem (ele não irá entrar, apenas traga ele até a entrada).\n3. 2.Espere um minuto ou dois até os zumbis começarem a 'nascer', então mate ele.\n4. 3.Fale com Arthas, então limpe a estalagem, mate o terceiro chefe e fale com Arthas novamente pra que ele abra a passagem na estante.\n5. 1 ou 2 DPS devem voltar onde o segundo chefe foi morto, o resto do grupo continua em frente.\n6. Comece a matar os zumbis simultaneamente nos dois locais até conseguir a conquista."
	ralldefaulttactic10 = "O chefe começa a 'spawnar' vários Lodos aos 50% de vida e irá parar aos 25%. Espere os Lodos virarem os Lodos Férreos que você precisa matar" -- Needs review
	ralldefaulttactic11 = "Permafrio é 'stackado' a cada 2 ou 3 segundos. Você pode sair da mira usando pedras ou 'dispelando' o boss bem rápido." -- Needs review
	ralldefaulttactic12 = "Você tem que passar pelo túnel de gelo antes do terceiro chefe sem que NINGUEM do seu grupo seja atingido por qualquer uma das 'pontas de gelo' que caem\nVocê consegue ver onde a ponta vai cair através de um circulo azul que surge uns ~5 segundos antes da queda" -- Needs review
	ralldefaulttactic13 = "Após limpar a área ANTES de chegar até Mal'Ganis, você entra em uma área aparentemente não tomada pelo flagelo. Há duas maneiras, você pode para a direita (para Mal'Ganis) ou pode ir para a esquerda (para o Corruptor Infinito) se ainda estiver dentro do tempo." -- Needs review
	ralldefaulttactic14 = "Descrição: Acada 30 segundos (apróx.) o chefe irá mirar alguém do grupo e 'castar' uma magia fazendo com que surja um Fragmento de Alma Corrompido, o que deve ser feito aqui é correr pra mais longe possível dele, porque quando essa alma aparece ela começa a se mover em direção a Bronjahm, e chegando nele elas desaparecem. Quando a vida do chefe chegar a 35% ele se teletransporta para o centro da sala e para de se mover.\nTática: Leve ele até a plataforma antes de começar a atacar e espere até que as 4 almas apareçam, então ataque com tudo. Fragmento de Alma Corrompido pode ser retardado."
	ralldefaulttactic15 = "Você deve criar uma rotação para interromper o cast do 'Impacto Fantasma'" -- Needs review
	ralldefaulttactic16 = "O chefe ficará imune por 45 segundos em algum momento da luta, espere e mate ele sem matar nenhuma Fenda Caótica (atenção com o dano e área)" -- Needs review
	ralldefaulttactic17 = "Conquista individual. Frio Intenso estacka nos jogadores a cada 2 segundos. Movimentar-se quebra o efeito. Se você ficar parado por mais de 5 segundos você falha na conquista. Atenção, tem outra habilidade que congela os jogadores por 10 seg, dispele-a" -- Needs review
	ralldefaulttactic18 = "Descrição: o segundo chefe é aleatório, será Confessora Argêntea Albamecha ou Eadric, o Puro. Confessora evoca apenas 1 de 25 memórias para a luta" -- Needs review
	ralldefaulttactic19 = "Descrição: \"Martelo da Justiça\" - stuna um inimigo, deixando-os vulneráveis ao \"Martelo do Íntegro\" e incapazes de se mover ou atacar por 6 segundos.\n\"Martelo do Íntegro\" - arremessa o martelo atingindo um inimigo com 1400 de dano Arcano. Se o alvo não estiver sob o efeito do \"Hammer of Justice\" esse martelo pode ser pego e mandado de volta para quem o lançou.\nTática: Bata no chefe até ele ficar com 25k de vida e espere até ele stunar alguem, dispele o stun e na barra da pessoa que for dispelada aparecerá um novo botão pra lançar o martelo de volta, use!"
	ralldefaulttactic2 = "Apenas fique parado nas escadas matando os mobs. Nenhum adc irá 'spawnar' depois que o escudo de Novos for quebrado e o combate direto for iniciado." -- Needs review
	ralldefaulttactic20 = "Mate os carniçais ou leve o chefe pra longe se eles começarem a castar Explosão." -- Needs review
	ralldefaulttactic21 = "\"Tumba Gélida\" - aprisiona o alvo em um bloco de gelo. Apenas mate o chefe sem matar as tumbas, a magia será castada em jogadores randomicos." -- Needs review
	ralldefaulttactic22 = "Há 2 Hulk do Flagelo perto do chefe, você precisa de 1 deles para a conquista. Aos 50% de vida o chefe começará o 'Ritual da Espada', você tem que matar um Hulk do Flagelo depois que a espada atingir ele" -- Needs review
	ralldefaulttactic23 = "Para matar Grauf você tem que usar 3 arpões simultaneamente" -- Needs review
	ralldefaulttactic24 = "Se o chefe não for morto rapidamente ele irá castar 'Ruína' em si próprio. Apenas ataque o boss com tudo antes dele castar esse buff." -- Needs review
	ralldefaulttactic25 = "Mate os Glóbulos de Linfa rapidamente enquanto tentam se fundir com o chefe" -- Needs review
	ralldefaulttactic26 = "Os Cristais de Controle de Defesas estão espalhados pelas paredes, não clique neles e não deixe o chefe danificar o Lacre da Prisão" -- Needs review
	ralldefaulttactic27 = "Cada vez que você entrar nessa masmorra você poderá enfrentar apenas 2 chefes, de 6 existentes" -- Needs review
	ralldefaulttactic28 = "Se o Guardião Ahn'kahar estiver perto do chefe - o chefe ficará imune a todos os danos, simplesmente leve o adc pra longe do chefe e mate-o rapidamente" -- Needs review
	ralldefaulttactic29 = "Bjarngrim tem a sua disposição três plataformas onde ele pega Carga Elétrica Temporária. Bata nele com tudo quando ele parar pra pegar as Cargas" -- Needs review
	ralldefaulttactic3 = "Descrição: algumas vezes o chefe causa danos a inimigos dentro de 50 jardas. Para cada inimigo que sofrer dano dessa forma o chefe ganha 1 stack de \"Consumir\"\nTatica: Ataque o chefe com tudo"
	ralldefaulttactic30 = "De vez em quando o chefe irá atacar a Bigorna de Volkhan criando 2 Golems Derretidos. Mate ele antes que ele cria 4 Golems" -- Needs review
	ralldefaulttactic31 = "Na segunda (vôo) fase Onyxia irá castar Respiração Profunda, corra para a direção oposta a dela (ela irá voar pela sala  na diagonal), se vocês atacarem com tudo  - ele não irá castar essa magia" -- Needs review
	ralldefaulttactic32 = "Aos 65% de vida Onyxia entrará na segunda fase, quando ela vier pro chão vocês tem 10 segundos para correr pela caverna forçando os dragonetes a spawnar" -- Needs review
	-- ralldefaulttactic33 = ""
	-- ralldefaulttactic34 = ""
	-- ralldefaulttactic35 = ""
	-- ralldefaulttactic36 = ""
	ralldefaulttactic37 = "Há duas maneiras de conseguir essa conquista: 1. Não mate os adc 2. Mate os adc bem longe do chefe" -- Needs review
	-- ralldefaulttactic38 = ""
	ralldefaulttactic39 = "Na primeira fase você deve matar os adc de Kel'Thuzad, ataque as abominações e mate a quantidade necessária" -- Needs review
	ralldefaulttactic4 = "Mate a quantidade necessária de dinossauros durante a luta contra o chefe" -- Needs review
	ralldefaulttactic40 = "Durante a luta o chefe irá castar Espigão Ósseo nos jogadores (1 para 10 e 3 para 25), eles devem ser destruidos bem rápido" -- Needs review
	-- ralldefaulttactic41 = ""
	-- ralldefaulttactic42 = ""
	-- ralldefaulttactic43 = ""
	-- ralldefaulttactic44 = ""
	-- ralldefaulttactic45 = ""
	-- ralldefaulttactic46 = ""
	-- ralldefaulttactic47 = ""
	-- ralldefaulttactic48 = ""
	-- ralldefaulttactic49 = ""
	ralldefaulttactic5 = "Bata no chefe antes dele chegar e bloquear as portas" -- Needs review
	-- ralldefaulttactic50 = ""
	ralldefaulttactic51 = "É possivel fazer essa conquista sozinho. Aggre vários Defensores Forjados em Aço e mate-os, use o rastreador do jogo para te ajudar" -- Needs review
	ralldefaulttactic52 = "Conquista individual. Passageiros podem ser lançados no Leviatã Flamejante e podem matar Torretas de Defesa, para conseguir essa conquista você deve dar um golpe fatal (killing blow)" -- Needs review
	ralldefaulttactic53 = "Jogadores podem ser lançados (dos veículos Demolidores) no Leviatã Flamejante para destruir suas torretas. Destruir todas as torretas ativa 'Circuito Sobrecarregado' deixando o Leviatã stunado, fazendo ele receber 50% a mais de dano e zerando os stacks do seu Ganhando Velocidade. Essa conquista requer que todos da raide ignorem essa mecanica" -- Needs review
	-- ralldefaulttactic54 = ""
	-- ralldefaulttactic55 = ""
	-- ralldefaulttactic56 = ""
	-- ralldefaulttactic57 = ""
	ralldefaulttactic58 = "A descrição da conquista está incorreta e com dificil entendimento." -- Needs review
	-- ralldefaulttactic59 = ""
	-- ralldefaulttactic6 = ""
	-- ralldefaulttactic60 = ""
	-- ralldefaulttactic61 = ""
	-- ralldefaulttactic62 = ""
	-- ralldefaulttactic63 = ""
	-- ralldefaulttactic64 = ""
	-- ralldefaulttactic65 = ""
	-- ralldefaulttactic66 = ""
	-- ralldefaulttactic67 = ""
	-- ralldefaulttactic68 = ""
	-- ralldefaulttactic69 = ""
	-- ralldefaulttactic7 = ""
	-- ralldefaulttactic70 = ""
	-- ralldefaulttactic71 = ""
	-- ralldefaulttactic72 = ""
	-- ralldefaulttactic73 = ""
	-- ralldefaulttactic74 = ""
	-- ralldefaulttactic75 = ""
	-- ralldefaulttactic76 = ""
	ralldefaulttactic77 = "Modo-dificil. Não mate nenhuma Saronita, espere que se transformem em Ânimus de Saronita, então mate todos - depois derrote o chefe" -- Needs review
	ralldefaulttactic78 = "Use /kiss em Sara na fase 2 da luta contra Yogg-Saron. Macro:\n/tar Sara\n/kiss"
	ralldefaulttactic79 = "Durante a fase 2, portais irão surgir perto de Yogg. Quando você entrar em um deles, você estará em uma das três visões" -- Needs review
	ralldefaulttactic8 = "Para ganhar o debuff 'Resíduo', você deve ser atingido pelo ataque frontal de Eck: Cuspe de Eck. Depois disso mate o ultimo chefe, sem morrer" -- Needs review
	ralldefaulttactic80 = "Você começa a luta com 100% de sanidade, que vai diminuindo a medida que você é atingido. Durante a luta Poços da Sanidade irtão spawnar, eles são usados pra recuperar sua sanidadade (caso você peça Freya para te ajudar).Quando a sanidade chega a 0% o jogador passa a ser controlado por Yogg-Saron até que ele (ou o próprio Yogg-Saron) morra" -- Needs review
	ralldefaulttactic81 = "Buracos Negros são formados quando Estrelas em Colapso morrem. Essa conquista consiste em fechar os Buracos Negros levando as Constelações Vivas até eles simultaneamente" -- Needs review
	ralldefaulttactic82 = "Cada vez que Parvo Desorientado usa Investida em alguem, um numero aleatório de Ratos da Mina surgem no local onde o jogador é arremessado. O contador não é resetado, então você pode fazer aos poucos" -- Needs review
	ralldefaulttactic83 = "Para conseguir essa conquista você precisa matar o chefe na primeira tentativa e evitar que o ceifador tome qualquer dano durante as lutas (ele é imune a dano de fogo)" -- Needs review
	ralldefaulttactic84 = "Conquista individual. O chefe irá castar paredes de fogo durante toda a segunda fase" -- Needs review
	ralldefaulttactic85 = "Depois de cada 'Asfixiar' o chefe usará Suspensão da Execução - interrompa imediatamente" -- Needs review
	ralldefaulttactic86 = "Os ads (não o chefe) ficam castando 'Potencialização Profana' - interrompa todos os casts" -- Needs review
	ralldefaulttactic87 = "Quando os adc vierem faça um deles andar em cima de um Gêiser. Não é necessário matar o chefe para conseguir essa conquista" -- Needs review
	ralldefaulttactic88 = "Não mate o Beemote Obstinado até que você tenha o Surto das Marés em você na terceira fase" -- Needs review
	ralldefaulttactic89 = "Deixe os zelotes evoluirem um a um então destrua eles o mais rápido que puder (antes deles destruirem sem tanque). Eles 'evoluem' se você não ficar parado nos raios" -- Needs review
	ralldefaulttactic9 = "Na verdade, o feitiço empalar não será lançado no alvo de maior ameaça, por isso você precisa de 2 tanks. Mate o chefe depois que todos os jogadores do grupo forem empalados" -- Needs review
	ralldefaulttactic90 = "Conquista individual. Pule quando o chefe castar 'Atração Estática' - assim você não ficará preso por essa hablidade, a melhor maneiro de conseguir essa conquista é ficar pulando a luta toda" -- Needs review
	ralldefaulttactic91 = "Para que ele fique infectado, você dele matar um dos Habitante Troggs infectads perto dele. Atenção: 'Malícia de Modgud' - Aumenta o dano feito em 100%" -- Needs review
	ralldefaulttactic92 = "A conquista irá para todos os membros do grupo. Há vários orbs na masmorra mas você precisa apenas de cinco deles. Por exemplo, 2 deles estão debaixo da plataforma do segundo chefe, pra pega-los você dele usar o tornado durante a luta" -- Needs review
	-- ralldefaulttactic93 = ""
	ralldefaulttactic94 = "Você pode completar apenas metade dessa conquista vindo pela primeira vez aqui. Se você quiser ser mordido (ou não ser mordido) fale agora, quanto mais dps for feito menos pessoas terão de ser mordidas" -- Needs review
	ralldefaulttacticmain1 = "O addon irá informar no chat quando for possível matar o chefe!" -- Needs review
	ralldefaulttacticmain2 = "Atenção: seus pets e totems podem fazer essa conquista falhar!"
	ralldefaulttacticmain3 = "Falhas de conquistas serão salvas no ID das masmorras, e você não poderá reiniciar para aquele dia" -- Needs review
	ralldifparty = "grupo" -- Needs review
	ralldifraid = "raide" -- Needs review
	ralldifscenario = "cenário" -- Needs review
	rallglory = "glória" -- Needs review
	rallmanualtxt1 = "Expansão" -- Needs review
	rallmanualtxt2 = "Dificuldade:" -- Needs review
	rallmanualtxt3 = "Local:" -- Needs review
	rallmenutxt1 = "Lista de conquistas disponíveis no local atual" -- Needs review
	rallmenutxt2 = "Lista de conquistas pelo local escolhido" -- Needs review
	rallmenutxt3 = "Táticas para conquistas de grupo" -- Needs review
	rallnoaddontrack = "O addon NÃO está rastreando" -- Needs review
	rallnotfoundachiv1 = "conquistas incompletas não foram encontradas" -- Needs review
	rallnotfoundachiv2 = "nenhuma conquista" -- Needs review
	rallnotfromboss = "não é de chefe" -- Needs review
	rallsend = "Enviar" -- Needs review
	ralltacticbutsave1 = "Aplicar mudanças" -- Needs review
	ralltacticbutsave2 = "Restairar tática padrão" -- Needs review
	ralltactictext1 = "Escolha a conquista" -- Needs review
	ralltactictext2 = "precisa de tática" -- Needs review
	ralltactictext3 = "tática: /raida" -- Needs review
	ralltitle2 = "Este módulo informa sobre conquistas no |cff00ff00local atual|r, quando você entra em uma masmorra. Também pode mostrar quando um chefe na sua mira é critério de alguma conquista. P.S  '|cffff0000não rastreado pelo addon|r' significa que o addon não pode rastrear a conquista e não irá informar em caso de falha, '|cffff0000não é de chefe|r' - o critério da conquista não envolve a morte de nenhum chefe, podendo ser algum objeto ou qualquer outra coisa. No quadro atual, você pode ver todas as conquistas do grupo disponíveis no local atual" -- Needs review
	ralltitle3 = "Este módulo mostra as conquistas disponíveis no local escolhido. Você pode enviar essa informação para o chat" -- Needs review
	ralltitle33 = "'tática: /raida' mostra no chat táticas para conquistas que possam vir a ser difíceis de conseguiur. Aqui você pode ver todas as táticas, é muito util quando você está indo na masmorra pela primeira vez. Você pode editar o texto e enviar para o chat. Todas as mudanças serão aplicadas à todos os personagens.\nP.S. Envie sei comentários ou tática para mim, e e eles seram inseridos nesse addon para ajudar os outros.\nP.S.2 Encontrou erros de tradução? Entre em contato comigo pelo Curse e ajude a corrigir!"
	ralltooltiptxt = "Mostrar em dicas" -- Needs review
	ralltooltiptxt2 = "RA: Encontrados %s conquistas" -- Needs review
	ralltooltiptxt21 = "RA: Conquistas encontradas" -- Needs review
	ralltooltiptxt3 = "Mais informações: /raida" -- Needs review
	ralltxt1 = "Quando você entra em uma masmorra é informado de:" -- Needs review
	ralltxt10 = "apenas conquistas incompletas, necessárias para 'glória do herói/aventureiro'" -- Needs review
	ralltxt11 = "apenas conquistas necessárias para 'glória do herói/aventureiro', incluindo conquistas já completadas" -- Needs review
	ralltxt12 = "Versão COMPLETA - TODAS as conquistas que eu preciso, incluindo mortes de chefes nos modos normal/heróico etc" -- Needs review
	ralltxt13 = "Versão COMPLETA - TODAS as conquistas desse local" -- Needs review
	ralltxt2 = "apenas conquistas incompletas" -- Needs review
	ralltxt3 = "todas as conquistas, incluindo as já completadas" -- Needs review
	ralltxt4 = "apenas conquistas incompletas necssárias para 'glória do herói/aventureiro'" -- Needs review
	ralltxt5 = "apenas conquistas necessárias para 'glória do herói/aventureiro', incluindo as já completadas" -- Needs review
	ralltxt6 = "Versão COMPLETA - TODAS as conquistas que eu preciso, incluindo mortes de chefes nos modos normal/heróico etc" -- Needs review
	ralltxt7 = "Quando você mira um chefe é informado de:" -- Needs review
	ralltxt8 = "apenas conquistas incompletas" -- Needs review
	ralltxt9 = "todas as conquistas, incluindo as já completadas" -- Needs review
	ralltxtoff = "(desativado)" -- Needs review
	ralltxton = "(ativado)" -- Needs review
	ralluilooktactic1 = "Mostrar táticas" -- Needs review
	ralluilooktactic3 = "|cffff0000Sem táticas|r, talvez essa conquista seja fácil de entender apenas lendo sua descrição. se você quiser |cff00ff00adcionar sua próprio tática - insira-a aqui|r" -- Needs review
	ralluilooktactic4 = "Mudanças salvas com sucesso." -- Needs review
	ralluilooktactic5 = "Tática" -- Needs review
	rallwhisper = "sussurro:" -- Needs review
	rallzonenotfound = "Local atual não foi encontrado no bando de dados." -- Needs review

end


end