--[[ Credit for these translations goes to:
	TomHB
	fiesekeule
	Quevain
	XNuclearWinterX
	erwinmeier
	xevilgrin
	Farronski
--]]
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "deDE", false)
if not L then return end


L["AIR"] = "Luft" -- Needs review
L["ALLOWVERSIONWARN"] = "Melde neue Version" -- Needs review
L["ALPHA"] = "Alpha" -- Needs review
L["ANIM_ACTVTNGLOW"] = "Icon: Aktivierungs Rahmen" -- Needs review
L["ANIM_ACTVTNGLOW_DESC"] = "Zeigt den Zauberaktivierungs-Rahmen von Blizzard auf dem Icon an." -- Needs review
L["ANIM_COLOR_DESC"] = "Stelle Farbe und Deckkraft ein." -- Needs review
L["ANIM_FADE"] = "Pulsieren" -- Needs review
L["ANIM_FADE_DESC"] = "Auswählen zum pulsieren. Abwählen zum blinken." -- Needs review
L["ANIM_ICONFADE"] = "Icon: Ein-/Ausblenden" -- Needs review
L["ANIM_ICONFLASH_DESC"] = "Farbiges Blinken über dem Symbol." -- Needs review
L["ANIM_ICONSHAKE_DESC"] = "Lässt das Symbol wackeln." -- Needs review
L["ANIM_PERIOD"] = "Periodenlänge" -- Needs review
L["ANIM_SCREENFLASH"] = "Bildschirm: Blinken" -- Needs review
L["ANIM_SCREENFLASH_DESC"] = "Farbiges Blinken über dem Bildschirm." -- Needs review
L["ANIM_SCREENSHAKE_DESC"] = [=[Lässt den Bildschirm wackeln.

HINWEIS: Funktioniert nur wenn ausserhalb des Kampfes oder wenn nameplates seit dem letzten login noch nicht aktiviert wurden.]=] -- Needs review
L["ASPECT"] = "Aspekt" -- Needs review
L["AURA"] = "Aura" -- Needs review
L["Bleeding"] = "Blutend" -- Needs review
L["BonusStamina"] = "Erhöhte Ausdauer" -- Needs review
L["BOTTOM"] = "unten"
L["BOTTOMLEFT"] = "unten links"
L["BOTTOMRIGHT"] = "unten rechts"
L["BurstManaRegen"] = "Stark erhöhte Mana Regeneration" -- Needs review
L["CASTERFORM"] = "Zaubergestalt"
L["CENTER"] = "Mitte" -- Needs review
L["CHOOSENAME_DIALOG"] = [=[Geben Sie den Namen oder die ID der Zauber / Fähigkeit / Gegenstand / Buff / Debuff ein, die dieses Symbol überwachen soll. Sie können mehrere Buffs / Debuffs hinzufügen indem Sie diese mit Semikolon (';') trennen.

Sie können Zauber, Gegenstände oder Chatlinks per Shift-Klick oder Drag and Drop hinzufügen.]=]
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "Vordefinierte Zauber-Sets / Dispel-Typen" -- Needs review
L["CHOOSENAME_DIALOG_PETABILITIES"] = "Begleiterfähigkeiten müssen per ID eingetragen werden!" -- Needs review
L["CLEU_CAT_SWING"] = "Nahkampf/Fernkampf" -- Needs review
L["CLEU_DAMAGE_SHIELD_DESC"] = "Tritt ein, wenn ein Schadensschild  (%s, %s, etc., aber nicht %s) Schaden an einer Einheit verursacht." -- Needs review
L["CLEU_DAMAGE_SHIELD_MISSED_DESC"] = "Tritt ein, wenn ein Schadensschild  (%s, %s, etc., aber nicht %s) keinen Schaden an einer Einheit verursacht." -- Needs review
L["CLEU_DAMAGE_SPLIT_DESC"] = "Tritt ein, wenn der schaden zwischen zwei oder mehr Zielen aufgeteilt wird." -- Needs review
L["CLEU_ENCHANT_APPLIED_DESC"] = "Bezieht temporäre Waffenverzauberungen wie Gifte und Shamanen Tränke mit ein." -- Needs review
L["CLEU_ENCHANT_REMOVED_DESC"] = "Bezieht temporäre Waffenverzauberungen wie Gifte und Shamanen Tränke mit ein." -- Needs review
L["CLEU_ENVIRONMENTAL_DAMAGE_DESC"] = "Beinhaltet/Erfasst Schaden von Lava, Erschöpfung, Ertrinken und Fallen." -- Needs review
L["CLEU_SPELL_EXTRA_ATTACKS_DESC"] = "Tritt ein, wenn ein extra Nahkampfangriff durch eine Fähigkeit gewährt wird." -- Needs review
L["CLEU_SPELL_LEECH"] = "Ressourcenverbrauch" -- Needs review
L["CLEU_UNIT_DESTROYED_DESC"] = "Tritt ein, wenn eine Einheit, wie z.B. ein Totem zerstört wird." -- Needs review
L["CMD_OPTIONS"] = "Optionen"
L["CNDTCAT_ATTRIBUTES_PLAYER"] = "Spieler-Attribute" -- Needs review
L["CNDTCAT_ATTRIBUTES_UNIT"] = "Einheiten-Attribute" -- Needs review
L["COLOR_CBC"] = "Abklingzeit-Leiste - Ende" -- Needs review
L["COLOR_CBC_DESC"] = "Farbe der Abklingzeit/Restdauer overlay-Leiste, wenn die Abklingzeit/Restdauer beendet ist." -- Needs review
L["COLOR_CBS"] = "Abklingzeit-Leiste - Beginn" -- Needs review
L["COLOR_COA"] = "Zählend, Timer deaktiviert, immer sichtbar" -- Needs review
L["COLOR_COLOR"] = "Farbe" -- Needs review
L["COLOR_COS"] = "Zählend, Timer deaktiviert, manchmal sichtbar" -- Needs review
L["COLOR_CTA"] = "Zählend, Timer aktiviert, immer sichtbar" -- Needs review
L["COLOR_CTS"] = "Zählend, Timer aktiviert, manchmal sichtbar" -- Needs review
L["COLOR_DEFAULT"] = "*Globale Farben*" -- Needs review
L["COLOR_DESATURATE"] = "Grau" -- Needs review
L["COLOR_DESATURATE_DESC"] = "Bestätigen Sie dies um das Symbol zu entfärben, wenn diese Farbe genutzt wird. Dies wird alle Farben entfernen und das Symbol Schwarz/Weiß machen." -- Needs review
L["COLOR_NA"] = "Beendet, immer sichtbar" -- Needs review
L["COLOR_NS"] = "Beendet, manchmal sichtbar" -- Needs review
L["COLOR_OOM"] = "niedriges Mana" -- Needs review
L["COLOR_OOM_DESC"] = "Farbe des Symbols, wenn Sie nicht über die Ressourcen verfügen um eine Fähigkeit zu nutzen." -- Needs review
L["COLOR_OOR"] = "Außer Reichweite" -- Needs review
L["COLOR_OOR_DESC"] = "Farbe des Symbols, wenn Sie außerhalb der Reichweite sind um eine Fähigkeit zu nutzen." -- Needs review
L["COLOR_OORM"] = "Außer Reichweite & Mana" -- Needs review
L["COLOR_OORM_DESC"] = "Farbe des Symbols, wenn Sie nicht über die Ressourcen verfügen und außerhalb der Reichweite sind um eine Fähigkeit zu nutzen." -- Needs review
L["COLOR_OVERRIDEDEFAULT"] = "Verwendungszweck" -- Needs review
L["COLOR_OVERRIDEDEFAULT_DESC"] = "Bestätigen Sie dies um die *Globale Farben* Einstellungen zu überschreiben und stattdessen diese Einstellungen zu nutzen." -- Needs review
L["COLOR_RESET_DESC"] = "Setzt diese Einstellungen zu ihren Standardwerten zurück." -- Needs review
L["CONDITIONALPHA_CONDITIONICON"] = "unpassende Dauer" -- Needs review
L["CONDITIONALPHA_CONDITIONICON_DESC"] = "Dies wird verwendet, falls die Anforderungen an die Dauer nicht erreicht werden. Diese Einstellung wird ignoriert, falls das Icon bereits von den beiden anderen Unsichtsbarkeitseinstellungen verdeckt wird." -- Needs review
L["CONDITIONORMETA_CHECKINGINVALID"] = "Warnung! Gruppe %d, Icon %d prüft ein ungültiges Symbol (Gruppe %d, Symbol %d)" -- Needs review
L["CONDITIONPANEL_ALIVE"] = "Einheit lebt" -- Needs review
L["CONDITIONPANEL_ALIVE_DESC"] = "Die Bedingung wird erfüllt, wenn die spezifizierte Einheit lebt."
L["CONDITIONPANEL_AND"] = "und"
L["CONDITIONPANEL_ANDOR"] = "und / oder"
L["CONDITIONPANEL_CLASSIFICATION"] = "Einheit Klassifizierung" -- Needs review
L["CONDITIONPANEL_COMBAT"] = "Einheit im Kampf"
L["CONDITIONPANEL_COMBO"] = "Kombo Punkte"
L["CONDITIONPANEL_ECLIPSE_DESC"] = "Finsternis hat eine Reichweite von -100 (Mondfinsternis) bis 100 (Sonnenfinsternis). Gib -80 ein, wenn du möchtest, dass das Symbol mit einem Wert von 80 Mond-Macht arbeitet. " -- Needs review
L["CONDITIONPANEL_EQUALS"] = "gleich"
L["CONDITIONPANEL_EXISTS"] = "Einheit existiert"
L["CONDITIONPANEL_GREATER"] = "größer als"
L["CONDITIONPANEL_GREATEREQUAL"] = "größer als oder gleich"
L["CONDITIONPANEL_ICON"] = "Zeige Symbol"
L["CONDITIONPANEL_ICON_DESC"] = "Die Bedingung wird erfüllt, wenn das Symbol derzeit mit einer Transparenz von über 0 angezeigt oder versteckt mit einer Transparenz von 0 wird." -- Needs review
L["CONDITIONPANEL_ICON_HIDDEN"] = "Versteckt" -- Needs review
L["CONDITIONPANEL_ICON_SHOWN"] = "Gezeigt" -- Needs review
L["CONDITIONPANEL_INSTANCETYPE"] = "Instanz-Typ" -- Needs review
L["CONDITIONPANEL_LESS"] = "kleiner als"
L["CONDITIONPANEL_LESSEQUAL"] = "kleiner als oder gleich"
L["CONDITIONPANEL_LEVEL"] = "Einheit Level" -- Needs review
L["CONDITIONPANEL_MOUNTED"] = "Gemountet" -- Needs review
L["CONDITIONPANEL_NAME"] = "Einheit Name" -- Needs review
L["CONDITIONPANEL_NAMETOOLTIP"] = "Mehrere Namen können mit Semikolon (;) getrennt werden. Die Bedingung ist erfüllt, wenn einer der Namen zutrifft." -- Needs review
L["CONDITIONPANEL_NOTEQUAL"] = "ungleich"
L["CONDITIONPANEL_OPERATOR"] = "Operator"
L["CONDITIONPANEL_OR"] = "oder"
L["CONDITIONPANEL_POWER"] = "primäre Ressource"
L["CONDITIONPANEL_POWER_DESC"] = "Prüft auf Energie, falls die Einheit ein Druide in Katzengestalt ist, auf Wut, wenn die Einheit ein Krieger ist, usw." -- Needs review
L["CONDITIONPANEL_PVPFLAG"] = "Einheit ist für PvP markiert." -- Needs review
L["CONDITIONPANEL_REMOVE"] = "Bedingung löschen" -- Needs review
L["CONDITIONPANEL_RUNES_DESC"] = "Diese Bedingung prüft den Zustand von Runen. Jede Rune hat eine eigene Checkbox. Ein Haken prüft ob die Rune verfügbar ist, ein Kreuz prüft ob eine Rune nicht verfügbar ist, bei einer leeren Checkbox wird die Rune ignoriert." -- Needs review
L["CONDITIONPANEL_SWIMMING"] = "Schwimmend" -- Needs review
L["CONDITIONPANEL_TYPE"] = "Typ"
L["CONDITIONPANEL_UNIT"] = "Einheit"
L["CONDITIONPANEL_VALUEN"] = "Wert"
L["CONDITIONPANEL_VEHICLE"] = "Einheit kontrolliert Fahrzeug" -- Needs review
L["CONDITIONS"] = "Bedingungen" -- Needs review
L["COPYGROUP"] = "Kopiere Gruppe" -- Needs review
L["COPYPOSSCALE"] = "Kopiere Position/Größe" -- Needs review
L["CREATURETYPE_1"] = "Wildtier"
L["CREATURETYPE_10"] = "Nicht spezifiziert"
L["CREATURETYPE_11"] = "Totem"
L["CREATURETYPE_12"] = "Haustier"
L["CREATURETYPE_13"] = "Gaswolke"
L["CREATURETYPE_14"] = "Ungezähmtes Tier"
L["CREATURETYPE_2"] = "Drachkin"
L["CREATURETYPE_3"] = "Dämon"
L["CREATURETYPE_4"] = "Elementar"
L["CREATURETYPE_5"] = "Riese"
L["CREATURETYPE_6"] = "Untoter"
L["CREATURETYPE_7"] = "Humanoid"
L["CREATURETYPE_8"] = "Kleintier"
L["CREATURETYPE_9"] = "Mechanisch"
L["CrowdControl"] = "Crowd Control" -- Needs review
L["Curse"] = "Fluch"
L["DISABLED"] = "Deaktiviert"
L["Disarmed"] = "Entwaffnet"
L["Disease"] = "Krankheit"
L["Disoriented"] = "Verwirrt"
L["DR-MindControl"] = "Gedankenkontrolle" -- Needs review
L["EARTH"] = "Erde" -- Needs review
L["ECLIPSE_DIRECTION"] = "Finsternis Richtung"
L["elite"] = "Elite"
L["ENABLINGOPT"] = "TellMeWhen_Options ist deaktiviert. Aktiviere..." -- Needs review
L["EVENTS_SETTINGS_CNDTJUSTPASSED_DESC"] = "Verhindert, dass der Event abgearbeitet wird, bis die Bedingung, die oben konfiguriert wurde, zu erfolgen begonnen hat." -- Needs review
L["EVENTS_SETTINGS_HEADER"] = "Ereignis-Einstellungen" -- Needs review
L["EVENTS_SETTINGS_ONLYSHOWN"] = "Nur nutzen, wenn das Icon sichtbar ist." -- Needs review
L["EVENTS_SETTINGS_ONLYSHOWN_DESC"] = "Das Bestätigen dieser Einstellung wird das Ereignis daran hindern jegliche verknüpften Handlungen auszuführen, sollte das Icon nicht sichtbar sein." -- Needs review
L["EVENTS_SETTINGS_PASSINGCNDT"] = "Führe dies nur durch, wenn die Bedingung beendet ist." -- Needs review
L["EVENTS_SETTINGS_PASSINGCNDT_DESC"] = "Verhindert, dass der Event abgearbeitet wird, bis die Bedingung, die unten konfiguriert wurde, erfolgreich war." -- Needs review
L["EXPORT_f"] = "Export %s" -- Needs review
L["EXPORT_HEADING"] = "Export" -- Needs review
L["EXPORT_TOCOMM"] = "An Spieler" -- Needs review
L["EXPORT_TOSTRING"] = "In String (Zeichenkette)" -- Needs review
L["EXPORT_TOSTRING_DESC"] = "Eine Zeichenfolge die die notwendigen Daten enthält wird im Eingabefeld angezeigt. Drücke STRG+C um diese zu kopieren, und füge sie dann dort ein wo du sie anderen teilen möchtest." -- Needs review
L["FALSE"] = "Falsch"
L["Feared"] = "Furcht"
L["fGROUP"] = "Gruppe %s" -- Needs review
L["fICON"] = "Icon %s" -- Needs review
L["FIRE"] = "Feuer" -- Needs review
L["FONTCOLOR"] = "Schriftfarbe"
L["FONTSIZE"] = "Schriftgröße"
L["GCD"] = "Globale Abklingzeit" -- Needs review
L["GROUPADDONSETTINGS"] = "Gruppeneinstellungen" -- Needs review
L["GROUPCONDITIONS"] = "Gruppenbedingungen" -- Needs review
L["GROUPICON"] = "Gruppe: %s, Symbol %s" -- Needs review
L["Heals"] = "Spieler Heilungen"
L["HELP_EXPORT_DOCOPY_MAC"] = "Drücke |cff7fffffCMD+C|r zum kopieren" -- Needs review
L["HELP_EXPORT_DOCOPY_WIN"] = "Drücke |cff7fffffCTRL+C|r zum kopieren" -- Needs review
L["ICON"] = "Symbol" -- Needs review
L["ICONALPHAPANEL_FAKEHIDDEN"] = "Unsichtbar" -- Needs review
L["ICONALPHAPANEL_FAKEHIDDEN_DESC"] = "Macht das Symbol unsichtbar, lässt es aber aktiv damit andere Symbole verknüpfte Bedingungen weiterhin prüfen können." -- Needs review
L["ICONGROUP"] = "Symbol: %s (Gruppe: %s)" -- Needs review
L["ICONMENU_ABSENT"] = "fehlend" -- Needs review
L["ICONMENU_ALPHA"] = "Transparenz"
L["ICONMENU_ANCHORTO_UIPARENT"] = "Anker zurücksetzen" -- Needs review
L["ICONMENU_BAROFFS"] = [=[Die Leistendauer wird um diese Dauer erweitert/gekürzt.

Dies ist z.B. nützlich für personalisierte Indikatoren für wann Sie einen neuen Zauber beginnen sollten um einen Buff/Debuff vom Auslaufen abzuhalten.
]=] -- Needs review
L["ICONMENU_BOTH"] = "Entweder"
L["ICONMENU_BUFF"] = "Buff"
L["ICONMENU_BUFFDEBUFF"] = "Buff / Debuff"
L["ICONMENU_BUFFDEBUFF_DESC"] = "Prüft Buffs und/oder Debuffs." -- Needs review
L["ICONMENU_BUFFTYPE"] = "Buff oder Debuff"
L["ICONMENU_CAST"] = "Zauberspruch" -- Needs review
L["ICONMENU_CAST_DESC"] = "Prüft gewirkte und kanalisierte Zauber." -- Needs review
L["ICONMENU_CASTS"] = "Zaubersprüche"
L["ICONMENU_CASTSHOWWHEN"] = "Zeige, wenn ein Zauber" -- Needs review
L["ICONMENU_CHECKNEXT"] = "Prüfe Sub-Metasymbole" -- Needs review
L["ICONMENU_CHECKNEXT_DESC"] = [=[Checken dieser Box bewirkt, dass dieses Symbol alle Symbole in allen Metasymbolen, die es prüft, ebenso prüft.

Zusätzlich zeigt dieses Symbol keine Symbole an, die bereits von anderen Metaicons angezeigt werden, die weiter vorne in der Aktualisierungsreihenfolge liegen. Die Aktualisierungsreihenfolge kann in den Haupt- und Gruppenoptionen konfiguriert werden.]=] -- Needs review
L["ICONMENU_CHOOSENAME_WPNENCH"] = "Wählen Sie eine oder mehrere Verzauberungen zum Prüfen." -- Needs review
L["ICONMENU_CLEU"] = "Kampfereignis" -- Needs review
L["ICONMENU_COOLDOWNCHECK"] = "Abklingzeit prüfen" -- Needs review
L["ICONMENU_COOLDOWNCHECK_DESC"] = "Auswahl bewirkt, dass das Symbol während der Abklingzeit als nicht nutzbar behandelt wird." -- Needs review
L["ICONMENU_COPYHERE"] = "Hierher kopieren" -- Needs review
L["ICONMENU_DEBUFF"] = "Debuff"
L["ICONMENU_DISPEL"] = "Dispel-Typ" -- Needs review
L["ICONMENU_DURATION_MAX_DESC"] = "Maximale Dauer erlaubt um das Symbol anzuzeigen. (In Sekunden)" -- Needs review
L["ICONMENU_DURATION_MIN_DESC"] = "Minimale Dauer erlaubt um das Symbol anzuzeigen. (In Sekunden)" -- Needs review
L["ICONMENU_ENABLE"] = "Aktiviert"
L["ICONMENU_FOCUS"] = "Fokus"
L["ICONMENU_FOCUSTARGET"] = "Fokusziel"
L["ICONMENU_FRIEND"] = "freundliche Einheiten"
L["ICONMENU_HIDEUNEQUIPPED"] = "Unsichtbar, wenn Waffenplatz leer ist." -- Needs review
L["ICONMENU_HOSTILE"] = "feindliche Einheiten"
L["ICONMENU_ICD"] = "Interne Abklingzeit" -- Needs review
L["ICONMENU_ICDAURA_DESC"] = [=[Mögliche Auslöser für interne Abklingzeiten: Spieler selbst erhält Buff/Debuff, Effekt fügt Schaden zu oder Effekt erfüllt den Spieler mit Mana/Wut/etc.

Es muss der Name/die ID des Buffs/Debuffs/Effekts, der erhalten/ausgeführt wird, wenn die interne Abklingzeit beginnt, angegeben werden.]=] -- Needs review
L["ICONMENU_ICDBDE"] = "Buff/Debuff/Schaden/Energieeffekt/Beschwörung" -- Needs review
L["ICONMENU_ICDTYPE"] = "Ausgelöst durch" -- Needs review
L["ICONMENU_IGNORERUNES"] = "Ignoriere Runen"
L["ICONMENU_IGNORERUNES_DESC"] = "Wählen Sie dies aus, wenn ein Cooldown als nutzbar behandelt werden soll, wenn lediglich Runen benötigt werden (oder der GCD (globale Abklingzeit) aktiv ist)." -- Needs review
L["ICONMENU_IGNORERUNES_DESC_DISABLED"] = "Du musst die \"Cooldown Überprüfung\" Einstellung wählen, um \"Runen ignorieren\" einzuschalten." -- Needs review
L["ICONMENU_INVERTBARS"] = "Leisten auffüllen"
L["ICONMENU_ITEMCOOLDOWN"] = "Item Abklingzeit" -- Needs review
L["ICONMENU_ITEMCOOLDOWN_DESC"] = "Prüft die Abklingzeit von Items." -- Needs review
L["ICONMENU_MANACHECK"] = "Ressourcen Check" -- Needs review
L["ICONMENU_MANACHECK_DESC"] = "Auswahl bewirkt, dass das Symbol die Farbe ändert, wenn kein/e Mana/Wut/Runenmacht/etc. vorhanden ist." -- Needs review
L["ICONMENU_META"] = "Meta Symbol"
L["ICONMENU_META_DESC"] = [=[Kombiniert mehere andere Symbole in einem.
Symbole, die immer unsichtbar sind, werden hier trotzdem angezeigt.]=] -- Needs review
L["ICONMENU_MOUSEOVER"] = "Mausover"
L["ICONMENU_MOUSEOVERTARGET"] = "Mausover's Ziel" -- Needs review
L["ICONMENU_MOVEHERE"] = "hierher verschieben" -- Needs review
L["ICONMENU_MULTISTATECD"] = "Multi-Zustand Fähigkeit" -- Needs review
L["ICONMENU_MULTISTATECD_DESC"] = "Prüft Fähigkeiten, die mehere Zustände annehmen können. (z.B. Segenswort: Epiphanie)" -- Needs review
L["ICONMENU_ONLYEQPPD"] = "nur wenn ausgerüstet" -- Needs review
L["ICONMENU_ONLYIFCOUNTING"] = "Anzeige nur bei aktiviertem Timer." -- Needs review
L["ICONMENU_ONLYINTERRUPTIBLE"] = "Nur unterbrechbare Zauber"
L["ICONMENU_ONLYMINE"] = "Nur zeigen, wenn selbst gezaubert" -- Needs review
L["ICONMENU_PETTARGET"] = "Begleiterziel"
L["ICONMENU_PRESENT"] = "vorhanden" -- Needs review
L["ICONMENU_RANGECHECK"] = "Reichweiten Check" -- Needs review
L["ICONMENU_RANGECHECK_DESC"] = "Auswahl bewirkt, dass das Symbol die Farbe ändert, wenn Sie außer Reichweite sind." -- Needs review
L["ICONMENU_REACT"] = "Einheit Reaktion"
L["ICONMENU_REACTIVE"] = "Reaktiver Zauber oder Fähigkeit"
L["ICONMENU_RUNES_DESC"] = "Prüft Runen-Abklingzeiten" -- Needs review
L["ICONMENU_SHOWTIMER"] = "Zeige Timer"
L["ICONMENU_SHOWTIMERTEXT"] = "Zeige Timertext" -- Needs review
L["ICONMENU_SHOWTIMERTEXT_DESC"] = "Zeigt einen Timertext für die verbleibende Abklingzeit/Dauer. Benötigt das AddOn 'OmniCC'" -- Needs review
L["ICONMENU_SHOWWHEN"] = "Zeige Symbol, wenn"
L["ICONMENU_SORTASC"] = "Niedrige Dauer" -- Needs review
L["ICONMENU_SORTASC_DESC"] = "Bestätigen Sie dieses Feld um Zaubersprüche mit der niedrigsten Dauer zu priorisieren." -- Needs review
L["ICONMENU_SORTDESC"] = "Hohe Dauer" -- Needs review
L["ICONMENU_SORTDESC_DESC"] = "Bestätigen Sie dieses Feld um Zaubersprüche mit der höchsten Dauer zu priorisieren." -- Needs review
L["ICONMENU_SPELLCOOLDOWN"] = "Zauberspruch Abklingzeit" -- Needs review
L["ICONMENU_SPELLCOOLDOWN_DESC"] = "Prüft die Abklingzeit von Zaubersprüchen in Ihrem Zauberbuch." -- Needs review
L["ICONMENU_SPLIT"] = "In neue Gruppe aufteilen" -- Needs review
L["ICONMENU_SPLIT_DESC"] = "Erstellen Sie eine neue Gruppe und bewegen Sie dieses Symbol in diese hinein. Viele Gruppeneinstellungen werden auf die neue Gruppe übertragen werden." -- Needs review
L["ICONMENU_STACKS_MAX_DESC"] = "Maximale Anzahl Stapel der Aura erlaubt, um das Symbol anzuzeigen." -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "Minimale Anzahl Stapel der Aura benötigt, um das Symbol anzuzeigen." -- Needs review
L["ICONMENU_TARGETTARGET"] = "Ziel des Ziels"
L["ICONMENU_TOTEM"] = "Totem / non-MoG Ghoul"
L["ICONMENU_TOTEM_DESC"] = "Prüft Ihre Totems." -- Needs review
L["ICONMENU_TYPE"] = "Icon Typ"
L["ICONMENU_UNUSABLE"] = "unbenutzbar"
L["ICONMENU_USABLE"] = "Benutzbar"
L["ICONMENU_VEHICLE"] = "Fahrzeug"
L["ICONMENU_WPNENCHANT"] = "Temporäre Waffenverzauberung"
L["ICONMENU_WPNENCHANTTYPE"] = "zu überwachender Waffenplatz"
L["ICONTOCHECK"] = "Zu prüfendes Symbol"
L["ImmuneToMagicCC"] = "Immun gegen magisches CC" -- Needs review
L["ImmuneToStun"] = "Immun gegen Betäubungseffekte" -- Needs review
L["IMPORTERROR_FAILEDPARSE"] = "Es gab einen Fehler beim Auslesen des Strings. Überprüfe, ob der vollständige String von der Quelle kopiert wurde." -- Needs review
L["IMPORT_EXPORT_DESC"] = "Drücke den Pfeil rechts dieses Feldes zum import und export von Symbolen, Gruppen und Profilen." -- Needs review
L["IMPORT_FROMBACKUP"] = "Von Backup" -- Needs review
L["IMPORT_FROMBACKUP_DESC"] = "Einstellungen die aus diesem Menü wiederhergestellt werden sind von: %s" -- Needs review
L["IMPORT_FROMBACKUP_WARNING"] = "Backup Einstellungen: %s" -- Needs review
L["IMPORT_FROMCOMM"] = "Von Spieler"
L["IMPORT_FROMCOMM_DESC"] = "Wenn ein anderer Benutzer von TellMeWhen Ihnen Konfigurationsdaten schickt, können Sie diese von diesem Untermenü importieren." -- Needs review
L["IMPORT_FROMLOCAL"] = "Von Profil" -- Needs review
L["IMPORT_FROMSTRING"] = "Von String (Zeichenkette)" -- Needs review
L["IMPORT_FROMSTRING_DESC"] = "Um einen String zu importieren, drücken Sie STRG+V um den String einzufügen, nachdem Sie es mit STRG-C kopiert haben. Navigieren Sie danach zurück zu diesem Untermenü." -- Needs review
L["IMPORT_HEADING"] = "Import"
L["IMPORT_PROFILE"] = "Profil kopieren"
L["IMPORT_PROFILE_NEW"] = "Neues Profil erstellen" -- Needs review
L["IMPORT_PROFILE_OVERWRITE"] = "|cFFFF5959Überschreibe|r %s" -- Needs review
L["Incapacitated"] = "Bewegungsunfähig"
L["IncreasedAP"] = "Erhöhte Angriffskraft" -- Needs review
L["IncreasedCrit"] = "Erhöhte kritische Trefferchance" -- Needs review
L["IncreasedPhysHaste"] = "Erhöhtes Nahkampfangriffstempo" -- Needs review
L["IncreasedSpellHaste"] = "Erhöhtes Zaubertempo"
L["IncreasedSPsix"] = "Erhöhte Zaubermacht (6%)"
L["IncreasedSPten"] = "Erhöhte Zaubermacht (10%)"
L["IncreasedStats"] = "Erhöhte Attribute"
L["ITEMCOOLDOWN"] = "Item Abklingzeit" -- Needs review
L["LDB_TOOLTIP1"] = "|cff7fffffLinks-Klick|r um die Gruppen fest/freizuschalten." -- Needs review
L["LDB_TOOLTIP2"] = "|cff7fffffRechts-Klick|r um die TMW Hauptoptionen anzuzeigen." -- Needs review
L["LEFT"] = "links"
L["LOCKED"] = "gesperrt"
L["Magic"] = "Magie"
L["!!Main Addon Description"] = "Bietet visuelle, akustische und schriftliche Benachrichtigungen über Cooldowns, Buffs and so ziemlich alles andere."
L["METAPANEL_DOWN"] = "nach unten bewegen" -- Needs review
L["METAPANEL_REMOVE"] = "Dieses Icon entfernen" -- Needs review
L["METAPANEL_UP"] = "nach oben bewegen" -- Needs review
L["MOON"] = "Mond"
L["NEWVERSION"] = "Eine neue Version von TellMeWhen ist verfügbar: %s"
L["NONE"] = "Keine der Folgenden" -- Needs review
L["normal"] = "normal"
L["OUTLINE_NO"] = "Keine Kontur" -- Needs review
L["OUTLINE_THICK"] = "Dicke Kontur" -- Needs review
L["OUTLINE_THIN"] = "Dünne Kontur" -- Needs review
L["PhysicalDmgTaken"] = "Erhaltener physischer Schaden" -- Needs review
L["Poison"] = "Gift"
L["PvPSpells"] = "PVP Crowd Control, usw." -- Needs review
L["rare"] = "Rar" -- Needs review
L["rareelite"] = "Rar Elite" -- Needs review
L["ReducedArmor"] = "Verringerte Rüstungswertung"
L["ReducedCastingSpeed"] = "Verringertes Zaubertempo"
L["ReducedHealing"] = "Verringerte Heilung"
L["ReducedPhysicalDone"] = "Verringerter verursachter physischer Schaden" -- Needs review
L["RESIZE"] = "Größe ändern"
L["RESIZE_TOOLTIP"] = "Klicken und ziehen um die Größe zu ändern" -- Needs review
L["RIGHT"] = "rechts" -- Needs review
L["Rooted"] = "Gewurzelt"
L["Shatterable"] = "Zerschlagbar" -- Needs review
L["Silenced"] = "Zum Schweigen gebracht"
L["SORTBY"] = "sortieren nach" -- Needs review
L["SOUND_EVENT_ONFINISH_DESC"] = "Dieses Ereignis wird ausgelöst, wenn die Abklingzeit abläuft (Buff/Debuff läuft aus etc.)" -- Needs review
L["SOUND_EVENT_ONSPELL"] = "Wenn Zauberspruch verändert" -- Needs review
L["SOUND_EVENT_ONSPELL_DESC"] = "Dieses Ereignis wird ausgelöst, wenn der Zauberspruch/das Item/etc, für die den/das das Symbol Information darstellt, sich ändert." -- Needs review
L["SOUND_EVENT_ONUNIT"] = "Wenn Einheit verändert" -- Needs review
L["SOUND_EVENT_ONUNIT_DESC"] = "Dieses Ereignis wird ausgelöst, wenn die Einheit, für die das Symbol Information darstellt, sich ändert." -- Needs review
L["SpellDamageTaken"] = "Erhöhter Zauberschaden erhalten"
L["STRATA_BACKGROUND"] = "Hintergrund" -- Needs review
L["Stunned"] = "Betäubt"
L["SUG_FINISHHIM_DESC"] = "Dies beendet den Caching/Filtering Prozess sofort. Dies könnte den Rechner einige Sekunden einfrieren." -- Needs review
L["SUG_MATCH_WPNENCH_ENCH"] = "Waffe de[sr] (.-)s?$" -- Needs review
L["SUG_PATTERNMATCH_FISHINGLURE"] = "Angelköder %(%+%d+ Angelfertigkeit%)"
L["SUG_PATTERNMATCH_SHARPENINGSTONE"] = "Geschärft %(%+%d+ Schaden%)"
L["SUG_PATTERNMATCH_WEIGHTSTONE"] = "Beschwert %(%+%d+ Schaden%)"
L["SUN"] = "Sonne"
L["Tier11Interrupts"] = "Tier 11 unterbrechbare Zauber" -- Needs review
L["TOP"] = "oben" -- Needs review
L["TOPLEFT"] = "oben links" -- Needs review
L["TOPRIGHT"] = "oben rechts" -- Needs review
L["TRUE"] = "Wahr"
L["UIPANEL_ADDGROUP"] = "+ Weitere Gruppe hinzufügen +" -- Needs review
L["UIPANEL_ADDGROUP_DESC"] = "Der neuen Gruppe wird die nächste freie GruppenID zugewiesen" -- Needs review
L["UIPANEL_ALLRESET"] = "Alles zurücksetzen"
L["UIPANEL_BARIGNOREGCD"] = "Leisten ignorieren GCD" -- Needs review
L["UIPANEL_BARIGNOREGCD_DESC"] = "Wenn ausgewählt, werden die Abklingzeit-Leisten nicht auf den GCD (globale Abklingzeit) reagieren." -- Needs review
L["UIPANEL_BARTEXTURE"] = "Leistentextur"
L["UIPANEL_CLOCKIGNOREGCD"] = "Timer ignorieren GCD (globale Abklingzeit)." -- Needs review
L["UIPANEL_CLOCKIGNOREGCD_DESC"] = "Wenn ausgewählt, werden Timer und Abklingzeiten nicht vom GCD (globale Abklingzeit) ausgelöst." -- Needs review
L["UIPANEL_COLORS"] = "Farben"
L["UIPANEL_COLUMNS"] = "Spalten"
L["UIPANEL_DELGROUP"] = "Gruppe löschen" -- Needs review
L["UIPANEL_DELGROUP_DESC"] = [=[Alle Gruppen nach dieser Gruppe werden ihre ID um eine hochgesetzt bekommen. Alle Symbole, die Symbole in diesen Gruppen prüfen, werden automatisch aktualisiert.

Halte |cff7fffffStrg|r um diese Kontrolle zu übergehen.]=] -- Needs review
L["UIPANEL_DRAWEDGE"] = "Hervorgehobener Timer-Rand" -- Needs review
L["UIPANEL_DRAWEDGE_DESC"] = "Hervorgehobener Rand um die Abklingzeit (Uhr-Animation), um die Sichtbarkeit zu erhöhen" -- Needs review
L["UIPANEL_ENABLEGROUP"] = "Gruppe aktivieren" -- Needs review
L["UIPANEL_FONT_CONSTRAINWIDTH"] = "Breite beschränken" -- Needs review
L["UIPANEL_FONT_CONSTRAINWIDTH_DESC"] = "Bestätigen Sie dies um den Text zu zwingen innerhalb der Breite des Symbols, sollte dieses korrekt platziert sein, zu passen. Entfernen Sie die Bestätigung um den Text breiter als das Symbol reichen zu lassen." -- Needs review
L["UIPANEL_FONT_DESC"] = "Wähle die Schriftart für den Stapel-Text auf Symbolen." -- Needs review
L["UIPANEL_FONT_OUTLINE"] = "Schriftart-Kontur"
L["UIPANEL_FONT_OUTLINE_DESC"] = "Bestimmt den Konturenstil des Stapel-Textes auf Symbolen." -- Needs review
L["UIPANEL_FONT_SIZE"] = "Zeichengröße"
L["UIPANEL_FONT_SIZE_DESC"] = "Ändert die Zeichengröße für den Stapel-Text auf Symbolen. Wenn Masque (ButtonFacade) benuzt wird und der Masque-Skin eine vordefinierte Schriftgröße hat, wird diese Einstellung ignoriert." -- Needs review
L["UIPANEL_FONT_XOFFS"] = "X Abstand" -- Needs review
L["UIPANEL_FONT_YOFFS"] = "Y Abstand" -- Needs review
L["UIPANEL_GROUPNAME"] = "Gruppe umbennen" -- Needs review
L["UIPANEL_GROUPRESET"] = "Position zurücksetzen"
L["UIPANEL_GROUPS"] = "Gruppen"
L["UIPANEL_ICONSPACING_DESC"] = "Abstand der Symbole in einer Gruppe voneinander." -- Needs review
L["UIPANEL_LOCK"] = "sperre Position" -- Needs review
L["UIPANEL_LOCKUNLOCK"] = "Sperre / Entsperre AddOn" -- Needs review
L["UIPANEL_MAINOPT"] = "Grundeinstellungen"
L["UIPANEL_ONLYINCOMBAT"] = "Nur im Kampf zeigen"
L["UIPANEL_POSITION"] = "Position" -- Needs review
L["UIPANEL_PRIMARYSPEC"] = "Primäre Talentspezialisierung" -- Needs review
L["UIPANEL_ROWS"] = "Zeilen"
L["UIPANEL_SCALE"] = "Massstab" -- Needs review
L["UIPANEL_SECONDARYSPEC"] = "Sekundäre Talentspezialisierung" -- Needs review
L["UIPANEL_SPEC"] = "Dual Spec" -- Needs review
L["UIPANEL_SUBTEXT2"] = "Symbole funktionieren im gesperrten Zustand. Im entsperrten Zustand können Sie die Symbolgruppen bewegen, die Größe ändern und mit einem Rechtsklick einzelne Symbole für weitere Optionen anklicken. Du kannst auch '/tellmewhen' oder /tmw zum sperren / entsperren eingeben." -- Needs review
L["UIPANEL_TOOLTIP_ALLRESET"] = "DATEN und POSITIONEN aller Symbole und Gruppen zurücksetzen"
L["UIPANEL_TOOLTIP_COLUMNS"] = "Setzt die Anzahl der Spalten in dieser Gruppe" -- Needs review
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "Zeige und aktivieren diese Gruppe" -- Needs review
L["UIPANEL_TOOLTIP_GROUPRESET"] = "Position und Größe dieser Gruppe zurücksetzen" -- Needs review
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "Auswählen um diese Gruppe nur im Kampf zu zeigen" -- Needs review
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "Auswählen um diese Gruppe nur in der primären Talentspezialisierung zu zeigen" -- Needs review
L["UIPANEL_TOOLTIP_ROWS"] = "Setzt die Anzahl der Reihen in dieser Gruppe" -- Needs review
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "Auswählen um diese Gruppe nur in der sekundären Talentspezialisierung zu zeigen" -- Needs review
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "Legt fest wie oft (in Sekunden) Symbole auf zeigen/verstecken, Transparenz, Bedingungen usw. überprüft werden. Null ist so schnell wie möglich. Niedrigere Werte können erheblichen Einfluss auf die Framerate für Low-End-Rechner haben." -- Needs review
L["UIPANEL_UPDATEINTERVAL"] = "Aktualisierungs-Intervall" -- Needs review
L["worldboss"] = "Weltboss"
