GlowFoSho_enchants = {
    ["7786"] = {
        ["enchantID"] = "249",
        ["classic"] = true,
        ["name"] = "Minor Beastslayer",
    },
    ["7788"] = {
        ["enchantID"] = "250",
        ["glowless"] = true,
        ["classic"] = true,
        ["name"] = "Minor Striking",
    },
    ["7793"] = {
        ["enchantID"] = "723",
        ["glowless"] = true,
        ["classic"] = true,
        ["name"] = "Lesser Intellect",
        ["is2H"] = true,
    },
    ["7745"] = {
        ["enchantID"] = "241",
        ["glowless"] = true,
        ["classic"] = true,
        ["name"] = "Minor Impact",
        ["is2H"] = true,
    },
    ["13380"] = {
        ["enchantID"] = "255",
        ["glowless"] = true,
        ["classic"] = true,
        ["name"] = "Lesser Spirit",
        ["is2H"] = true,
    },
    ["13503"] = {
        ["enchantID"] = "241",
        ["glowless"] = true,
        ["classic"] = true,
        ["name"] = "Lesser Striking",
    },
    ["13529"] = {
        ["enchantID"] = "943",
        ["classic"] = true,
        ["name"] = "Lesser Impact",
        ["is2H"] = true,
    },
    ["13653"] = {
        ["enchantID"] = "853",
        ["classic"] = true,
        ["name"] = "Lesser Beastslayer",
    },
    ["13655"] = {
        ["enchantID"] = "854",
        ["classic"] = true,
        ["name"] = "Lesser Elemental Slayer",
    },
    ["21931"] = {
        ["enchantID"] = "2443",
        ["glowless"] = true,
        ["classic"] = true,
        ["name"] = "Winter's Might",
    },
    ["13693"] = {
        ["enchantID"] = "943",
        ["classic"] = true,
        ["name"] = "Striking",
    },
    ["13695"] = {
        ["enchantID"] = "1897",
        ["classic"] = true,
        ["name"] = "Impact",
        ["is2H"] = true,
    },
    ["13915"] = {
        ["enchantID"] = "912",
        ["classic"] = true,
        ["name"] = "Demonslaying",
    },
    ["13937"] = {
        ["enchantID"] = "963",
        ["classic"] = true,
        ["name"] = "Greater Impact",
        ["is2H"] = true,
    },
    ["13943"] = {
        ["enchantID"] = "805",
        ["classic"] = true,
        ["name"] = "Greater Striking",
    },
    ["13898"] = {
        ["enchantID"] = "803",
        ["classic"] = true,
        ["name"] = "Fiery Weapon",
    },
    ["20029"] = {
        ["enchantID"] = "1894",
        ["classic"] = true,
        ["name"] = "Icy Chill",
    },
    ["27837"] = {
        ["enchantID"] = "2646",
        ["classic"] = true,
        ["name"] = "Agility",
        ["is2H"] = true,
    },
    ["23800"] = {
        ["enchantID"] = "2564",
        ["classic"] = true,
        ["name"] = "Agility",
    },
    ["23799"] = {
        ["enchantID"] = "2563",
        ["classic"] = true,
        ["name"] = "Strength",
    },
    ["20030"] = {
        ["enchantID"] = "1896",
        ["classic"] = true,
        ["name"] = "Superior Impact",
        ["is2H"] = true,
    },
    ["20033"] = {
        ["enchantID"] = "1899",
        ["classic"] = true,
        ["name"] = "Unholy Weapon",
    },
    ["20036"] = {
        ["enchantID"] = "1904",
        ["classic"] = true,
        ["name"] = "Major Intellect",
        ["is2H"] = true,
    },
    ["20035"] = {
        ["enchantID"] = "1903",
        ["classic"] = true,
        ["name"] = "Major Spirit",
        ["is2H"] = true,
    },
    ["20034"] = {
        ["enchantID"] = "1900",
        ["classic"] = true,
        ["name"] = "Crusader",
    },
    ["22750"] = {
        ["enchantID"] = "2505",
        ["classic"] = true,
        ["name"] = "Healing Power",
    },
    ["20032"] = {
        ["enchantID"] = "1898",
        ["classic"] = true,
        ["name"] = "Lifestealing",
    },
    ["23804"] = {
        ["enchantID"] = "2568",
        ["classic"] = true,
        ["name"] = "Mighty Intellect",
    },
    ["23803"] = {
        ["enchantID"] = "2567",
        ["classic"] = true,
        ["name"] = "Mighty Spirit",
    },
    ["22749"] = {
        ["enchantID"] = "2504",
        ["classic"] = true,
        ["name"] = "Spell Power",
    },
    ["20031"] = {
        ["enchantID"] = "1897",
        ["classic"] = true,
        ["name"] = "Superior Striking",
    },
    ["27968"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2666",
        ["burningcrusade"] = true,
        ["name"] = "Major Intellect",
    },
    ["27967"] = {
        ["lvl"] = 35,
        ["enchantID"] = "963",
        ["burningcrusade"] = true,
        ["name"] = "Major Striking",
    },
    ["27971"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2667",
        ["burningcrusade"] = true,
        ["name"] = "Savagery",
        ["is2H"] = true,
    },
    ["42620"] = {
        ["lvl"] = 35,
        ["enchantID"] = "3222",
        ["burningcrusade"] = true,
        ["name"] = "Greater Agility",
    },
    ["34010"] = {
        ["lvl"] = 35,
        ["enchantID"] = "3846",
        ["burningcrusade"] = true,
        ["name"] = "Major Healing",
    },
    ["27975"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2669",
        ["burningcrusade"] = true,
        ["name"] = "Major Spellpower",
    },
    ["27972"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2668",
        ["burningcrusade"] = true,
        ["name"] = "Potency",
    },
    ["27977"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2670",
        ["burningcrusade"] = true,
        ["name"] = "Major Agility",
        ["is2H"] = true,
    },
    ["28004"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2675",
        ["burningcrusade"] = true,
        ["name"] = "Battlemaster",
    },
    ["28003"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2674",
        ["burningcrusade"] = true,
        ["name"] = "Spellsurge",
    },
    ["42974"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3225",
        ["burningcrusade"] = true,
        ["name"] = "Executioner",
    },
    ["27984"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2673",
        ["burningcrusade"] = true,
        ["name"] = "Mongoose",
    },
    ["27982"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2672",
        ["burningcrusade"] = true,
        ["name"] = "Soulfrost",
    },
    ["27981"] = {
        ["lvl"] = 35,
        ["enchantID"] = "2671",
        ["burningcrusade"] = true,
        ["name"] = "Sunfire",
    },
    ["46578"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3273",
        ["burningcrusade"] = true,
        ["name"] = "Deathfrost",
    },
    ["60621"] = {
        ["lvl"] = 60,
        ["enchantID"] = "1606",
        ["wotlk"] = true,
        ["name"] = "Greater Potency",
    },
    ["44630"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3828",
        ["wotlk"] = true,
        ["name"] = "Greater Savagery",
        ["is2H"] = true,
    },
    ["44629"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3830",
        ["wotlk"] = true,
        ["name"] = "Exceptional Spellpower",
    },
    ["44633"] = {
        ["lvl"] = 60,
        ["enchantID"] = "1103",
        ["wotlk"] = true,
        ["name"] = "Exceptional Agility",
    },
    ["44510"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3844",
        ["wotlk"] = true,
        ["name"] = "Exceptional Spirit",
    },
    ["44524"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3239",
        ["wotlk"] = true,
        ["name"] = "Icebreaker",
    },
    ["60691"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3827",
        ["wotlk"] = true,
        ["name"] = "Massacre",
        ["is2H"] = true,
    },
    ["44595"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3247",
        ["wotlk"] = true,
        ["name"] = "Scourgebane",
        ["is2H"] = true,
    },
    ["44621"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3251",
        ["wotlk"] = true,
        ["name"] = "Giant Slayer",
    },
    ["60714"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3834",
        ["wotlk"] = true,
        ["name"] = "Mighty Spellpower",
    },
    ["60707"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3833",
        ["wotlk"] = true,
        ["name"] = "Superior Potency",
    },
    ["59619"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3788",
        ["wotlk"] = true,
        ["name"] = "Accuracy",
    },
    ["59621"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3789",
        ["wotlk"] = true,
        ["name"] = "Berserking",
    },
    ["59625"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3790",
        ["wotlk"] = true,
        ["name"] = "Black Magic",
    },
    ["44576"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3241",
        ["wotlk"] = true,
        ["name"] = "Lifeward",
    },
    ["55836"] = {
        ["lvl"] = 70,
        ["enchantID"] = "3731",
        ["wotlk"] = true,
        ["name"] = "Titanium Weapon Chain",
    },
    ["64579"] = {
        ["lvl"] = 75,
        ["enchantID"] = "3870",
        ["wotlk"] = true,
        ["name"] = "Blood Draining",
    },
    ["64441"] = {
        ["lvl"] = 75,
        ["enchantID"] = "3869",
        ["wotlk"] = true,
        ["name"] = "Blade Ward",
    },
    ["62959"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3855",
        ["wotlk"] = true,
        ["name"] = "Spellpower",
        ["is2H"] = true,
    },
    ["62948"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3854",
        ["wotlk"] = true,
        ["name"] = "Greater Spellpower",
        ["is2H"] = true,
    },
    ["95471"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4227",
        ["cata"] = true,
        ["name"] = "Mighty Agility",
        ["is2H"] = true,
    },
    ["74197"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4067",
        ["cata"] = true,
        ["name"] = "Avalanche",
    },
    ["74211"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4074",
        ["cata"] = true,
        ["name"] = "Elemental Slayer",
    },
    ["74225"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4084",
        ["cata"] = true,
        ["name"] = "Heartsong",
    },
    ["74223"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4083",
        ["cata"] = true,
        ["name"] = "Hurricane",
    },
    ["74246"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4099",
        ["cata"] = true,
        ["name"] = "Landslide",
    },
    ["74195"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4066",
        ["cata"] = true,
        ["name"] = "Mending",
    },
    ["74242"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4097",
        ["cata"] = true,
        ["name"] = "Power Torrent",
    },
    ["74244"] = {
        ["lvl"] = 80,
        ["enchantID"] = "4098",
        ["cata"] = true,
        ["name"] = "Windwalk",
    },
    ["53341"] = {
        ["lvl"] = 55,
        ["enchantID"] = "3369",
        ["runes"] = true,
        ["name"] = "Rune of Cinderglacier",
    },
    ["53343"] = {
        ["lvl"] = 55,
        ["enchantID"] = "3370",
        ["runes"] = true,
        ["name"] = "Rune of Razorice",
    },
    ["54447"] = {
        ["lvl"] = 57,
        ["enchantID"] = "3595",
        ["runes"] = true,
        ["name"] = "Rune of Spellbreaking",
    },
    ["53342"] = {
        ["lvl"] = 57,
        ["enchantID"] = "3367",
        ["runes"] = true,
        ["name"] = "Rune of Spellshattering",
        ["is2H"] = true,
    },
    ["53331"] = {
        ["lvl"] = 60,
        ["enchantID"] = "3366",
        ["runes"] = true,
        ["name"] = "Rune of Lichbane",
    },
    ["54446"] = {
        ["lvl"] = 63,
        ["enchantID"] = "3594",
        ["runes"] = true,
        ["name"] = "Rune of Swordbreaking",
    },
    ["53323"] = {
        ["lvl"] = 63,
        ["enchantID"] = "3365",
        ["runes"] = true,
        ["name"] = "Rune of Swordshattering",
        ["is2H"] = true,
    },
    ["53344"] = {
        ["lvl"] = 70,
        ["enchantID"] = "3368",
        ["runes"] = true,
        ["name"] = "Rune of the Fallen Crusader",
    },
    ["70164"] = {
        ["lvl"] = 72,
        ["enchantID"] = "3883",
        ["runes"] = true,
        ["name"] = "Rune of the Nerubian Carapace",
    },
    ["62158"] = {
        ["lvl"] = 72,
        ["enchantID"] = "3847",
        ["runes"] = true,
        ["name"] = "Rune of the Stoneskin Gargoyle",
        ["is2H"] = true,
    },
    ["55057"] = {
        ["lvl"] = 81,
        ["enchantID"] = "4217",
        ["cata"] = true,
        ["name"] = "Pyrium Weapon Chain",
    },
    ["104430"] = {
        ["lvl"] = 85,
        ["enchantID"] = "4443",
        ["mop"] = true,
        ["name"] = "Elemental Force",
    },
    ["104425"] = {
        ["lvl"] = 85,
        ["enchantID"] = "4441",
        ["mop"] = true,
        ["name"] = "Windsong",
    },
    ["104440"] = {
        ["lvl"] = 85,
        ["enchantID"] = "4445",
        ["mop"] = true,
        ["name"] = "Colossus",
    },
    ["104434"] = {
        ["lvl"] = 85,
        ["enchantID"] = "4444",
        ["mop"] = true,
        ["name"] = "Dancing Steel",
    },
    ["104427"] = {
        ["lvl"] = 85,
        ["enchantID"] = "4442",
        ["mop"] = true,
        ["name"] = "Jade Spirit",
    },
    ["104442"] = {
        ["lvl"] = 85,
        ["enchantID"] = "4446",
        ["mop"] = true,
        ["name"] = "River's Song",
    },
    ["139631"] = {
        ["lvl"] = 85,
        ["enchantID"] = "5035",
        ["mop"] = true,
        ["name"] = "Glorious Tyranny",
    },

}