local addonName = ...
local VERSION = GetAddOnMetadata(addonName, "Version")
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "enUS", true)
if not L then return end 
L["Helm"] = true;
L["Neck"] = true;
L["Shoulders"] = true;
L["Chest"] = true;
L["Belt"] = true;
L["Legs"] = true;
L["Boots"] = true;
L["Bracers"] = true;
L["Gloves"] = true;
L["Ring 1"] = true;
L["Ring 2"] = true;
L["Trinket 1"] = true;
L["Trinket 2"] = true;
L["Cloak"] = true;
L["Main Hand"] = true;
L["Off Hand"] = true;
L["Equipped Average Item Level Tooltip"] = true;
L["Version "] = true;
L[" by Isoloedlk of US-Khaz Modan"] = true;
L["Show Specialization"] = true;
L["Show Item List"] = true;
L["Decimal Places"] = true;
L["Inspect Request Delay"] = true;
L['Name'] = true;
L['Specialization'] = true;
L['Equipped iLvl'] = true;
L["You are not in a group."] = true;
L["You are in PvP."] = true;
L["None"] = true;
L["Unknown"] = true;
L["Group Item Levels:"] = true;
L["ilvl(s): Loading..."] = true;
L["ilvl(s): "] = true;
L["A newer version is available.  Visit http://www.wowinterface.com to download the latest version."] = true;
L["Spec:"] = true;
L["iLvl:"] = true;
L["PVP:"] = true;
L["None/Not Scanned"] = true;