local addonName = ...
local VERSION = GetAddOnMetadata(addonName, "Version")
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "zhTW")
if not L then return end 
L["Helm"] = "頭部"
L["Neck"] = "頸部"
L["Shoulders"] = "肩部"
L["Chest"] = "胸部"
L["Belt"] = "腰部"
L["Legs"] = "腿部"
L["Boots"] = "腳部"
L["Bracers"] = "手腕"
L["Gloves"] = "手部"
L["Ring 1"] = "手指 1"
L["Ring 2"] = "手指 2"
L["Trinket 1"] = "飾品 1"
L["Trinket 2"] = "飾品 2"
L["Cloak"] = "背部"
L["Main Hand"] = "主手"
L["Off Hand"] = "副手"
L["Equipped Average Item Level Tooltip"] = "Equipped Average Item Level Tooltip"
L["Version "] = "版本 "
L[" by Isoloedlk of US-Khaz Modan"] = " 由 US-Khaz Modan 的 Isoloedlk 製作"
L["Show Specialization"] = "顯示天賦樹"
L["Show Item List"] = "顯示物品列表"
L["Decimal Places"] = "小數點位置"
L["Inspect Request Delay"] = "查看請求延遲"
L['Name'] = '名字';
L['Specialization'] = '專精';
L['Equipped iLvl'] = '已裝備物品等級';
L["You are not in a group."] = "你不在一個隊伍中.";
L["You are in PvP."] = "你在 PvP 中.";
L["None"] = "無";
L["Unknown"] = "未知";
L["Group Item Levels:"] = "隊伍物品等級:";
L["ilvl(s): Loading..."] = "物品等級: 載入中...";
L["ilvl(s): "] = "物品等級: ";
L["A newer version is available.  Visit http://www.wowinterface.com to download the latest version."] = "新版本可用.  訪問://www.wowinterface.com 下載最新版本."
L["Spec:"] = "專精:";
L["iLvl:"] = "物品等級:";
L["PVP:"] = "PVP:";
L["None/Not Scanned"] = "無/未掃描";