if GetLocale() == "zhCN" then
	BINDING_HEADER_GOGOHEADER = "GoGoMount 按键绑定" -- Needs review
	BINDING_NAME_GOGOBINDING = "召唤坐骑/解散坐骑 按键绑定" -- Needs review
	BINDING_NAME_GOGOBINDING2 = "召唤/解散坐骑 (非飞行坐骑) 按键绑定" -- Needs review
	BINDING_NAME_GOGOBINDING3 = "召唤/解散多人坐骑 按键绑定" -- Needs review
	GoGo_Variables.Localize = {
	Skill = {
		Engineering = "工程学",
		Riding = "骑术",
		Tailoring = "裁缝",
	},
	String = {
		AutomaticallyRemoveBuffs = "自动移除影响召唤坐骑的Buff",
		AutoStartCrusaderAura = "自动开启十字军光环",
		AutoStartCrusaderAura_Long = "当使用GoGoMount召唤坐骑时，自动开启十字军光环。",
		Clear = "清除",
		ClearGlobalFavoriteMounts = "清除全局收藏",
		CurrentZone = "当前区域",
		CurrentZoneDescription = "Mounts flagged here as zone favorites will be the only mounts GoGoMount will use in this zone.  All other mounts and shape forms will be ignored.  Clearing this list will allow GoGoMount to use all mounts (or global favorites if set).", -- Requires localization
		CurrentZoneExclusions = "当前区域排除",
		CurrentZoneFavorites = "当前地域收藏",
		DisableFlyingFromWater = "防止在水中时召唤飞行坐骑",
		DisableInCombat = "在战斗中禁用GoGoMount按钮",
		DisableInCombat_Long = "这个选项将在战斗中禁用GoGoMount 按钮。这个选项对于熊坦来说很有用。必须在战斗前来启用或禁用。",
		DisableUnknownMountNotices = "关闭未知坐骑提示",
		DisableUpdateNotices = "关闭更新提示",
		DruidFlightPreference = "在角色移动的情况下总是使用飞行形态",
		DruidOptions = "德鲁伊选项",
		DruidSingleClick = "一键切换至旅行形态",
		EnableAutoDismount = "开启自动解散坐骑",
		ExtraPassengerMounts = "Extra Passenger Mounts", -- Requires localization
		ExtraPassengerMountsDescription = "This list of passenger mounts is used to add passenger mounts to the random selection only when the Passenger Mount button is pressed.  This will allow you to set preferred mount lists excluding passenger mounts but still have them available when using the Passenger Mount button.  These mounts will not be used if they are marked as excluded mounts globally or for the current zone you are in.", -- Requires localization
		Favorites = "收藏",
		GlobalExclusions = "全局排除",
		GlobalExclusionsDescription = "坐骑将始终被忽略。这里选择的坐骑，即使设置为我的收藏，他们将不会被使用。",
		GlobalFavorites = "全局收藏",
		GlobalPreferences = "全局优先",
		GlobalZoneDescription = "Preferred mounts defined here will only take effect if there are no zone specific mount favorites set for the current zone you are in.", -- Requires localization
		HunterOptions = "猎人选项",
		NewVersionFound = "GoGoMount 有新版本可更新",
		NoShapeInRandom = "Do not randomize shape forms with mounts", -- Requires localization
		PaladinOptions = "圣骑士选项",
		RemoveBuffs = "移除会影响召唤坐骑的Buffs",
		RemoveBuffs_Long = "GoGoMount将会尝试移除那些妨碍坐骑的Buf和姿态变形。这个仅为已知的Buff以及一些需要2次点击你的GoGoMount上马时才会执行。",
		ShamanOptions = "Shaman Options", -- Requires localization
		ShamanSingleClick = "Single click mount from Ghost Wolf Form instead of dismounting", -- Requires localization
		UnknownMountFound = "在您的坐骑列表中发现一个未知的坐骑.请报告,以便在未来版本中加入",
		UseAspectOfThePackInstead = "使用豹群守护替代猎豹守护",
		UseAspectOfThePackInstead_Long = "When enabled, GoGoMount will cast Aspect of the Pack instead of Aspect of the Cheetah.  Local zone or global settings override this setting.  If this is set to use Aspect of the Pack and you have Aspect of the Cheetah as a zone favorite, Aspect of the Cheetah will be used.", -- Requires localization
		ZoneExclusionsDescription = "Zone specific exclusions work the same as global exclusions but specific to this zone.  Any mount marked below as an exclusion for the zone you're currently in will never be summoned.", -- Requires localization
	},
	Talent = {
		AncestralSwiftness = "先祖迅捷",
		FeralSwiftness = "豹之迅捷",
	},
	Zone = {
		AbyssalDepths = "无底海渊",
		AmaniMountains = "阿曼尼山岭",
		AQ40 = "安其拉神殿",
		AzuremystIsle = "秘蓝岛",
		BloodmystIsle = "秘血岛",
		CrumblingDepths = "碎岩之渊",
		Dalaran = "达拉然",
		DarkbreakCove = "驱暗海窟",
		Deepholm = "深岩之洲",
		DireMaul = "厄运之槌",
		EversongWoods = "永歌森林",
		Ghostlands = "幽魂之地",
		Icecrown = "冰冠冰川",
		Ironforge = "铁炉堡",
		IsleOfQuelDanas = "奎尔丹纳斯岛",
		KrasusLanding = "克拉苏斯平台",
		LegionsRest = "军团营地",
		Lghorek = "拉葛雷克",
		Nespirah = "奈瑟匹拉",
		ShimmeringExpanse = "烁光海床",
		SholazarBasin = "索拉查盆地",
		SilvermoonCity = "银月城",
		SilverTideHollow = "银潮谷",
		TempleOfBethekk = "贝瑟克神殿",
		TempleOfEarth = "大地神殿",
		TenebrousCavern = "阴暗洞穴",
		ThalassianPass = "萨拉斯小径",
		ThalassianRange = "萨拉斯山脉",
		TheCerebrillum = "脑室",
		TheExodar = "埃索达",
		TheFrozenSea = "冰冻之海",
		TheOculus = "魔环",
		TheStormPeaks = "风暴峭壁",
		TheTempleOfAtalHakkar = "阿塔哈卡神庙",
		TheUnderbelly = "达拉然下水道",
		TheVioletCitadel = "紫罗兰城堡",
		TheVortexPinnacle = "旋云之巅",
		TolBarad = "托尔巴拉德",
		TolBaradPeninsula = "托尔巴拉德半岛",
		TwistingNether = "扭曲虚空",
		Vashjir = "瓦丝琪尔",
		Wintergrasp = "冬拥湖",
	},
}

end --if