if (GetLocale() ~= "esES") then return end

MHExRTL.panelbossmodsradenonly25 = "Sólo para 25m"
MHExRTL.panelbossmodsalpha = "Transparencia"
MHExRTL.panelbossmodsscale = "Escala"
MHExRTL.panelbossmodsclose = "Cerrar"
MHExRTL.panelbossmodsmalkorok ="Malkorok"
MHExRTL.panelbossmodsmalkorokh = "Malkorok Helper"
MHExRTL.panelbossmodsmalkorokai ="Malkorok AI"
MHExRTL.panelbossmodsmalkorokhelp ="Malkorok bossmod. Click izquierdo para elegir, click derecho para cancelar."
MHExRTL.panelbossmodsmalkorokaihelp ="Malkorok AI bossmod. Selección automática con el menor número de personas durante el área. Estará en naranja durante 5 segundos.  Suficiente para ser avisado al mismo tiempo por una persona con ayudante en Raid."
MHExRTL.panelbossmodsmalkorokdanger ="! Peligro !"
MHExRTL.panelsetauthor = "Autor"
MHExRTL.panelbossmodhelptext = "+ Cuadro principal\n   - 'castle' - permite mover el cuadro.\n   - 'cog' - cambia el estilo de mostrar 'rotando' / 'fijo'.\n   - Círculo principal. Click derecho en el área seleccionada para pintarla en verde, click izquierdo para pintarla en rojo. Tu decisión la verá toda la banda si tienes ayudante o si eres el líder.\n   - El icono de Aliento de Y'Shaarj muestra el tiempo estimado hasta el siguiente área.\n+ Malkorok AI\n   - Seleccionar la región con la menor cantidad de personas durante el área y marcarla automáticamente. En 5 segundos, el área se volverá amarilla. En el caso de elegir mal, puedes corregir el error manualmente."
MHExRTL.panelsettranslate = "Traductor: Krovikan - Minahonda"
MHExRTL.panelbossmodsautoload = "Automáticamente cargar"
MHExRTL.panelbossmodsThanks = "Agradecimientos"